// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation struct {
	// Types that are valid to be assigned to Op:
	//	*Operation_Acop
	//	*Operation_Top
	Op                   isOperation_Op `protobuf_oneof:"op"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

type isOperation_Op interface {
	isOperation_Op()
}

type Operation_Acop struct {
	Acop *AccountCreateOperation `protobuf:"bytes,1,opt,name=acop,proto3,oneof"`
}

type Operation_Top struct {
	Top *TransferOperation `protobuf:"bytes,2,opt,name=top,proto3,oneof"`
}

func (*Operation_Acop) isOperation_Op() {}

func (*Operation_Top) isOperation_Op() {}

func (m *Operation) GetOp() isOperation_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *Operation) GetAcop() *AccountCreateOperation {
	if x, ok := m.GetOp().(*Operation_Acop); ok {
		return x.Acop
	}
	return nil
}

func (m *Operation) GetTop() *TransferOperation {
	if x, ok := m.GetOp().(*Operation_Top); ok {
		return x.Top
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Operation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Operation_OneofMarshaler, _Operation_OneofUnmarshaler, _Operation_OneofSizer, []interface{}{
		(*Operation_Acop)(nil),
		(*Operation_Top)(nil),
	}
}

func _Operation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Operation)
	// op
	switch x := m.Op.(type) {
	case *Operation_Acop:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Acop); err != nil {
			return err
		}
	case *Operation_Top:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Top); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Operation.Op has unexpected type %T", x)
	}
	return nil
}

func _Operation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Operation)
	switch tag {
	case 1: // op.acop
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AccountCreateOperation)
		err := b.DecodeMessage(msg)
		m.Op = &Operation_Acop{msg}
		return true, err
	case 2: // op.top
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TransferOperation)
		err := b.DecodeMessage(msg)
		m.Op = &Operation_Top{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Operation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Operation)
	// op
	switch x := m.Op.(type) {
	case *Operation_Acop:
		s := proto.Size(x.Acop)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_Top:
		s := proto.Size(x.Top)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// transaction
type Transaction struct {
	RefBlockNum          uint32        `protobuf:"varint,1,opt,name=ref_block_num,json=refBlockNum,proto3" json:"ref_block_num,omitempty"`
	RefBlockPrefix       uint32        `protobuf:"varint,2,opt,name=ref_block_prefix,json=refBlockPrefix,proto3" json:"ref_block_prefix,omitempty"`
	Expiration           *TimePointSec `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Operations           []*Operation  `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetRefBlockNum() uint32 {
	if m != nil {
		return m.RefBlockNum
	}
	return 0
}

func (m *Transaction) GetRefBlockPrefix() uint32 {
	if m != nil {
		return m.RefBlockPrefix
	}
	return 0
}

func (m *Transaction) GetExpiration() *TimePointSec {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *Transaction) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type SignedTransaction struct {
	Trx                  *Transaction     `protobuf:"bytes,1,opt,name=trx,proto3" json:"trx,omitempty"`
	Signatures           []*SignatureType `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignedTransaction) Reset()         { *m = SignedTransaction{} }
func (m *SignedTransaction) String() string { return proto.CompactTextString(m) }
func (*SignedTransaction) ProtoMessage()    {}
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *SignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedTransaction.Unmarshal(m, b)
}
func (m *SignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedTransaction.Marshal(b, m, deterministic)
}
func (m *SignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedTransaction.Merge(m, src)
}
func (m *SignedTransaction) XXX_Size() int {
	return xxx_messageInfo_SignedTransaction.Size(m)
}
func (m *SignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SignedTransaction proto.InternalMessageInfo

func (m *SignedTransaction) GetTrx() *Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

func (m *SignedTransaction) GetSignatures() []*SignatureType {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type TransactionInvoice struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	VmError              bool     `protobuf:"varint,2,opt,name=vm_error,json=vmError,proto3" json:"vm_error,omitempty"`
	VmErrorCode          uint32   `protobuf:"varint,3,opt,name=vm_error_code,json=vmErrorCode,proto3" json:"vm_error_code,omitempty"`
	VmErrorMsg           string   `protobuf:"bytes,4,opt,name=vm_error_msg,json=vmErrorMsg,proto3" json:"vm_error_msg,omitempty"`
	GasUsage             uint64   `protobuf:"varint,5,opt,name=gas_usage,json=gasUsage,proto3" json:"gas_usage,omitempty"`
	VmConsole            string   `protobuf:"bytes,6,opt,name=vm_console,json=vmConsole,proto3" json:"vm_console,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionInvoice) Reset()         { *m = TransactionInvoice{} }
func (m *TransactionInvoice) String() string { return proto.CompactTextString(m) }
func (*TransactionInvoice) ProtoMessage()    {}
func (*TransactionInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *TransactionInvoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInvoice.Unmarshal(m, b)
}
func (m *TransactionInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInvoice.Marshal(b, m, deterministic)
}
func (m *TransactionInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInvoice.Merge(m, src)
}
func (m *TransactionInvoice) XXX_Size() int {
	return xxx_messageInfo_TransactionInvoice.Size(m)
}
func (m *TransactionInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInvoice proto.InternalMessageInfo

func (m *TransactionInvoice) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TransactionInvoice) GetVmError() bool {
	if m != nil {
		return m.VmError
	}
	return false
}

func (m *TransactionInvoice) GetVmErrorCode() uint32 {
	if m != nil {
		return m.VmErrorCode
	}
	return 0
}

func (m *TransactionInvoice) GetVmErrorMsg() string {
	if m != nil {
		return m.VmErrorMsg
	}
	return ""
}

func (m *TransactionInvoice) GetGasUsage() uint64 {
	if m != nil {
		return m.GasUsage
	}
	return 0
}

func (m *TransactionInvoice) GetVmConsole() string {
	if m != nil {
		return m.VmConsole
	}
	return ""
}

type TransactionWrapper struct {
	SigTrx               *SignedTransaction  `protobuf:"bytes,1,opt,name=sig_trx,json=sigTrx,proto3" json:"sig_trx,omitempty"`
	Invoice              *TransactionInvoice `protobuf:"bytes,2,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TransactionWrapper) Reset()         { *m = TransactionWrapper{} }
func (m *TransactionWrapper) String() string { return proto.CompactTextString(m) }
func (*TransactionWrapper) ProtoMessage()    {}
func (*TransactionWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *TransactionWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionWrapper.Unmarshal(m, b)
}
func (m *TransactionWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionWrapper.Marshal(b, m, deterministic)
}
func (m *TransactionWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionWrapper.Merge(m, src)
}
func (m *TransactionWrapper) XXX_Size() int {
	return xxx_messageInfo_TransactionWrapper.Size(m)
}
func (m *TransactionWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionWrapper proto.InternalMessageInfo

func (m *TransactionWrapper) GetSigTrx() *SignedTransaction {
	if m != nil {
		return m.SigTrx
	}
	return nil
}

func (m *TransactionWrapper) GetInvoice() *TransactionInvoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

// block
type BlockHeader struct {
	Previous              *Sha256       `protobuf:"bytes,1,opt,name=previous,proto3" json:"previous,omitempty"`
	Timestamp             *TimePointSec `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Witness               string        `protobuf:"bytes,3,opt,name=witness,proto3" json:"witness,omitempty"`
	TransactionMerkleRoot *Sha256       `protobuf:"bytes,4,opt,name=transaction_merkle_root,json=transactionMerkleRoot,proto3" json:"transaction_merkle_root,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetPrevious() *Sha256 {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() *TimePointSec {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeader) GetWitness() string {
	if m != nil {
		return m.Witness
	}
	return ""
}

func (m *BlockHeader) GetTransactionMerkleRoot() *Sha256 {
	if m != nil {
		return m.TransactionMerkleRoot
	}
	return nil
}

type SignedBlockHeader struct {
	Header               *BlockHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WitnessSignature     *SignatureType `protobuf:"bytes,2,opt,name=witness_signature,json=witnessSignature,proto3" json:"witness_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignedBlockHeader) Reset()         { *m = SignedBlockHeader{} }
func (m *SignedBlockHeader) String() string { return proto.CompactTextString(m) }
func (*SignedBlockHeader) ProtoMessage()    {}
func (*SignedBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *SignedBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBlockHeader.Unmarshal(m, b)
}
func (m *SignedBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBlockHeader.Marshal(b, m, deterministic)
}
func (m *SignedBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBlockHeader.Merge(m, src)
}
func (m *SignedBlockHeader) XXX_Size() int {
	return xxx_messageInfo_SignedBlockHeader.Size(m)
}
func (m *SignedBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBlockHeader proto.InternalMessageInfo

func (m *SignedBlockHeader) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedBlockHeader) GetWitnessSignature() *SignatureType {
	if m != nil {
		return m.WitnessSignature
	}
	return nil
}

type SignedBlock struct {
	SignedHeader         *SignedBlockHeader    `protobuf:"bytes,1,opt,name=signed_header,json=signedHeader,proto3" json:"signed_header,omitempty"`
	Transactions         []*TransactionWrapper `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SignedBlock) Reset()         { *m = SignedBlock{} }
func (m *SignedBlock) String() string { return proto.CompactTextString(m) }
func (*SignedBlock) ProtoMessage()    {}
func (*SignedBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{7}
}

func (m *SignedBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBlock.Unmarshal(m, b)
}
func (m *SignedBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBlock.Marshal(b, m, deterministic)
}
func (m *SignedBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBlock.Merge(m, src)
}
func (m *SignedBlock) XXX_Size() int {
	return xxx_messageInfo_SignedBlock.Size(m)
}
func (m *SignedBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBlock proto.InternalMessageInfo

func (m *SignedBlock) GetSignedHeader() *SignedBlockHeader {
	if m != nil {
		return m.SignedHeader
	}
	return nil
}

func (m *SignedBlock) GetTransactions() []*TransactionWrapper {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Operation)(nil), "prototype.operation")
	proto.RegisterType((*Transaction)(nil), "prototype.transaction")
	proto.RegisterType((*SignedTransaction)(nil), "prototype.signed_transaction")
	proto.RegisterType((*TransactionInvoice)(nil), "prototype.transaction_invoice")
	proto.RegisterType((*TransactionWrapper)(nil), "prototype.transaction_wrapper")
	proto.RegisterType((*BlockHeader)(nil), "prototype.block_header")
	proto.RegisterType((*SignedBlockHeader)(nil), "prototype.signed_block_header")
	proto.RegisterType((*SignedBlock)(nil), "prototype.signed_block")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x41, 0x73, 0xd3, 0x3c,
	0x10, 0xfd, 0xdc, 0xe4, 0x4b, 0xe2, 0x4d, 0x02, 0xad, 0x0a, 0xad, 0x5b, 0xa6, 0x9d, 0x8c, 0xb9,
	0xe4, 0x42, 0x19, 0x02, 0x14, 0x7a, 0x6d, 0x07, 0xa6, 0x1c, 0xca, 0x30, 0x02, 0xce, 0x1a, 0xd5,
	0xd9, 0xb8, 0x9e, 0xd6, 0x96, 0x47, 0x52, 0xd2, 0xf4, 0xc4, 0x91, 0x1b, 0x57, 0xfe, 0x13, 0xc3,
	0x3f, 0xe0, 0xcf, 0x30, 0x96, 0x65, 0x47, 0x09, 0x81, 0x4b, 0xe2, 0x5d, 0xbd, 0x27, 0xbd, 0x7d,
	0x7a, 0x82, 0x2d, 0x2d, 0x79, 0xa6, 0x78, 0xa4, 0x13, 0x91, 0x1d, 0xe5, 0x52, 0x68, 0x41, 0x7c,
	0xf3, 0xa7, 0xef, 0x72, 0xdc, 0x87, 0xe2, 0xb7, 0x6c, 0xef, 0xdf, 0x17, 0x39, 0x4a, 0xbe, 0xc0,
	0x85, 0x5f, 0xc0, 0xaf, 0x5b, 0xe4, 0x04, 0x9a, 0x3c, 0x12, 0x79, 0xe0, 0x0d, 0xbc, 0x61, 0x77,
	0xf4, 0xf8, 0xa8, 0xde, 0xe3, 0x88, 0x47, 0x91, 0x98, 0x66, 0x9a, 0x45, 0x12, 0xb9, 0x46, 0x56,
	0x53, 0xce, 0xff, 0xa3, 0x86, 0x42, 0x9e, 0x41, 0x43, 0x8b, 0x3c, 0xd8, 0x30, 0xcc, 0x03, 0x87,
	0x69, 0xa4, 0x4d, 0x50, 0x2e, 0x71, 0x0a, 0xec, 0x69, 0x13, 0x36, 0x44, 0x1e, 0xfe, 0xf4, 0xa0,
	0xeb, 0xc8, 0x27, 0x21, 0xf4, 0x25, 0x4e, 0xd8, 0xe5, 0x8d, 0x88, 0xae, 0x59, 0x36, 0x4d, 0x8d,
	0x98, 0x3e, 0xed, 0x4a, 0x9c, 0x9c, 0x16, 0xbd, 0xf7, 0xd3, 0x94, 0x0c, 0x61, 0x73, 0x81, 0xc9,
	0x25, 0x4e, 0x92, 0xb9, 0x39, 0xb9, 0x4f, 0xef, 0x55, 0xb0, 0x0f, 0xa6, 0x4b, 0x4e, 0x00, 0x70,
	0x9e, 0x27, 0xe5, 0xc1, 0x41, 0xc3, 0xa8, 0xdb, 0x73, 0xd5, 0x25, 0x29, 0xb2, 0x5c, 0x24, 0x99,
	0x66, 0x0a, 0x23, 0xea, 0x80, 0xc9, 0x0b, 0x80, 0x5a, 0xb2, 0x0a, 0x9a, 0x83, 0xc6, 0xb0, 0x3b,
	0x7a, 0xe0, 0x50, 0xeb, 0x45, 0xea, 0xe0, 0xc2, 0x3b, 0x20, 0x2a, 0x89, 0x33, 0x1c, 0x33, 0x77,
	0xa8, 0x21, 0x34, 0xb4, 0x9c, 0x5b, 0x5f, 0x77, 0x56, 0xdd, 0x29, 0x41, 0xb4, 0x80, 0x14, 0x82,
	0x0b, 0x3e, 0xd7, 0x53, 0x89, 0x2a, 0xd8, 0x30, 0xa7, 0xba, 0x82, 0xeb, 0x45, 0x56, 0x94, 0xd4,
	0x01, 0x87, 0x3f, 0x3c, 0xd8, 0x76, 0xf6, 0x63, 0x49, 0x36, 0x13, 0x49, 0x84, 0x64, 0x07, 0x5a,
	0x4a, 0x73, 0x3d, 0x55, 0xd6, 0x4a, 0x5b, 0x91, 0x3d, 0xe8, 0xcc, 0x52, 0x86, 0x52, 0x0a, 0x69,
	0xdc, 0xeb, 0xd0, 0xf6, 0x2c, 0x7d, 0x53, 0x94, 0xc5, 0x25, 0x54, 0x4b, 0x2c, 0x12, 0x63, 0x34,
	0xce, 0xf5, 0x69, 0xd7, 0xae, 0x9f, 0x89, 0x31, 0x92, 0x01, 0xf4, 0x6a, 0x4c, 0xaa, 0xe2, 0xa0,
	0x39, 0xf0, 0x86, 0x3e, 0x05, 0x0b, 0xb9, 0x50, 0x31, 0x79, 0x04, 0x7e, 0xcc, 0x15, 0x9b, 0x2a,
	0x1e, 0x63, 0xf0, 0xff, 0xc0, 0x1b, 0x36, 0x69, 0x27, 0xe6, 0xea, 0x73, 0x51, 0x93, 0x03, 0x80,
	0x59, 0xca, 0x22, 0x91, 0x29, 0x71, 0x83, 0x41, 0xcb, 0x90, 0xfd, 0x59, 0x7a, 0x56, 0x36, 0xc2,
	0xaf, 0x2b, 0xc3, 0xdc, 0x4a, 0x9e, 0xe7, 0x28, 0xc9, 0x31, 0xb4, 0x55, 0x12, 0xb3, 0x85, 0x9b,
	0x07, 0x2b, 0xe6, 0x2c, 0x3b, 0x4f, 0x5b, 0x2a, 0x89, 0x3f, 0xc9, 0x39, 0x79, 0x0d, 0x6d, 0xeb,
	0x87, 0xcd, 0xe8, 0xe1, 0xfa, 0x5b, 0xa8, 0x5c, 0xa3, 0x15, 0x3c, 0xfc, 0xe5, 0x41, 0xaf, 0x4c,
	0xda, 0x15, 0xf2, 0x31, 0x4a, 0xf2, 0x04, 0x3a, 0xb9, 0xc4, 0x59, 0x22, 0xac, 0xa3, 0xdd, 0xd1,
	0x96, 0xab, 0xe1, 0x8a, 0x8f, 0x5e, 0x1e, 0xd3, 0x1a, 0x42, 0x5e, 0x81, 0x5f, 0xa4, 0x4c, 0x69,
	0x9e, 0x56, 0xef, 0xe3, 0x1f, 0x09, 0x5c, 0x60, 0x49, 0x00, 0xed, 0xdb, 0x44, 0x67, 0xa8, 0x94,
	0xb1, 0xdf, 0xa7, 0x55, 0x49, 0xde, 0xc1, 0xae, 0x2b, 0x39, 0x45, 0x79, 0x7d, 0x83, 0x4c, 0x0a,
	0xa1, 0xcd, 0x2d, 0xac, 0x15, 0xf4, 0xd0, 0x61, 0x5c, 0x18, 0x02, 0x15, 0x42, 0x87, 0xdf, 0x3c,
	0xd8, 0xb6, 0xb6, 0x2d, 0x0d, 0xf9, 0x14, 0x5a, 0xe5, 0x97, 0x1d, 0x71, 0xd7, 0xd9, 0xd1, 0x05,
	0x52, 0x0b, 0x23, 0x6f, 0x61, 0xcb, 0xca, 0x63, 0x75, 0x26, 0xd7, 0x8c, 0xbb, 0x92, 0xdf, 0x4d,
	0xcb, 0xf9, 0x58, 0xb5, 0xc3, 0xef, 0x1e, 0xf4, 0x5c, 0x41, 0xe4, 0x0c, 0xfa, 0xb6, 0x5e, 0x12,
	0x74, 0xf8, 0xe7, 0xbd, 0x2f, 0xe9, 0xb2, 0x9b, 0x9c, 0x97, 0xea, 0x4e, 0xa1, 0xe7, 0xcc, 0x5f,
	0x3d, 0xac, 0xbf, 0x65, 0xc0, 0x86, 0x8d, 0x2e, 0x71, 0x2e, 0x5b, 0x06, 0xfc, 0xfc, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x49, 0xa7, 0xb2, 0x6e, 0x05, 0x00, 0x00,
}
