// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_accountAuthorityObject.proto

package table

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SoAccountAuthorityObject struct {
	Account              *prototype.AccountName  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Owner                *prototype.Authority    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Active               *prototype.Authority    `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	Posting              *prototype.Authority    `protobuf:"bytes,4,opt,name=posting,proto3" json:"posting,omitempty"`
	LastOwnerUpdate      *prototype.TimePointSec `protobuf:"bytes,5,opt,name=last_owner_update,json=lastOwnerUpdate,proto3" json:"last_owner_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoAccountAuthorityObject) Reset()         { *m = SoAccountAuthorityObject{} }
func (m *SoAccountAuthorityObject) String() string { return proto.CompactTextString(m) }
func (*SoAccountAuthorityObject) ProtoMessage()    {}
func (*SoAccountAuthorityObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_45e0b1218bf764ce, []int{0}
}

func (m *SoAccountAuthorityObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoAccountAuthorityObject.Unmarshal(m, b)
}
func (m *SoAccountAuthorityObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoAccountAuthorityObject.Marshal(b, m, deterministic)
}
func (m *SoAccountAuthorityObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoAccountAuthorityObject.Merge(m, src)
}
func (m *SoAccountAuthorityObject) XXX_Size() int {
	return xxx_messageInfo_SoAccountAuthorityObject.Size(m)
}
func (m *SoAccountAuthorityObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SoAccountAuthorityObject.DiscardUnknown(m)
}

var xxx_messageInfo_SoAccountAuthorityObject proto.InternalMessageInfo

func (m *SoAccountAuthorityObject) GetAccount() *prototype.AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SoAccountAuthorityObject) GetOwner() *prototype.Authority {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *SoAccountAuthorityObject) GetActive() *prototype.Authority {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *SoAccountAuthorityObject) GetPosting() *prototype.Authority {
	if m != nil {
		return m.Posting
	}
	return nil
}

func (m *SoAccountAuthorityObject) GetLastOwnerUpdate() *prototype.TimePointSec {
	if m != nil {
		return m.LastOwnerUpdate
	}
	return nil
}

type SoUniqueAccountAuthorityObjectByAccount struct {
	Account              *prototype.AccountName `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoUniqueAccountAuthorityObjectByAccount) Reset() {
	*m = SoUniqueAccountAuthorityObjectByAccount{}
}
func (m *SoUniqueAccountAuthorityObjectByAccount) String() string { return proto.CompactTextString(m) }
func (*SoUniqueAccountAuthorityObjectByAccount) ProtoMessage()    {}
func (*SoUniqueAccountAuthorityObjectByAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_45e0b1218bf764ce, []int{1}
}

func (m *SoUniqueAccountAuthorityObjectByAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueAccountAuthorityObjectByAccount.Unmarshal(m, b)
}
func (m *SoUniqueAccountAuthorityObjectByAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueAccountAuthorityObjectByAccount.Marshal(b, m, deterministic)
}
func (m *SoUniqueAccountAuthorityObjectByAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueAccountAuthorityObjectByAccount.Merge(m, src)
}
func (m *SoUniqueAccountAuthorityObjectByAccount) XXX_Size() int {
	return xxx_messageInfo_SoUniqueAccountAuthorityObjectByAccount.Size(m)
}
func (m *SoUniqueAccountAuthorityObjectByAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueAccountAuthorityObjectByAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueAccountAuthorityObjectByAccount proto.InternalMessageInfo

func (m *SoUniqueAccountAuthorityObjectByAccount) GetAccount() *prototype.AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*SoAccountAuthorityObject)(nil), "table.so_accountAuthorityObject")
	proto.RegisterType((*SoUniqueAccountAuthorityObjectByAccount)(nil), "table.so_unique_accountAuthorityObject_by_account")
}

func init() {
	proto.RegisterFile("app/table/so_accountAuthorityObject.proto", fileDescriptor_45e0b1218bf764ce)
}

var fileDescriptor_45e0b1218bf764ce = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xd9, 0x74, 0x1b, 0xc4, 0x83, 0x18, 0x06, 0x76, 0x9e, 0x64, 0x07, 0x99, 0xff, 0x5a,
	0xd4, 0x4f, 0xa0, 0xe0, 0x79, 0x50, 0xf0, 0xe2, 0x25, 0x26, 0xf1, 0xa5, 0x8d, 0xac, 0x79, 0x63,
	0xf3, 0x46, 0xe9, 0xa7, 0xf1, 0xab, 0x4a, 0xd3, 0x56, 0x76, 0xd9, 0x0e, 0x5e, 0x02, 0xe1, 0xf9,
	0xfd, 0x9e, 0xc0, 0x13, 0x76, 0x29, 0x9d, 0xcb, 0x48, 0xaa, 0x0d, 0x64, 0x1e, 0x85, 0xd4, 0x1a,
	0x83, 0xa5, 0xc7, 0x40, 0x25, 0xd6, 0x86, 0x9a, 0xb5, 0xfa, 0x00, 0x4d, 0xa9, 0xab, 0x91, 0x90,
	0x4f, 0x22, 0x76, 0x36, 0x8f, 0x37, 0x6a, 0x1c, 0x64, 0xed, 0xd1, 0x85, 0xcb, 0x9f, 0x31, 0x5b,
	0xec, 0x2c, 0xe0, 0x77, 0x6c, 0xd6, 0x27, 0xc9, 0xe8, 0x7c, 0xb4, 0x3a, 0xba, 0x3f, 0x4d, 0xff,
	0x5a, 0xd2, 0x3e, 0x11, 0x56, 0x56, 0x90, 0x0f, 0x1c, 0xbf, 0x62, 0x13, 0xfc, 0xb6, 0x50, 0x27,
	0xe3, 0x28, 0xcc, 0xb7, 0x85, 0xa1, 0x3d, 0xef, 0x10, 0x7e, 0xc3, 0xa6, 0x52, 0x93, 0xf9, 0x82,
	0xe4, 0x60, 0x0f, 0xdc, 0x33, 0x3c, 0x65, 0x33, 0x87, 0x9e, 0x8c, 0x2d, 0x92, 0xc3, 0x3d, 0xf8,
	0x00, 0xf1, 0x67, 0x76, 0xb2, 0x91, 0x9e, 0x44, 0x7c, 0x4b, 0x04, 0xf7, 0x2e, 0x09, 0x92, 0x49,
	0x34, 0x17, 0x5b, 0x26, 0x99, 0x0a, 0x84, 0x43, 0x63, 0x49, 0x78, 0xd0, 0xf9, 0x71, 0xeb, 0xac,
	0x5b, 0xe5, 0x25, 0x1a, 0xcb, 0x37, 0x76, 0xed, 0x51, 0x04, 0x6b, 0x3e, 0x03, 0xec, 0xd8, 0x49,
	0xa8, 0x66, 0x48, 0xfe, 0x31, 0xd9, 0xd3, 0xea, 0xf5, 0xa2, 0x30, 0x54, 0x06, 0x95, 0x6a, 0xac,
	0x32, 0x8d, 0x5e, 0x97, 0xd2, 0xd8, 0x4c, 0xa3, 0x25, 0xb0, 0x84, 0xfe, 0xb6, 0xc0, 0xee, 0xab,
	0xd5, 0x34, 0x56, 0x3d, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xcd, 0x9f, 0x96, 0xfe, 0x01,
	0x00, 0x00,
}
