// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_account.proto

package table

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SoAccount struct {
	Name                  *prototype.AccountName   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedTime           *prototype.TimePointSec  `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Creator               *prototype.AccountName   `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Balance               *prototype.Coin          `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Vest                  *prototype.Vest          `protobuf:"bytes,5,opt,name=vest,proto3" json:"vest,omitempty"`
	BpVoteCount           uint32                   `protobuf:"varint,6,opt,name=bp_vote_count,json=bpVoteCount,proto3" json:"bp_vote_count,omitempty"`
	LastVoteTime          *prototype.TimePointSec  `protobuf:"bytes,7,opt,name=last_vote_time,json=lastVoteTime,proto3" json:"last_vote_time,omitempty"`
	LastPostTime          *prototype.TimePointSec  `protobuf:"bytes,8,opt,name=last_post_time,json=lastPostTime,proto3" json:"last_post_time,omitempty"`
	VotePower             uint32                   `protobuf:"varint,9,opt,name=vote_power,json=votePower,proto3" json:"vote_power,omitempty"`
	PostCount             uint32                   `protobuf:"varint,10,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	CreatedTrxCount       uint32                   `protobuf:"varint,11,opt,name=created_trx_count,json=createdTrxCount,proto3" json:"created_trx_count,omitempty"`
	NextPowerdownBlockNum uint64                   `protobuf:"varint,12,opt,name=next_powerdown_block_num,json=nextPowerdownBlockNum,proto3" json:"next_powerdown_block_num,omitempty"`
	EachPowerdownRate     *prototype.Vest          `protobuf:"bytes,13,opt,name=each_powerdown_rate,json=eachPowerdownRate,proto3" json:"each_powerdown_rate,omitempty"`
	ToPowerdown           *prototype.Vest          `protobuf:"bytes,14,opt,name=to_powerdown,json=toPowerdown,proto3" json:"to_powerdown,omitempty"`
	HasPowerdown          *prototype.Vest          `protobuf:"bytes,15,opt,name=has_powerdown,json=hasPowerdown,proto3" json:"has_powerdown,omitempty"`
	PubKey                *prototype.PublicKeyType `protobuf:"bytes,16,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Stamina               uint64                   `protobuf:"varint,17,opt,name=stamina,proto3" json:"stamina,omitempty"`
	StaminaUseBlock       uint64                   `protobuf:"varint,18,opt,name=stamina_use_block,json=staminaUseBlock,proto3" json:"stamina_use_block,omitempty"`
	StaminaFree           uint64                   `protobuf:"varint,19,opt,name=stamina_free,json=staminaFree,proto3" json:"stamina_free,omitempty"`
	StaminaFreeUseBlock   uint64                   `protobuf:"varint,20,opt,name=stamina_free_use_block,json=staminaFreeUseBlock,proto3" json:"stamina_free_use_block,omitempty"`
	StakeVest             *prototype.Vest          `protobuf:"bytes,21,opt,name=stake_vest,json=stakeVest,proto3" json:"stake_vest,omitempty"`
	LastStakeTime         *prototype.TimePointSec  `protobuf:"bytes,22,opt,name=last_stake_time,json=lastStakeTime,proto3" json:"last_stake_time,omitempty"`
	Reputation            uint32                   `protobuf:"varint,23,opt,name=reputation,proto3" json:"reputation,omitempty"`
	ReputationMemo        string                   `protobuf:"bytes,24,opt,name=reputation_memo,json=reputationMemo,proto3" json:"reputation_memo,omitempty"`
	ChargedTicket         uint32                   `protobuf:"varint,25,opt,name=charged_ticket,json=chargedTicket,proto3" json:"charged_ticket,omitempty"`
	Freeze                uint32                   `protobuf:"varint,26,opt,name=freeze,proto3" json:"freeze,omitempty"`
	FreezeMemo            string                   `protobuf:"bytes,27,opt,name=freeze_memo,json=freezeMemo,proto3" json:"freeze_memo,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *SoAccount) Reset()         { *m = SoAccount{} }
func (m *SoAccount) String() string { return proto.CompactTextString(m) }
func (*SoAccount) ProtoMessage()    {}
func (*SoAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{0}
}

func (m *SoAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoAccount.Unmarshal(m, b)
}
func (m *SoAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoAccount.Marshal(b, m, deterministic)
}
func (m *SoAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoAccount.Merge(m, src)
}
func (m *SoAccount) XXX_Size() int {
	return xxx_messageInfo_SoAccount.Size(m)
}
func (m *SoAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SoAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SoAccount proto.InternalMessageInfo

func (m *SoAccount) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *SoAccount) GetCreatedTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *SoAccount) GetCreator() *prototype.AccountName {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *SoAccount) GetBalance() *prototype.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *SoAccount) GetVest() *prototype.Vest {
	if m != nil {
		return m.Vest
	}
	return nil
}

func (m *SoAccount) GetBpVoteCount() uint32 {
	if m != nil {
		return m.BpVoteCount
	}
	return 0
}

func (m *SoAccount) GetLastVoteTime() *prototype.TimePointSec {
	if m != nil {
		return m.LastVoteTime
	}
	return nil
}

func (m *SoAccount) GetLastPostTime() *prototype.TimePointSec {
	if m != nil {
		return m.LastPostTime
	}
	return nil
}

func (m *SoAccount) GetVotePower() uint32 {
	if m != nil {
		return m.VotePower
	}
	return 0
}

func (m *SoAccount) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *SoAccount) GetCreatedTrxCount() uint32 {
	if m != nil {
		return m.CreatedTrxCount
	}
	return 0
}

func (m *SoAccount) GetNextPowerdownBlockNum() uint64 {
	if m != nil {
		return m.NextPowerdownBlockNum
	}
	return 0
}

func (m *SoAccount) GetEachPowerdownRate() *prototype.Vest {
	if m != nil {
		return m.EachPowerdownRate
	}
	return nil
}

func (m *SoAccount) GetToPowerdown() *prototype.Vest {
	if m != nil {
		return m.ToPowerdown
	}
	return nil
}

func (m *SoAccount) GetHasPowerdown() *prototype.Vest {
	if m != nil {
		return m.HasPowerdown
	}
	return nil
}

func (m *SoAccount) GetPubKey() *prototype.PublicKeyType {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *SoAccount) GetStamina() uint64 {
	if m != nil {
		return m.Stamina
	}
	return 0
}

func (m *SoAccount) GetStaminaUseBlock() uint64 {
	if m != nil {
		return m.StaminaUseBlock
	}
	return 0
}

func (m *SoAccount) GetStaminaFree() uint64 {
	if m != nil {
		return m.StaminaFree
	}
	return 0
}

func (m *SoAccount) GetStaminaFreeUseBlock() uint64 {
	if m != nil {
		return m.StaminaFreeUseBlock
	}
	return 0
}

func (m *SoAccount) GetStakeVest() *prototype.Vest {
	if m != nil {
		return m.StakeVest
	}
	return nil
}

func (m *SoAccount) GetLastStakeTime() *prototype.TimePointSec {
	if m != nil {
		return m.LastStakeTime
	}
	return nil
}

func (m *SoAccount) GetReputation() uint32 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

func (m *SoAccount) GetReputationMemo() string {
	if m != nil {
		return m.ReputationMemo
	}
	return ""
}

func (m *SoAccount) GetChargedTicket() uint32 {
	if m != nil {
		return m.ChargedTicket
	}
	return 0
}

func (m *SoAccount) GetFreeze() uint32 {
	if m != nil {
		return m.Freeze
	}
	return 0
}

func (m *SoAccount) GetFreezeMemo() string {
	if m != nil {
		return m.FreezeMemo
	}
	return ""
}

type SoListAccountByCreatedTime struct {
	CreatedTime          *prototype.TimePointSec `protobuf:"bytes,1,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Name                 *prototype.AccountName  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoListAccountByCreatedTime) Reset()         { *m = SoListAccountByCreatedTime{} }
func (m *SoListAccountByCreatedTime) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByCreatedTime) ProtoMessage()    {}
func (*SoListAccountByCreatedTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{1}
}

func (m *SoListAccountByCreatedTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByCreatedTime.Unmarshal(m, b)
}
func (m *SoListAccountByCreatedTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByCreatedTime.Marshal(b, m, deterministic)
}
func (m *SoListAccountByCreatedTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByCreatedTime.Merge(m, src)
}
func (m *SoListAccountByCreatedTime) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByCreatedTime.Size(m)
}
func (m *SoListAccountByCreatedTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByCreatedTime.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByCreatedTime proto.InternalMessageInfo

func (m *SoListAccountByCreatedTime) GetCreatedTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *SoListAccountByCreatedTime) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoListAccountByBalance struct {
	Balance              *prototype.Coin        `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Name                 *prototype.AccountName `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoListAccountByBalance) Reset()         { *m = SoListAccountByBalance{} }
func (m *SoListAccountByBalance) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByBalance) ProtoMessage()    {}
func (*SoListAccountByBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{2}
}

func (m *SoListAccountByBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByBalance.Unmarshal(m, b)
}
func (m *SoListAccountByBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByBalance.Marshal(b, m, deterministic)
}
func (m *SoListAccountByBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByBalance.Merge(m, src)
}
func (m *SoListAccountByBalance) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByBalance.Size(m)
}
func (m *SoListAccountByBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByBalance.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByBalance proto.InternalMessageInfo

func (m *SoListAccountByBalance) GetBalance() *prototype.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *SoListAccountByBalance) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoListAccountByVest struct {
	Vest                 *prototype.Vest        `protobuf:"bytes,1,opt,name=vest,proto3" json:"vest,omitempty"`
	Name                 *prototype.AccountName `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoListAccountByVest) Reset()         { *m = SoListAccountByVest{} }
func (m *SoListAccountByVest) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByVest) ProtoMessage()    {}
func (*SoListAccountByVest) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{3}
}

func (m *SoListAccountByVest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByVest.Unmarshal(m, b)
}
func (m *SoListAccountByVest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByVest.Marshal(b, m, deterministic)
}
func (m *SoListAccountByVest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByVest.Merge(m, src)
}
func (m *SoListAccountByVest) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByVest.Size(m)
}
func (m *SoListAccountByVest) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByVest.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByVest proto.InternalMessageInfo

func (m *SoListAccountByVest) GetVest() *prototype.Vest {
	if m != nil {
		return m.Vest
	}
	return nil
}

func (m *SoListAccountByVest) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoListAccountByBpVoteCount struct {
	BpVoteCount          uint32                 `protobuf:"varint,1,opt,name=bp_vote_count,json=bpVoteCount,proto3" json:"bp_vote_count,omitempty"`
	Name                 *prototype.AccountName `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoListAccountByBpVoteCount) Reset()         { *m = SoListAccountByBpVoteCount{} }
func (m *SoListAccountByBpVoteCount) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByBpVoteCount) ProtoMessage()    {}
func (*SoListAccountByBpVoteCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{4}
}

func (m *SoListAccountByBpVoteCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByBpVoteCount.Unmarshal(m, b)
}
func (m *SoListAccountByBpVoteCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByBpVoteCount.Marshal(b, m, deterministic)
}
func (m *SoListAccountByBpVoteCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByBpVoteCount.Merge(m, src)
}
func (m *SoListAccountByBpVoteCount) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByBpVoteCount.Size(m)
}
func (m *SoListAccountByBpVoteCount) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByBpVoteCount.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByBpVoteCount proto.InternalMessageInfo

func (m *SoListAccountByBpVoteCount) GetBpVoteCount() uint32 {
	if m != nil {
		return m.BpVoteCount
	}
	return 0
}

func (m *SoListAccountByBpVoteCount) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoListAccountByPostCount struct {
	PostCount            uint32                 `protobuf:"varint,1,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	Name                 *prototype.AccountName `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoListAccountByPostCount) Reset()         { *m = SoListAccountByPostCount{} }
func (m *SoListAccountByPostCount) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByPostCount) ProtoMessage()    {}
func (*SoListAccountByPostCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{5}
}

func (m *SoListAccountByPostCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByPostCount.Unmarshal(m, b)
}
func (m *SoListAccountByPostCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByPostCount.Marshal(b, m, deterministic)
}
func (m *SoListAccountByPostCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByPostCount.Merge(m, src)
}
func (m *SoListAccountByPostCount) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByPostCount.Size(m)
}
func (m *SoListAccountByPostCount) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByPostCount.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByPostCount proto.InternalMessageInfo

func (m *SoListAccountByPostCount) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *SoListAccountByPostCount) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoListAccountByCreatedTrxCount struct {
	CreatedTrxCount      uint32                 `protobuf:"varint,1,opt,name=created_trx_count,json=createdTrxCount,proto3" json:"created_trx_count,omitempty"`
	Name                 *prototype.AccountName `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoListAccountByCreatedTrxCount) Reset()         { *m = SoListAccountByCreatedTrxCount{} }
func (m *SoListAccountByCreatedTrxCount) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByCreatedTrxCount) ProtoMessage()    {}
func (*SoListAccountByCreatedTrxCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{6}
}

func (m *SoListAccountByCreatedTrxCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByCreatedTrxCount.Unmarshal(m, b)
}
func (m *SoListAccountByCreatedTrxCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByCreatedTrxCount.Marshal(b, m, deterministic)
}
func (m *SoListAccountByCreatedTrxCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByCreatedTrxCount.Merge(m, src)
}
func (m *SoListAccountByCreatedTrxCount) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByCreatedTrxCount.Size(m)
}
func (m *SoListAccountByCreatedTrxCount) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByCreatedTrxCount.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByCreatedTrxCount proto.InternalMessageInfo

func (m *SoListAccountByCreatedTrxCount) GetCreatedTrxCount() uint32 {
	if m != nil {
		return m.CreatedTrxCount
	}
	return 0
}

func (m *SoListAccountByCreatedTrxCount) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoListAccountByNextPowerdownBlockNum struct {
	NextPowerdownBlockNum uint64                 `protobuf:"varint,1,opt,name=next_powerdown_block_num,json=nextPowerdownBlockNum,proto3" json:"next_powerdown_block_num,omitempty"`
	Name                  *prototype.AccountName `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *SoListAccountByNextPowerdownBlockNum) Reset()         { *m = SoListAccountByNextPowerdownBlockNum{} }
func (m *SoListAccountByNextPowerdownBlockNum) String() string { return proto.CompactTextString(m) }
func (*SoListAccountByNextPowerdownBlockNum) ProtoMessage()    {}
func (*SoListAccountByNextPowerdownBlockNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{7}
}

func (m *SoListAccountByNextPowerdownBlockNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListAccountByNextPowerdownBlockNum.Unmarshal(m, b)
}
func (m *SoListAccountByNextPowerdownBlockNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListAccountByNextPowerdownBlockNum.Marshal(b, m, deterministic)
}
func (m *SoListAccountByNextPowerdownBlockNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListAccountByNextPowerdownBlockNum.Merge(m, src)
}
func (m *SoListAccountByNextPowerdownBlockNum) XXX_Size() int {
	return xxx_messageInfo_SoListAccountByNextPowerdownBlockNum.Size(m)
}
func (m *SoListAccountByNextPowerdownBlockNum) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListAccountByNextPowerdownBlockNum.DiscardUnknown(m)
}

var xxx_messageInfo_SoListAccountByNextPowerdownBlockNum proto.InternalMessageInfo

func (m *SoListAccountByNextPowerdownBlockNum) GetNextPowerdownBlockNum() uint64 {
	if m != nil {
		return m.NextPowerdownBlockNum
	}
	return 0
}

func (m *SoListAccountByNextPowerdownBlockNum) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoUniqueAccountByName struct {
	Name                 *prototype.AccountName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoUniqueAccountByName) Reset()         { *m = SoUniqueAccountByName{} }
func (m *SoUniqueAccountByName) String() string { return proto.CompactTextString(m) }
func (*SoUniqueAccountByName) ProtoMessage()    {}
func (*SoUniqueAccountByName) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{8}
}

func (m *SoUniqueAccountByName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueAccountByName.Unmarshal(m, b)
}
func (m *SoUniqueAccountByName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueAccountByName.Marshal(b, m, deterministic)
}
func (m *SoUniqueAccountByName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueAccountByName.Merge(m, src)
}
func (m *SoUniqueAccountByName) XXX_Size() int {
	return xxx_messageInfo_SoUniqueAccountByName.Size(m)
}
func (m *SoUniqueAccountByName) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueAccountByName.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueAccountByName proto.InternalMessageInfo

func (m *SoUniqueAccountByName) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

type SoUniqueAccountByPubKey struct {
	PubKey               *prototype.PublicKeyType `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Name                 *prototype.AccountName   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SoUniqueAccountByPubKey) Reset()         { *m = SoUniqueAccountByPubKey{} }
func (m *SoUniqueAccountByPubKey) String() string { return proto.CompactTextString(m) }
func (*SoUniqueAccountByPubKey) ProtoMessage()    {}
func (*SoUniqueAccountByPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_246c6b96a0e2a331, []int{9}
}

func (m *SoUniqueAccountByPubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueAccountByPubKey.Unmarshal(m, b)
}
func (m *SoUniqueAccountByPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueAccountByPubKey.Marshal(b, m, deterministic)
}
func (m *SoUniqueAccountByPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueAccountByPubKey.Merge(m, src)
}
func (m *SoUniqueAccountByPubKey) XXX_Size() int {
	return xxx_messageInfo_SoUniqueAccountByPubKey.Size(m)
}
func (m *SoUniqueAccountByPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueAccountByPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueAccountByPubKey proto.InternalMessageInfo

func (m *SoUniqueAccountByPubKey) GetPubKey() *prototype.PublicKeyType {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *SoUniqueAccountByPubKey) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*SoAccount)(nil), "table.so_account")
	proto.RegisterType((*SoListAccountByCreatedTime)(nil), "table.so_list_account_by_created_time")
	proto.RegisterType((*SoListAccountByBalance)(nil), "table.so_list_account_by_balance")
	proto.RegisterType((*SoListAccountByVest)(nil), "table.so_list_account_by_vest")
	proto.RegisterType((*SoListAccountByBpVoteCount)(nil), "table.so_list_account_by_bp_vote_count")
	proto.RegisterType((*SoListAccountByPostCount)(nil), "table.so_list_account_by_post_count")
	proto.RegisterType((*SoListAccountByCreatedTrxCount)(nil), "table.so_list_account_by_created_trx_count")
	proto.RegisterType((*SoListAccountByNextPowerdownBlockNum)(nil), "table.so_list_account_by_next_powerdown_block_num")
	proto.RegisterType((*SoUniqueAccountByName)(nil), "table.so_unique_account_by_name")
	proto.RegisterType((*SoUniqueAccountByPubKey)(nil), "table.so_unique_account_by_pub_key")
}

func init() { proto.RegisterFile("app/table/so_account.proto", fileDescriptor_246c6b96a0e2a331) }

var fileDescriptor_246c6b96a0e2a331 = []byte{
	// 817 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xdf, 0x8f, 0xdb, 0x44,
	0x10, 0xc7, 0xb5, 0xe5, 0x9a, 0x90, 0xc9, 0x2f, 0x6e, 0xaf, 0xbd, 0xdb, 0x0b, 0x94, 0x86, 0x00,
	0x22, 0xb4, 0x90, 0x88, 0x1e, 0x12, 0x2f, 0x48, 0x15, 0x45, 0x42, 0x48, 0x08, 0x74, 0x32, 0xa5,
	0x0f, 0xbc, 0xac, 0xd6, 0xee, 0x70, 0xb1, 0x12, 0x7b, 0x8d, 0x77, 0xdd, 0x5e, 0x78, 0x81, 0x3f,
	0x80, 0x37, 0xfe, 0x3e, 0xfe, 0x17, 0xb4, 0x63, 0x3b, 0x31, 0x17, 0x37, 0x17, 0xbf, 0x9c, 0xb2,
	0x33, 0xdf, 0xef, 0xcc, 0xee, 0x64, 0xee, 0xa3, 0xc0, 0x48, 0x25, 0xc9, 0xdc, 0x2a, 0x7f, 0x85,
	0x73, 0xa3, 0xa5, 0x0a, 0x02, 0x9d, 0xc5, 0x76, 0x96, 0xa4, 0xda, 0x6a, 0x7e, 0x97, 0xe2, 0xa3,
	0x7b, 0x74, 0xb2, 0xeb, 0x04, 0xe7, 0xee, 0x4f, 0x9e, 0x9c, 0xfc, 0xdb, 0x01, 0xd8, 0x3a, 0xf8,
	0x63, 0x38, 0x8a, 0x55, 0x84, 0x82, 0x8d, 0xd9, 0xb4, 0xfb, 0xe4, 0x6c, 0xb6, 0xf1, 0xcc, 0x0a,
	0x85, 0x74, 0x69, 0x8f, 0x44, 0xfc, 0x6b, 0xe8, 0x05, 0x29, 0x2a, 0x8b, 0x2f, 0xa5, 0x0d, 0x23,
	0x14, 0x77, 0xc8, 0x74, 0x5e, 0x31, 0xb9, 0xb0, 0x4c, 0x74, 0x18, 0x5b, 0x69, 0x30, 0xf0, 0xba,
	0x85, 0xfc, 0x79, 0x18, 0x21, 0xff, 0x02, 0xda, 0x74, 0xd4, 0xa9, 0x78, 0x6b, 0x7f, 0xb7, 0x52,
	0xc7, 0x3f, 0x85, 0xb6, 0xaf, 0x56, 0x2a, 0x0e, 0x50, 0x1c, 0x91, 0x65, 0x58, 0xb1, 0x04, 0x3a,
	0x8c, 0xbd, 0x32, 0xcf, 0x3f, 0x84, 0xa3, 0x57, 0x68, 0xac, 0xb8, 0xbb, 0xa3, 0x73, 0x61, 0x8f,
	0x92, 0x7c, 0x02, 0x7d, 0x3f, 0x91, 0xaf, 0xb4, 0x45, 0x49, 0xed, 0x44, 0x6b, 0xcc, 0xa6, 0x7d,
	0xaf, 0xeb, 0x27, 0x2f, 0xb4, 0xc5, 0x6f, 0x69, 0x22, 0x4f, 0x61, 0xb0, 0x52, 0xc6, 0xe6, 0x2a,
	0x7a, 0x66, 0xfb, 0xb6, 0x67, 0xf6, 0x9c, 0xc1, 0x55, 0xa0, 0x77, 0x96, 0x05, 0x12, 0x6d, 0x6c,
	0x5e, 0xe0, 0xed, 0x83, 0x0a, 0x5c, 0x6a, 0x63, 0xa9, 0xc0, 0x03, 0x00, 0x6a, 0x9e, 0xe8, 0xd7,
	0x98, 0x8a, 0x0e, 0x5d, 0xb1, 0xe3, 0x22, 0x97, 0x2e, 0xe0, 0xd2, 0x54, 0x3a, 0x7f, 0x01, 0xe4,
	0x69, 0x17, 0xc9, 0xef, 0xff, 0x08, 0x8e, 0x37, 0x5f, 0x52, 0x7a, 0x5d, 0xa8, 0xba, 0xa4, 0x1a,
	0x96, 0x5f, 0x47, 0x7a, 0x9d, 0x6b, 0xbf, 0x02, 0x11, 0xe3, 0xb5, 0xcd, 0x3b, 0xbd, 0xd4, 0xaf,
	0x63, 0xe9, 0xaf, 0x74, 0xb0, 0x94, 0x71, 0x16, 0x89, 0xde, 0x98, 0x4d, 0x8f, 0xbc, 0xfb, 0x2e,
	0x7f, 0x59, 0xa6, 0x9f, 0xb9, 0xec, 0x4f, 0x59, 0xc4, 0x9f, 0xc2, 0x09, 0xaa, 0x60, 0x51, 0x31,
	0xa6, 0xca, 0xa2, 0xe8, 0xd7, 0x0f, 0xff, 0xd8, 0x69, 0x37, 0x45, 0x3c, 0x65, 0x91, 0x3f, 0x81,
	0x9e, 0xd5, 0x5b, 0xbb, 0x18, 0xd4, 0x3b, 0xbb, 0x56, 0x6f, 0x7c, 0xfc, 0x4b, 0xe8, 0x2f, 0x94,
	0xa9, 0x98, 0x86, 0xf5, 0xa6, 0xde, 0x42, 0x99, 0xad, 0xeb, 0x02, 0xda, 0x49, 0xe6, 0xcb, 0x25,
	0xae, 0xc5, 0x3b, 0xa4, 0x1f, 0x55, 0xf4, 0x49, 0xe6, 0xaf, 0xc2, 0xc0, 0x25, 0xa5, 0x3b, 0x7b,
	0xad, 0x24, 0xf3, 0x7f, 0xc0, 0x35, 0x17, 0xd0, 0x36, 0x56, 0x45, 0x61, 0xac, 0xc4, 0x31, 0xcd,
	0xa1, 0x3c, 0xba, 0xf1, 0x16, 0x1f, 0x65, 0x66, 0x30, 0x9f, 0x97, 0xe0, 0xa4, 0x19, 0x16, 0x89,
	0x5f, 0x0c, 0xd2, 0xa0, 0xf8, 0x07, 0xd0, 0x2b, 0xb5, 0xbf, 0xa5, 0x88, 0xe2, 0x84, 0x64, 0xdd,
	0x22, 0xf6, 0x5d, 0x8a, 0xc8, 0x2f, 0xe0, 0xb4, 0x2a, 0xa9, 0xd4, 0xbc, 0x47, 0xe2, 0x93, 0x8a,
	0x78, 0x53, 0x77, 0x06, 0x60, 0xac, 0x5a, 0xa2, 0xa4, 0x8d, 0xbf, 0x5f, 0x3f, 0x85, 0x0e, 0x49,
	0x5e, 0xb8, 0xb5, 0xff, 0x06, 0x86, 0xb4, 0x91, 0xb9, 0x89, 0x56, 0xf2, 0xf4, 0xb6, 0x95, 0xec,
	0x3b, 0xc7, 0xcf, 0xce, 0x40, 0x3b, 0xf9, 0x3e, 0x40, 0x8a, 0x49, 0x66, 0x95, 0x0d, 0x75, 0x2c,
	0xce, 0x68, 0x9d, 0x2a, 0x11, 0xfe, 0x09, 0x0c, 0xb7, 0x27, 0x19, 0x61, 0xa4, 0x85, 0x18, 0xb3,
	0x69, 0xc7, 0x1b, 0x6c, 0xc3, 0x3f, 0x62, 0xa4, 0xf9, 0xc7, 0x30, 0x08, 0x16, 0x2a, 0xbd, 0x22,
	0x86, 0x04, 0x4b, 0xb4, 0xe2, 0x9c, 0x8a, 0xf5, 0x8b, 0xe8, 0x73, 0x0a, 0xf2, 0x53, 0x68, 0xb9,
	0x79, 0xfc, 0x81, 0x62, 0x44, 0xe9, 0xe2, 0xc4, 0x1f, 0x42, 0x37, 0xff, 0x94, 0xf7, 0x78, 0x97,
	0x7a, 0x40, 0x1e, 0x72, 0xf5, 0x27, 0x7f, 0x33, 0x78, 0x68, 0xb4, 0x5c, 0x85, 0xc6, 0x96, 0x90,
	0x93, 0xfe, 0x5a, 0x56, 0xb9, 0xb5, 0xc3, 0x31, 0xd6, 0x88, 0x63, 0x25, 0x32, 0xef, 0x1c, 0x80,
	0xcc, 0x89, 0x85, 0x51, 0xcd, 0x6d, 0x4a, 0x68, 0x55, 0xf8, 0xc6, 0x6e, 0xe1, 0x5b, 0xa3, 0xae,
	0x4b, 0x38, 0xab, 0xe9, 0x4a, 0x08, 0x2c, 0x39, 0xc9, 0xf6, 0x71, 0xb2, 0x51, 0x33, 0x03, 0xe3,
	0xba, 0x27, 0x56, 0x39, 0xbb, 0x0b, 0x5e, 0xb6, 0x0b, 0xde, 0x86, 0x2f, 0x7c, 0x50, 0xd3, 0x74,
	0xcb, 0xc5, 0x1b, 0x94, 0x64, 0x37, 0x29, 0xd9, 0xa8, 0xd9, 0x9f, 0xf0, 0xd1, 0xbe, 0x95, 0x2a,
	0x29, 0x5b, 0x8f, 0x5e, 0x56, 0x8f, 0xde, 0x46, 0x17, 0xf8, 0x87, 0xc1, 0xe3, 0x9a, 0x1b, 0xbc,
	0x89, 0xdd, 0x7b, 0xb9, 0xce, 0xf6, 0x71, 0xbd, 0xd1, 0xad, 0xbe, 0x87, 0x73, 0xa3, 0x65, 0x16,
	0x87, 0xbf, 0x67, 0xf8, 0xbf, 0x6b, 0xa9, 0xca, 0x7f, 0xc9, 0x21, 0x3f, 0x2c, 0x26, 0x7f, 0x31,
	0x78, 0xaf, 0xb6, 0x54, 0x41, 0xee, 0x2a, 0xc4, 0xd9, 0xc1, 0x10, 0x6f, 0xf2, 0x98, 0x67, 0x9f,
	0xfd, 0xfa, 0xe8, 0x2a, 0xb4, 0x8b, 0xcc, 0x9f, 0x05, 0x3a, 0x9a, 0x07, 0xda, 0x04, 0x0b, 0x15,
	0xc6, 0xf3, 0x40, 0xc7, 0x16, 0x63, 0xab, 0xcd, 0xe7, 0x57, 0x7a, 0xbe, 0xf9, 0xcd, 0xe5, 0xb7,
	0xa8, 0xd6, 0xc5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x2d, 0x15, 0xff, 0x87, 0x09, 0x00,
	0x00,
}
