// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_blockProducerScheduleObject.proto

package table

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SoBlockProducerScheduleObject struct {
	Id                           int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentShuffledBlockProducer []string                   `protobuf:"bytes,2,rep,name=current_shuffled_block_producer,json=currentShuffledBlockProducer,proto3" json:"current_shuffled_block_producer,omitempty"`
	PubKey                       []*prototype.PublicKeyType `protobuf:"bytes,3,rep,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                   `json:"-"`
	XXX_unrecognized             []byte                     `json:"-"`
	XXX_sizecache                int32                      `json:"-"`
}

func (m *SoBlockProducerScheduleObject) Reset()         { *m = SoBlockProducerScheduleObject{} }
func (m *SoBlockProducerScheduleObject) String() string { return proto.CompactTextString(m) }
func (*SoBlockProducerScheduleObject) ProtoMessage()    {}
func (*SoBlockProducerScheduleObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6d3d6ba5e5a19e, []int{0}
}

func (m *SoBlockProducerScheduleObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoBlockProducerScheduleObject.Unmarshal(m, b)
}
func (m *SoBlockProducerScheduleObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoBlockProducerScheduleObject.Marshal(b, m, deterministic)
}
func (m *SoBlockProducerScheduleObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoBlockProducerScheduleObject.Merge(m, src)
}
func (m *SoBlockProducerScheduleObject) XXX_Size() int {
	return xxx_messageInfo_SoBlockProducerScheduleObject.Size(m)
}
func (m *SoBlockProducerScheduleObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SoBlockProducerScheduleObject.DiscardUnknown(m)
}

var xxx_messageInfo_SoBlockProducerScheduleObject proto.InternalMessageInfo

func (m *SoBlockProducerScheduleObject) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SoBlockProducerScheduleObject) GetCurrentShuffledBlockProducer() []string {
	if m != nil {
		return m.CurrentShuffledBlockProducer
	}
	return nil
}

func (m *SoBlockProducerScheduleObject) GetPubKey() []*prototype.PublicKeyType {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type SoMemBlockProducerScheduleObjectById struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoMemBlockProducerScheduleObjectById) Reset()         { *m = SoMemBlockProducerScheduleObjectById{} }
func (m *SoMemBlockProducerScheduleObjectById) String() string { return proto.CompactTextString(m) }
func (*SoMemBlockProducerScheduleObjectById) ProtoMessage()    {}
func (*SoMemBlockProducerScheduleObjectById) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6d3d6ba5e5a19e, []int{1}
}

func (m *SoMemBlockProducerScheduleObjectById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectById.Unmarshal(m, b)
}
func (m *SoMemBlockProducerScheduleObjectById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectById.Marshal(b, m, deterministic)
}
func (m *SoMemBlockProducerScheduleObjectById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoMemBlockProducerScheduleObjectById.Merge(m, src)
}
func (m *SoMemBlockProducerScheduleObjectById) XXX_Size() int {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectById.Size(m)
}
func (m *SoMemBlockProducerScheduleObjectById) XXX_DiscardUnknown() {
	xxx_messageInfo_SoMemBlockProducerScheduleObjectById.DiscardUnknown(m)
}

var xxx_messageInfo_SoMemBlockProducerScheduleObjectById proto.InternalMessageInfo

func (m *SoMemBlockProducerScheduleObjectById) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer struct {
	CurrentShuffledBlockProducer []string `protobuf:"bytes,1,rep,name=current_shuffled_block_producer,json=currentShuffledBlockProducer,proto3" json:"current_shuffled_block_producer,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) Reset() {
	*m = SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer{}
}
func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) String() string {
	return proto.CompactTextString(m)
}
func (*SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) ProtoMessage() {}
func (*SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6d3d6ba5e5a19e, []int{2}
}

func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer.Unmarshal(m, b)
}
func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer.Marshal(b, m, deterministic)
}
func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer.Merge(m, src)
}
func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) XXX_Size() int {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer.Size(m)
}
func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer.DiscardUnknown(m)
}

var xxx_messageInfo_SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer proto.InternalMessageInfo

func (m *SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer) GetCurrentShuffledBlockProducer() []string {
	if m != nil {
		return m.CurrentShuffledBlockProducer
	}
	return nil
}

type SoMemBlockProducerScheduleObjectByPubKey struct {
	PubKey               []*prototype.PublicKeyType `protobuf:"bytes,1,rep,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SoMemBlockProducerScheduleObjectByPubKey) Reset() {
	*m = SoMemBlockProducerScheduleObjectByPubKey{}
}
func (m *SoMemBlockProducerScheduleObjectByPubKey) String() string { return proto.CompactTextString(m) }
func (*SoMemBlockProducerScheduleObjectByPubKey) ProtoMessage()    {}
func (*SoMemBlockProducerScheduleObjectByPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6d3d6ba5e5a19e, []int{3}
}

func (m *SoMemBlockProducerScheduleObjectByPubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectByPubKey.Unmarshal(m, b)
}
func (m *SoMemBlockProducerScheduleObjectByPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectByPubKey.Marshal(b, m, deterministic)
}
func (m *SoMemBlockProducerScheduleObjectByPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoMemBlockProducerScheduleObjectByPubKey.Merge(m, src)
}
func (m *SoMemBlockProducerScheduleObjectByPubKey) XXX_Size() int {
	return xxx_messageInfo_SoMemBlockProducerScheduleObjectByPubKey.Size(m)
}
func (m *SoMemBlockProducerScheduleObjectByPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SoMemBlockProducerScheduleObjectByPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_SoMemBlockProducerScheduleObjectByPubKey proto.InternalMessageInfo

func (m *SoMemBlockProducerScheduleObjectByPubKey) GetPubKey() []*prototype.PublicKeyType {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type SoUniqueBlockProducerScheduleObjectById struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoUniqueBlockProducerScheduleObjectById) Reset() {
	*m = SoUniqueBlockProducerScheduleObjectById{}
}
func (m *SoUniqueBlockProducerScheduleObjectById) String() string { return proto.CompactTextString(m) }
func (*SoUniqueBlockProducerScheduleObjectById) ProtoMessage()    {}
func (*SoUniqueBlockProducerScheduleObjectById) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6d3d6ba5e5a19e, []int{4}
}

func (m *SoUniqueBlockProducerScheduleObjectById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueBlockProducerScheduleObjectById.Unmarshal(m, b)
}
func (m *SoUniqueBlockProducerScheduleObjectById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueBlockProducerScheduleObjectById.Marshal(b, m, deterministic)
}
func (m *SoUniqueBlockProducerScheduleObjectById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueBlockProducerScheduleObjectById.Merge(m, src)
}
func (m *SoUniqueBlockProducerScheduleObjectById) XXX_Size() int {
	return xxx_messageInfo_SoUniqueBlockProducerScheduleObjectById.Size(m)
}
func (m *SoUniqueBlockProducerScheduleObjectById) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueBlockProducerScheduleObjectById.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueBlockProducerScheduleObjectById proto.InternalMessageInfo

func (m *SoUniqueBlockProducerScheduleObjectById) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*SoBlockProducerScheduleObject)(nil), "table.so_blockProducerScheduleObject")
	proto.RegisterType((*SoMemBlockProducerScheduleObjectById)(nil), "table.so_mem_blockProducerScheduleObject_by_id")
	proto.RegisterType((*SoMemBlockProducerScheduleObjectByCurrentShuffledBlockProducer)(nil), "table.so_mem_blockProducerScheduleObject_by_current_shuffled_block_producer")
	proto.RegisterType((*SoMemBlockProducerScheduleObjectByPubKey)(nil), "table.so_mem_blockProducerScheduleObject_by_pub_key")
	proto.RegisterType((*SoUniqueBlockProducerScheduleObjectById)(nil), "table.so_unique_blockProducerScheduleObject_by_id")
}

func init() {
	proto.RegisterFile("app/table/so_blockProducerScheduleObject.proto", fileDescriptor_eb6d3d6ba5e5a19e)
}

var fileDescriptor_eb6d3d6ba5e5a19e = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xb1, 0x6a, 0xf3, 0x30,
	0x10, 0xc7, 0x51, 0x42, 0xf2, 0xf1, 0xa9, 0xd0, 0xc1, 0x74, 0x08, 0xa1, 0xb4, 0xc1, 0x93, 0x69,
	0x1b, 0x0b, 0x9a, 0xad, 0xd0, 0x25, 0x90, 0xa9, 0x43, 0x8b, 0xb3, 0x75, 0x11, 0x96, 0x74, 0x89,
	0xd5, 0xd8, 0x3e, 0xd5, 0x92, 0x06, 0xbf, 0x44, 0x9f, 0xa4, 0x0f, 0x59, 0xec, 0x98, 0x10, 0x3a,
	0x24, 0xee, 0x22, 0x38, 0xee, 0x7f, 0xa7, 0x9f, 0x7e, 0x88, 0xc6, 0xa9, 0x31, 0xcc, 0xa5, 0x22,
	0x07, 0x66, 0x91, 0x8b, 0x1c, 0xe5, 0xee, 0xad, 0x42, 0xe5, 0x25, 0x54, 0x6b, 0x99, 0x81, 0xf2,
	0x39, 0xbc, 0x8a, 0x0f, 0x90, 0x2e, 0x36, 0x15, 0x3a, 0x0c, 0x46, 0x6d, 0x76, 0x7a, 0xd5, 0x56,
	0xae, 0x36, 0xc0, 0x9a, 0x63, 0xdf, 0x0c, 0xbf, 0x09, 0xbd, 0x39, 0xbd, 0x25, 0xb8, 0xa4, 0x03,
	0xad, 0x26, 0x64, 0x46, 0xa2, 0x51, 0x32, 0xd0, 0x2a, 0x58, 0xd1, 0x5b, 0xe9, 0xab, 0x0a, 0x4a,
	0xc7, 0x6d, 0xe6, 0x37, 0x9b, 0x1c, 0xd4, 0x7e, 0x9e, 0x9b, 0x6e, 0xc1, 0x64, 0x30, 0x1b, 0x46,
	0xff, 0x93, 0xeb, 0x2e, 0xb6, 0xee, 0x52, 0xcb, 0xe3, 0x4b, 0x82, 0x05, 0xfd, 0x67, 0xbc, 0xe0,
	0x3b, 0xa8, 0x27, 0xc3, 0xd9, 0x30, 0xba, 0x78, 0x9c, 0xc6, 0x07, 0xc2, 0xd8, 0x78, 0x91, 0x6b,
	0xd9, 0x34, 0x79, 0x53, 0x27, 0x63, 0xe3, 0xc5, 0x0b, 0xd4, 0xe1, 0x13, 0x8d, 0x2c, 0xf2, 0x02,
	0x8a, 0x53, 0xc4, 0x5c, 0xd4, 0x5c, 0xab, 0xdf, 0xdc, 0xe1, 0x17, 0xa1, 0xab, 0x7e, 0xc3, 0x67,
	0x9e, 0xd7, 0xc7, 0x00, 0x39, 0x6f, 0x20, 0x54, 0x74, 0xde, 0x8f, 0xa7, 0xf3, 0x74, 0xac, 0x8c,
	0xf4, 0x56, 0xf6, 0x4c, 0xef, 0x2d, 0x72, 0x5f, 0xea, 0x4f, 0x0f, 0x7f, 0xb7, 0xb6, 0x7c, 0x78,
	0xbf, 0xdb, 0x6a, 0x97, 0x79, 0x11, 0x4b, 0x2c, 0x98, 0x44, 0x2b, 0xb3, 0x54, 0x97, 0x4c, 0x62,
	0xe9, 0xa0, 0x74, 0x68, 0xe7, 0x5b, 0x64, 0x87, 0x0f, 0x29, 0xc6, 0x2d, 0xcf, 0xe2, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xad, 0x10, 0xc0, 0xa3, 0xa4, 0x02, 0x00, 0x00,
}
