// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_contract.proto

package table

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SoContract struct {
	Id                   *prototype.ContractId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedTime          *prototype.TimePointSec `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Abi                  string                  `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`
	Balance              *prototype.Coin         `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Code                 []byte                  `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoContract) Reset()         { *m = SoContract{} }
func (m *SoContract) String() string { return proto.CompactTextString(m) }
func (*SoContract) ProtoMessage()    {}
func (*SoContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccfb8b33a116ac5, []int{0}
}

func (m *SoContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoContract.Unmarshal(m, b)
}
func (m *SoContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoContract.Marshal(b, m, deterministic)
}
func (m *SoContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoContract.Merge(m, src)
}
func (m *SoContract) XXX_Size() int {
	return xxx_messageInfo_SoContract.Size(m)
}
func (m *SoContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SoContract.DiscardUnknown(m)
}

var xxx_messageInfo_SoContract proto.InternalMessageInfo

func (m *SoContract) GetId() *prototype.ContractId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SoContract) GetCreatedTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *SoContract) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *SoContract) GetBalance() *prototype.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *SoContract) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

type SoListContractByCreatedTime struct {
	CreatedTime          *prototype.TimePointSec `protobuf:"bytes,1,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Id                   *prototype.ContractId   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoListContractByCreatedTime) Reset()         { *m = SoListContractByCreatedTime{} }
func (m *SoListContractByCreatedTime) String() string { return proto.CompactTextString(m) }
func (*SoListContractByCreatedTime) ProtoMessage()    {}
func (*SoListContractByCreatedTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccfb8b33a116ac5, []int{1}
}

func (m *SoListContractByCreatedTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListContractByCreatedTime.Unmarshal(m, b)
}
func (m *SoListContractByCreatedTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListContractByCreatedTime.Marshal(b, m, deterministic)
}
func (m *SoListContractByCreatedTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListContractByCreatedTime.Merge(m, src)
}
func (m *SoListContractByCreatedTime) XXX_Size() int {
	return xxx_messageInfo_SoListContractByCreatedTime.Size(m)
}
func (m *SoListContractByCreatedTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListContractByCreatedTime.DiscardUnknown(m)
}

var xxx_messageInfo_SoListContractByCreatedTime proto.InternalMessageInfo

func (m *SoListContractByCreatedTime) GetCreatedTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *SoListContractByCreatedTime) GetId() *prototype.ContractId {
	if m != nil {
		return m.Id
	}
	return nil
}

type SoUniqueContractById struct {
	Id                   *prototype.ContractId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SoUniqueContractById) Reset()         { *m = SoUniqueContractById{} }
func (m *SoUniqueContractById) String() string { return proto.CompactTextString(m) }
func (*SoUniqueContractById) ProtoMessage()    {}
func (*SoUniqueContractById) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccfb8b33a116ac5, []int{2}
}

func (m *SoUniqueContractById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueContractById.Unmarshal(m, b)
}
func (m *SoUniqueContractById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueContractById.Marshal(b, m, deterministic)
}
func (m *SoUniqueContractById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueContractById.Merge(m, src)
}
func (m *SoUniqueContractById) XXX_Size() int {
	return xxx_messageInfo_SoUniqueContractById.Size(m)
}
func (m *SoUniqueContractById) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueContractById.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueContractById proto.InternalMessageInfo

func (m *SoUniqueContractById) GetId() *prototype.ContractId {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*SoContract)(nil), "table.so_contract")
	proto.RegisterType((*SoListContractByCreatedTime)(nil), "table.so_list_contract_by_created_time")
	proto.RegisterType((*SoUniqueContractById)(nil), "table.so_unique_contract_by_id")
}

func init() { proto.RegisterFile("app/table/so_contract.proto", fileDescriptor_6ccfb8b33a116ac5) }

var fileDescriptor_6ccfb8b33a116ac5 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x95, 0xd3, 0x16, 0x84, 0x5b, 0x09, 0x64, 0x21, 0x64, 0x60, 0x89, 0x32, 0x54, 0x61, 0x20,
	0x91, 0x60, 0x65, 0xea, 0x27, 0x44, 0x4c, 0x2c, 0x96, 0x5f, 0x6a, 0xaf, 0x94, 0xf8, 0x86, 0xd8,
	0x19, 0xfa, 0x07, 0x7c, 0x18, 0x1f, 0x86, 0xe2, 0xd0, 0x2a, 0x15, 0x03, 0xb0, 0x58, 0xd7, 0x3e,
	0x0f, 0x1f, 0x1f, 0xd3, 0x7b, 0xd9, 0xb6, 0x65, 0x90, 0xaa, 0xb6, 0xa5, 0x47, 0xa1, 0xd1, 0x85,
	0x4e, 0xea, 0x50, 0xb4, 0x1d, 0x06, 0x64, 0x8b, 0x08, 0xdc, 0x5d, 0xc7, 0x5d, 0xd8, 0xb7, 0xb6,
	0x1c, 0x96, 0x11, 0xcc, 0x3e, 0x09, 0x5d, 0x4e, 0x24, 0x6c, 0x4d, 0x13, 0x30, 0x9c, 0xa4, 0x24,
	0x5f, 0x3e, 0xdd, 0x14, 0x47, 0x49, 0x71, 0x20, 0x08, 0x30, 0x55, 0x02, 0x86, 0xbd, 0xd0, 0x95,
	0xee, 0xac, 0x0c, 0xd6, 0x88, 0x00, 0x8d, 0xe5, 0x49, 0x54, 0xdc, 0x4e, 0x14, 0xc3, 0xb1, 0x68,
	0x11, 0x5c, 0x10, 0xde, 0xea, 0x6a, 0xf9, 0x4d, 0x7f, 0x85, 0xc6, 0xb2, 0x2b, 0x3a, 0x93, 0x0a,
	0xf8, 0x2c, 0x25, 0xf9, 0x45, 0x35, 0x8c, 0xec, 0x81, 0x9e, 0x2b, 0x59, 0x4b, 0xa7, 0x2d, 0x9f,
	0x47, 0xab, 0xcb, 0x93, 0xcb, 0xc1, 0x55, 0x07, 0x9c, 0x31, 0x3a, 0xd7, 0x68, 0x2c, 0x5f, 0xa4,
	0x24, 0x5f, 0x55, 0x71, 0xce, 0x3e, 0x08, 0x4d, 0x3d, 0x8a, 0x1a, 0x7c, 0x38, 0xbe, 0x45, 0xa8,
	0xbd, 0x98, 0x66, 0xfc, 0x91, 0x99, 0xfc, 0x2b, 0xf3, 0xd8, 0x4c, 0xf2, 0x5b, 0x33, 0xd9, 0x86,
	0x72, 0x8f, 0xa2, 0x77, 0xf0, 0xde, 0xdb, 0x93, 0x2c, 0x60, 0xfe, 0xda, 0xee, 0x26, 0x7f, 0x5b,
	0x6f, 0x21, 0xec, 0x7a, 0x55, 0x68, 0x6c, 0x4a, 0x8d, 0x5e, 0xef, 0x24, 0xb8, 0x72, 0xa0, 0x59,
	0x17, 0xd0, 0x3f, 0x6e, 0x71, 0xfc, 0x6e, 0x75, 0x16, 0x4d, 0x9e, 0xbf, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x44, 0xb9, 0x64, 0x02, 0x02, 0x00, 0x00,
}
