// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_extTrx.proto

package table

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SoExtTrx struct {
	TrxId                *prototype.Sha256             `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	BlockHeight          uint64                        `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	TrxWrap              *prototype.TransactionWrapper `protobuf:"bytes,3,opt,name=trx_wrap,json=trxWrap,proto3" json:"trx_wrap,omitempty"`
	BlockTime            *prototype.TimePointSec       `protobuf:"bytes,4,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	TrxCreateOrder       *prototype.UserTrxCreateOrder `protobuf:"bytes,5,opt,name=trx_create_order,json=trxCreateOrder,proto3" json:"trx_create_order,omitempty"`
	BlockId              *prototype.Sha256             `protobuf:"bytes,6,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SoExtTrx) Reset()         { *m = SoExtTrx{} }
func (m *SoExtTrx) String() string { return proto.CompactTextString(m) }
func (*SoExtTrx) ProtoMessage()    {}
func (*SoExtTrx) Descriptor() ([]byte, []int) {
	return fileDescriptor_76957eaae1f8a1bc, []int{0}
}

func (m *SoExtTrx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoExtTrx.Unmarshal(m, b)
}
func (m *SoExtTrx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoExtTrx.Marshal(b, m, deterministic)
}
func (m *SoExtTrx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoExtTrx.Merge(m, src)
}
func (m *SoExtTrx) XXX_Size() int {
	return xxx_messageInfo_SoExtTrx.Size(m)
}
func (m *SoExtTrx) XXX_DiscardUnknown() {
	xxx_messageInfo_SoExtTrx.DiscardUnknown(m)
}

var xxx_messageInfo_SoExtTrx proto.InternalMessageInfo

func (m *SoExtTrx) GetTrxId() *prototype.Sha256 {
	if m != nil {
		return m.TrxId
	}
	return nil
}

func (m *SoExtTrx) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *SoExtTrx) GetTrxWrap() *prototype.TransactionWrapper {
	if m != nil {
		return m.TrxWrap
	}
	return nil
}

func (m *SoExtTrx) GetBlockTime() *prototype.TimePointSec {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

func (m *SoExtTrx) GetTrxCreateOrder() *prototype.UserTrxCreateOrder {
	if m != nil {
		return m.TrxCreateOrder
	}
	return nil
}

func (m *SoExtTrx) GetBlockId() *prototype.Sha256 {
	if m != nil {
		return m.BlockId
	}
	return nil
}

type SoListExtTrxByTrxId struct {
	TrxId                *prototype.Sha256 `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SoListExtTrxByTrxId) Reset()         { *m = SoListExtTrxByTrxId{} }
func (m *SoListExtTrxByTrxId) String() string { return proto.CompactTextString(m) }
func (*SoListExtTrxByTrxId) ProtoMessage()    {}
func (*SoListExtTrxByTrxId) Descriptor() ([]byte, []int) {
	return fileDescriptor_76957eaae1f8a1bc, []int{1}
}

func (m *SoListExtTrxByTrxId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListExtTrxByTrxId.Unmarshal(m, b)
}
func (m *SoListExtTrxByTrxId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListExtTrxByTrxId.Marshal(b, m, deterministic)
}
func (m *SoListExtTrxByTrxId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListExtTrxByTrxId.Merge(m, src)
}
func (m *SoListExtTrxByTrxId) XXX_Size() int {
	return xxx_messageInfo_SoListExtTrxByTrxId.Size(m)
}
func (m *SoListExtTrxByTrxId) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListExtTrxByTrxId.DiscardUnknown(m)
}

var xxx_messageInfo_SoListExtTrxByTrxId proto.InternalMessageInfo

func (m *SoListExtTrxByTrxId) GetTrxId() *prototype.Sha256 {
	if m != nil {
		return m.TrxId
	}
	return nil
}

type SoListExtTrxByBlockHeight struct {
	BlockHeight          uint64            `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	TrxId                *prototype.Sha256 `protobuf:"bytes,2,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SoListExtTrxByBlockHeight) Reset()         { *m = SoListExtTrxByBlockHeight{} }
func (m *SoListExtTrxByBlockHeight) String() string { return proto.CompactTextString(m) }
func (*SoListExtTrxByBlockHeight) ProtoMessage()    {}
func (*SoListExtTrxByBlockHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_76957eaae1f8a1bc, []int{2}
}

func (m *SoListExtTrxByBlockHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListExtTrxByBlockHeight.Unmarshal(m, b)
}
func (m *SoListExtTrxByBlockHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListExtTrxByBlockHeight.Marshal(b, m, deterministic)
}
func (m *SoListExtTrxByBlockHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListExtTrxByBlockHeight.Merge(m, src)
}
func (m *SoListExtTrxByBlockHeight) XXX_Size() int {
	return xxx_messageInfo_SoListExtTrxByBlockHeight.Size(m)
}
func (m *SoListExtTrxByBlockHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListExtTrxByBlockHeight.DiscardUnknown(m)
}

var xxx_messageInfo_SoListExtTrxByBlockHeight proto.InternalMessageInfo

func (m *SoListExtTrxByBlockHeight) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *SoListExtTrxByBlockHeight) GetTrxId() *prototype.Sha256 {
	if m != nil {
		return m.TrxId
	}
	return nil
}

type SoListExtTrxByBlockTime struct {
	BlockTime            *prototype.TimePointSec `protobuf:"bytes,1,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	TrxId                *prototype.Sha256       `protobuf:"bytes,2,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoListExtTrxByBlockTime) Reset()         { *m = SoListExtTrxByBlockTime{} }
func (m *SoListExtTrxByBlockTime) String() string { return proto.CompactTextString(m) }
func (*SoListExtTrxByBlockTime) ProtoMessage()    {}
func (*SoListExtTrxByBlockTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_76957eaae1f8a1bc, []int{3}
}

func (m *SoListExtTrxByBlockTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListExtTrxByBlockTime.Unmarshal(m, b)
}
func (m *SoListExtTrxByBlockTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListExtTrxByBlockTime.Marshal(b, m, deterministic)
}
func (m *SoListExtTrxByBlockTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListExtTrxByBlockTime.Merge(m, src)
}
func (m *SoListExtTrxByBlockTime) XXX_Size() int {
	return xxx_messageInfo_SoListExtTrxByBlockTime.Size(m)
}
func (m *SoListExtTrxByBlockTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListExtTrxByBlockTime.DiscardUnknown(m)
}

var xxx_messageInfo_SoListExtTrxByBlockTime proto.InternalMessageInfo

func (m *SoListExtTrxByBlockTime) GetBlockTime() *prototype.TimePointSec {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

func (m *SoListExtTrxByBlockTime) GetTrxId() *prototype.Sha256 {
	if m != nil {
		return m.TrxId
	}
	return nil
}

type SoListExtTrxByTrxCreateOrder struct {
	TrxCreateOrder       *prototype.UserTrxCreateOrder `protobuf:"bytes,1,opt,name=trx_create_order,json=trxCreateOrder,proto3" json:"trx_create_order,omitempty"`
	TrxId                *prototype.Sha256             `protobuf:"bytes,2,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SoListExtTrxByTrxCreateOrder) Reset()         { *m = SoListExtTrxByTrxCreateOrder{} }
func (m *SoListExtTrxByTrxCreateOrder) String() string { return proto.CompactTextString(m) }
func (*SoListExtTrxByTrxCreateOrder) ProtoMessage()    {}
func (*SoListExtTrxByTrxCreateOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_76957eaae1f8a1bc, []int{4}
}

func (m *SoListExtTrxByTrxCreateOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListExtTrxByTrxCreateOrder.Unmarshal(m, b)
}
func (m *SoListExtTrxByTrxCreateOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListExtTrxByTrxCreateOrder.Marshal(b, m, deterministic)
}
func (m *SoListExtTrxByTrxCreateOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListExtTrxByTrxCreateOrder.Merge(m, src)
}
func (m *SoListExtTrxByTrxCreateOrder) XXX_Size() int {
	return xxx_messageInfo_SoListExtTrxByTrxCreateOrder.Size(m)
}
func (m *SoListExtTrxByTrxCreateOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListExtTrxByTrxCreateOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SoListExtTrxByTrxCreateOrder proto.InternalMessageInfo

func (m *SoListExtTrxByTrxCreateOrder) GetTrxCreateOrder() *prototype.UserTrxCreateOrder {
	if m != nil {
		return m.TrxCreateOrder
	}
	return nil
}

func (m *SoListExtTrxByTrxCreateOrder) GetTrxId() *prototype.Sha256 {
	if m != nil {
		return m.TrxId
	}
	return nil
}

type SoUniqueExtTrxByTrxId struct {
	TrxId                *prototype.Sha256 `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SoUniqueExtTrxByTrxId) Reset()         { *m = SoUniqueExtTrxByTrxId{} }
func (m *SoUniqueExtTrxByTrxId) String() string { return proto.CompactTextString(m) }
func (*SoUniqueExtTrxByTrxId) ProtoMessage()    {}
func (*SoUniqueExtTrxByTrxId) Descriptor() ([]byte, []int) {
	return fileDescriptor_76957eaae1f8a1bc, []int{5}
}

func (m *SoUniqueExtTrxByTrxId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueExtTrxByTrxId.Unmarshal(m, b)
}
func (m *SoUniqueExtTrxByTrxId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueExtTrxByTrxId.Marshal(b, m, deterministic)
}
func (m *SoUniqueExtTrxByTrxId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueExtTrxByTrxId.Merge(m, src)
}
func (m *SoUniqueExtTrxByTrxId) XXX_Size() int {
	return xxx_messageInfo_SoUniqueExtTrxByTrxId.Size(m)
}
func (m *SoUniqueExtTrxByTrxId) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueExtTrxByTrxId.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueExtTrxByTrxId proto.InternalMessageInfo

func (m *SoUniqueExtTrxByTrxId) GetTrxId() *prototype.Sha256 {
	if m != nil {
		return m.TrxId
	}
	return nil
}

func init() {
	proto.RegisterType((*SoExtTrx)(nil), "table.so_extTrx")
	proto.RegisterType((*SoListExtTrxByTrxId)(nil), "table.so_list_extTrx_by_trx_id")
	proto.RegisterType((*SoListExtTrxByBlockHeight)(nil), "table.so_list_extTrx_by_block_height")
	proto.RegisterType((*SoListExtTrxByBlockTime)(nil), "table.so_list_extTrx_by_block_time")
	proto.RegisterType((*SoListExtTrxByTrxCreateOrder)(nil), "table.so_list_extTrx_by_trx_create_order")
	proto.RegisterType((*SoUniqueExtTrxByTrxId)(nil), "table.so_unique_extTrx_by_trx_id")
}

func init() { proto.RegisterFile("app/table/so_extTrx.proto", fileDescriptor_76957eaae1f8a1bc) }

var fileDescriptor_76957eaae1f8a1bc = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x8b, 0xd3, 0x40,
	0x18, 0x66, 0xea, 0xb6, 0xbb, 0x3b, 0x2b, 0xa2, 0xc1, 0xc3, 0x6c, 0x95, 0xa5, 0xe6, 0x54, 0x64,
	0x4d, 0xa0, 0xa2, 0xe8, 0x55, 0x45, 0xac, 0x17, 0x21, 0x14, 0x04, 0x2f, 0xc3, 0x64, 0xf2, 0xd2,
	0x0c, 0x26, 0x99, 0x71, 0xe6, 0x0d, 0xa6, 0x57, 0x7f, 0x86, 0x7f, 0xc8, 0xbf, 0x25, 0x99, 0x94,
	0x36, 0xf4, 0x03, 0xab, 0x1e, 0xf3, 0xcc, 0xf3, 0xf1, 0xf2, 0x3c, 0x84, 0x5e, 0x0b, 0x63, 0x62,
	0x14, 0x69, 0x01, 0xb1, 0xd3, 0x1c, 0x1a, 0x5c, 0xd8, 0x26, 0x32, 0x56, 0xa3, 0x0e, 0x86, 0x1e,
	0x1e, 0x3f, 0xf2, 0x5f, 0xb8, 0x32, 0x10, 0xa3, 0x15, 0x95, 0x13, 0x12, 0x95, 0xae, 0x3a, 0xce,
	0x98, 0x6d, 0x1f, 0xcb, 0xba, 0x40, 0xc5, 0x55, 0xb6, 0x7e, 0x79, 0xd8, 0x93, 0xad, 0x0c, 0x74,
	0x68, 0xf8, 0x6b, 0x40, 0x2f, 0x37, 0x39, 0xc1, 0x94, 0x8e, 0xd0, 0x36, 0x5c, 0x65, 0x8c, 0x4c,
	0xc8, 0xf4, 0x6a, 0xf6, 0x20, 0xda, 0x88, 0x22, 0x97, 0x8b, 0xd9, 0x8b, 0x97, 0xc9, 0x10, 0x6d,
	0x33, 0xcf, 0x82, 0x27, 0xf4, 0x6e, 0x5a, 0x68, 0xf9, 0x95, 0xe7, 0xa0, 0x96, 0x39, 0xb2, 0xc1,
	0x84, 0x4c, 0xcf, 0x92, 0x2b, 0x8f, 0x7d, 0xf0, 0x50, 0xf0, 0x9a, 0x5e, 0xb4, 0x66, 0xdf, 0xad,
	0x30, 0xec, 0x8e, 0xb7, 0xbb, 0xe9, 0xd9, 0xf5, 0x4e, 0xf7, 0x14, 0x03, 0x36, 0x39, 0x47, 0xdb,
	0x7c, 0xb6, 0xc2, 0x04, 0xaf, 0x28, 0xed, 0xdc, 0x51, 0x95, 0xc0, 0xce, 0xbc, 0xf8, 0xba, 0x2f,
	0x56, 0x25, 0x70, 0xa3, 0x55, 0x85, 0xdc, 0x81, 0x4c, 0x2e, 0x3d, 0x79, 0xa1, 0x4a, 0x08, 0x3e,
	0xd2, 0xfb, 0x6d, 0xa8, 0xb4, 0x20, 0x10, 0xb8, 0xb6, 0x19, 0x58, 0x36, 0xf4, 0xfa, 0x49, 0x4f,
	0x5f, 0x3b, 0xb0, 0x7c, 0x97, 0x97, 0xdc, 0x43, 0xdb, 0xbc, 0xf5, 0xc0, 0xa7, 0xf6, 0x3b, 0xb8,
	0xa5, 0x17, 0xdd, 0x15, 0x2a, 0x63, 0xa3, 0x63, 0x7d, 0x9c, 0x7b, 0xca, 0x3c, 0x0b, 0xdf, 0x51,
	0xe6, 0x34, 0x2f, 0x94, 0xc3, 0x75, 0x9b, 0x3c, 0x5d, 0xf1, 0xae, 0xcd, 0xd3, 0x7b, 0x0d, 0x4b,
	0x7a, 0xb3, 0xef, 0xd2, 0x6f, 0x7a, 0xaf, 0x79, 0xb2, 0xdf, 0xfc, 0x36, 0x6e, 0xf0, 0x87, 0xb8,
	0x1f, 0x84, 0x3e, 0x3e, 0x96, 0xd7, 0x96, 0xbc, 0xb3, 0x04, 0xf9, 0x8b, 0x25, 0x4e, 0x3f, 0xe2,
	0x27, 0xa1, 0xe1, 0xe1, 0xea, 0xfa, 0xf3, 0x1c, 0x9c, 0x96, 0xfc, 0xe3, 0xb4, 0xa7, 0x1f, 0xf7,
	0x9e, 0x8e, 0x9d, 0xe6, 0x75, 0xa5, 0xbe, 0xd5, 0xf0, 0x1f, 0xc3, 0xbe, 0xb9, 0xfd, 0xf2, 0x74,
	0xa9, 0x30, 0xaf, 0xd3, 0x48, 0xea, 0x32, 0x96, 0xda, 0xc9, 0x5c, 0xa8, 0x2a, 0x96, 0xba, 0x42,
	0xa8, 0x50, 0xbb, 0x67, 0x4b, 0x1d, 0x6f, 0x7e, 0xfd, 0x74, 0xe4, 0x6d, 0x9e, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0x05, 0xd2, 0x33, 0x0e, 0x04, 0x00, 0x00,
}
