// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_following.proto

package table

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SoFollowing struct {
	Account              *prototype.AccountName  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Following            *prototype.AccountName  `protobuf:"bytes,2,opt,name=following,proto3" json:"following,omitempty"`
	CreateTime           *prototype.TimePointSec `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoFollowing) Reset()         { *m = SoFollowing{} }
func (m *SoFollowing) String() string { return proto.CompactTextString(m) }
func (*SoFollowing) ProtoMessage()    {}
func (*SoFollowing) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f46122cc3ea918f, []int{0}
}

func (m *SoFollowing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoFollowing.Unmarshal(m, b)
}
func (m *SoFollowing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoFollowing.Marshal(b, m, deterministic)
}
func (m *SoFollowing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoFollowing.Merge(m, src)
}
func (m *SoFollowing) XXX_Size() int {
	return xxx_messageInfo_SoFollowing.Size(m)
}
func (m *SoFollowing) XXX_DiscardUnknown() {
	xxx_messageInfo_SoFollowing.DiscardUnknown(m)
}

var xxx_messageInfo_SoFollowing proto.InternalMessageInfo

func (m *SoFollowing) GetAccount() *prototype.AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SoFollowing) GetFollowing() *prototype.AccountName {
	if m != nil {
		return m.Following
	}
	return nil
}

func (m *SoFollowing) GetCreateTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type SoListFollowingByCreateTime struct {
	CreateTime           *prototype.TimePointSec `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Account              *prototype.AccountName  `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SoListFollowingByCreateTime) Reset()         { *m = SoListFollowingByCreateTime{} }
func (m *SoListFollowingByCreateTime) String() string { return proto.CompactTextString(m) }
func (*SoListFollowingByCreateTime) ProtoMessage()    {}
func (*SoListFollowingByCreateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f46122cc3ea918f, []int{1}
}

func (m *SoListFollowingByCreateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoListFollowingByCreateTime.Unmarshal(m, b)
}
func (m *SoListFollowingByCreateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoListFollowingByCreateTime.Marshal(b, m, deterministic)
}
func (m *SoListFollowingByCreateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoListFollowingByCreateTime.Merge(m, src)
}
func (m *SoListFollowingByCreateTime) XXX_Size() int {
	return xxx_messageInfo_SoListFollowingByCreateTime.Size(m)
}
func (m *SoListFollowingByCreateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SoListFollowingByCreateTime.DiscardUnknown(m)
}

var xxx_messageInfo_SoListFollowingByCreateTime proto.InternalMessageInfo

func (m *SoListFollowingByCreateTime) GetCreateTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *SoListFollowingByCreateTime) GetAccount() *prototype.AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

type SoUniqueFollowingByAccount struct {
	Account              *prototype.AccountName `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoUniqueFollowingByAccount) Reset()         { *m = SoUniqueFollowingByAccount{} }
func (m *SoUniqueFollowingByAccount) String() string { return proto.CompactTextString(m) }
func (*SoUniqueFollowingByAccount) ProtoMessage()    {}
func (*SoUniqueFollowingByAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f46122cc3ea918f, []int{2}
}

func (m *SoUniqueFollowingByAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueFollowingByAccount.Unmarshal(m, b)
}
func (m *SoUniqueFollowingByAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueFollowingByAccount.Marshal(b, m, deterministic)
}
func (m *SoUniqueFollowingByAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueFollowingByAccount.Merge(m, src)
}
func (m *SoUniqueFollowingByAccount) XXX_Size() int {
	return xxx_messageInfo_SoUniqueFollowingByAccount.Size(m)
}
func (m *SoUniqueFollowingByAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueFollowingByAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueFollowingByAccount proto.InternalMessageInfo

func (m *SoUniqueFollowingByAccount) GetAccount() *prototype.AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

type SoUniqueFollowingByFollowing struct {
	Following            *prototype.AccountName `protobuf:"bytes,1,opt,name=following,proto3" json:"following,omitempty"`
	Account              *prototype.AccountName `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SoUniqueFollowingByFollowing) Reset()         { *m = SoUniqueFollowingByFollowing{} }
func (m *SoUniqueFollowingByFollowing) String() string { return proto.CompactTextString(m) }
func (*SoUniqueFollowingByFollowing) ProtoMessage()    {}
func (*SoUniqueFollowingByFollowing) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f46122cc3ea918f, []int{3}
}

func (m *SoUniqueFollowingByFollowing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueFollowingByFollowing.Unmarshal(m, b)
}
func (m *SoUniqueFollowingByFollowing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueFollowingByFollowing.Marshal(b, m, deterministic)
}
func (m *SoUniqueFollowingByFollowing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueFollowingByFollowing.Merge(m, src)
}
func (m *SoUniqueFollowingByFollowing) XXX_Size() int {
	return xxx_messageInfo_SoUniqueFollowingByFollowing.Size(m)
}
func (m *SoUniqueFollowingByFollowing) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueFollowingByFollowing.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueFollowingByFollowing proto.InternalMessageInfo

func (m *SoUniqueFollowingByFollowing) GetFollowing() *prototype.AccountName {
	if m != nil {
		return m.Following
	}
	return nil
}

func (m *SoUniqueFollowingByFollowing) GetAccount() *prototype.AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*SoFollowing)(nil), "table.so_following")
	proto.RegisterType((*SoListFollowingByCreateTime)(nil), "table.so_list_following_by_create_time")
	proto.RegisterType((*SoUniqueFollowingByAccount)(nil), "table.so_unique_following_by_account")
	proto.RegisterType((*SoUniqueFollowingByFollowing)(nil), "table.so_unique_following_by_following")
}

func init() { proto.RegisterFile("app/table/so_following.proto", fileDescriptor_0f46122cc3ea918f) }

var fileDescriptor_0f46122cc3ea918f = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0x45, 0xc5, 0xd4, 0xd3, 0x22, 0xb8, 0x8a, 0x48, 0xd9, 0x83, 0xf4, 0xe2, 0x06,
	0x15, 0x2f, 0x1e, 0x7d, 0x84, 0xea, 0xc9, 0xcb, 0x90, 0x0d, 0xe3, 0x36, 0xb0, 0x9b, 0x89, 0xcd,
	0x2c, 0xd2, 0x77, 0xf0, 0xe2, 0xbb, 0xf8, 0x80, 0xd2, 0x5d, 0xdb, 0x4d, 0x45, 0xa4, 0x7b, 0x09,
	0x24, 0x33, 0xdf, 0x3f, 0x33, 0xff, 0x44, 0x5e, 0x68, 0xef, 0x15, 0xeb, 0xa2, 0x42, 0x15, 0x08,
	0x5e, 0xa9, 0xaa, 0xe8, 0xdd, 0xba, 0x32, 0xf7, 0x0b, 0x62, 0x4a, 0xf6, 0xdb, 0xc8, 0xf9, 0x49,
	0x7b, 0xe3, 0xa5, 0x47, 0xb5, 0x3a, 0xba, 0x60, 0xf6, 0x25, 0xe4, 0x71, 0xcc, 0x24, 0x37, 0xf2,
	0x50, 0x1b, 0x43, 0x8d, 0xe3, 0x54, 0x4c, 0xc4, 0x74, 0x7c, 0x7b, 0x9a, 0x6f, 0xc0, 0xfc, 0x27,
	0x02, 0x4e, 0xd7, 0x38, 0x5b, 0xe7, 0x25, 0xf7, 0xf2, 0x68, 0xc3, 0xa7, 0xa3, 0xff, 0xa1, 0x3e,
	0x33, 0x79, 0x90, 0x63, 0xb3, 0x40, 0xcd, 0x08, 0x6c, 0x6b, 0x4c, 0xf7, 0x5a, 0xf0, 0x2c, 0x02,
	0x57, 0xcf, 0xe0, 0xc9, 0x3a, 0x86, 0x80, 0x66, 0x26, 0xbb, 0xec, 0x67, 0x5b, 0x63, 0xf6, 0x29,
	0xe4, 0x24, 0x10, 0x54, 0x36, 0x70, 0xdf, 0x3b, 0x14, 0x4b, 0x88, 0x14, 0x7f, 0x17, 0x10, 0x03,
	0x0a, 0xc4, 0x36, 0x8c, 0x76, 0xb3, 0x21, 0x7b, 0x92, 0x97, 0x81, 0xa0, 0x71, 0xf6, 0xad, 0xc1,
	0xed, 0xa6, 0xd6, 0x46, 0x0d, 0xf7, 0x36, 0xfb, 0xe8, 0x06, 0xfd, 0x4b, 0xb5, 0x77, 0x72, 0x6b,
	0x01, 0x62, 0xe7, 0x05, 0x0c, 0x9f, 0xf1, 0x71, 0xfa, 0x72, 0x55, 0x5a, 0x9e, 0x37, 0x45, 0x6e,
	0xa8, 0x56, 0x86, 0x82, 0x99, 0x6b, 0xeb, 0x94, 0x21, 0xc7, 0xe8, 0x98, 0xc2, 0x75, 0x49, 0xdd,
	0x47, 0x2c, 0x0e, 0x5a, 0xa9, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x8a, 0xcf, 0x2f,
	0x9c, 0x02, 0x00, 0x00,
}
