// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/table/so_witnessScheduleObject.proto

package table

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SoWitnessScheduleObject struct {
	Id                     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentShuffledWitness []string `protobuf:"bytes,2,rep,name=current_shuffled_witness,json=currentShuffledWitness,proto3" json:"current_shuffled_witness,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *SoWitnessScheduleObject) Reset()         { *m = SoWitnessScheduleObject{} }
func (m *SoWitnessScheduleObject) String() string { return proto.CompactTextString(m) }
func (*SoWitnessScheduleObject) ProtoMessage()    {}
func (*SoWitnessScheduleObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecbb71179ce2dbce, []int{0}
}

func (m *SoWitnessScheduleObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoWitnessScheduleObject.Unmarshal(m, b)
}
func (m *SoWitnessScheduleObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoWitnessScheduleObject.Marshal(b, m, deterministic)
}
func (m *SoWitnessScheduleObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoWitnessScheduleObject.Merge(m, src)
}
func (m *SoWitnessScheduleObject) XXX_Size() int {
	return xxx_messageInfo_SoWitnessScheduleObject.Size(m)
}
func (m *SoWitnessScheduleObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SoWitnessScheduleObject.DiscardUnknown(m)
}

var xxx_messageInfo_SoWitnessScheduleObject proto.InternalMessageInfo

func (m *SoWitnessScheduleObject) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SoWitnessScheduleObject) GetCurrentShuffledWitness() []string {
	if m != nil {
		return m.CurrentShuffledWitness
	}
	return nil
}

type SoUniqueWitnessScheduleObjectById struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoUniqueWitnessScheduleObjectById) Reset()         { *m = SoUniqueWitnessScheduleObjectById{} }
func (m *SoUniqueWitnessScheduleObjectById) String() string { return proto.CompactTextString(m) }
func (*SoUniqueWitnessScheduleObjectById) ProtoMessage()    {}
func (*SoUniqueWitnessScheduleObjectById) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecbb71179ce2dbce, []int{1}
}

func (m *SoUniqueWitnessScheduleObjectById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoUniqueWitnessScheduleObjectById.Unmarshal(m, b)
}
func (m *SoUniqueWitnessScheduleObjectById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoUniqueWitnessScheduleObjectById.Marshal(b, m, deterministic)
}
func (m *SoUniqueWitnessScheduleObjectById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoUniqueWitnessScheduleObjectById.Merge(m, src)
}
func (m *SoUniqueWitnessScheduleObjectById) XXX_Size() int {
	return xxx_messageInfo_SoUniqueWitnessScheduleObjectById.Size(m)
}
func (m *SoUniqueWitnessScheduleObjectById) XXX_DiscardUnknown() {
	xxx_messageInfo_SoUniqueWitnessScheduleObjectById.DiscardUnknown(m)
}

var xxx_messageInfo_SoUniqueWitnessScheduleObjectById proto.InternalMessageInfo

func (m *SoUniqueWitnessScheduleObjectById) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*SoWitnessScheduleObject)(nil), "table.so_witnessScheduleObject")
	proto.RegisterType((*SoUniqueWitnessScheduleObjectById)(nil), "table.so_unique_witnessScheduleObject_by_id")
}

func init() {
	proto.RegisterFile("app/table/so_witnessScheduleObject.proto", fileDescriptor_ecbb71179ce2dbce)
}

var fileDescriptor_ecbb71179ce2dbce = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x69, 0xa5, 0x82, 0x19, 0x1c, 0x3a, 0x48, 0xc6, 0x52, 0x50, 0xb2, 0xd8, 0x0c, 0x0e,
	0x3a, 0xfb, 0x07, 0x84, 0x76, 0x10, 0x5c, 0x42, 0x93, 0x7c, 0x6d, 0x22, 0x35, 0x5f, 0x6d, 0xbe,
	0x70, 0xdc, 0xbf, 0x3f, 0x68, 0x7b, 0xcb, 0x71, 0x37, 0x3f, 0xef, 0xcb, 0xc3, 0xc3, 0x44, 0x3f,
	0xcf, 0x92, 0x7a, 0x3d, 0x81, 0x8c, 0xa8, 0x0e, 0x9e, 0x02, 0xc4, 0xd8, 0x19, 0x07, 0x36, 0x4d,
	0xf0, 0xa5, 0x7f, 0xc1, 0x50, 0x33, 0x2f, 0x48, 0x58, 0x16, 0xeb, 0xaa, 0xb6, 0x8c, 0xdf, 0x1a,
	0x96, 0x8f, 0x2c, 0xf7, 0x96, 0x67, 0x55, 0x26, 0x8a, 0x36, 0xf7, 0xb6, 0xfc, 0x60, 0xdc, 0xa4,
	0x65, 0x81, 0x40, 0x2a, 0xba, 0x34, 0x0c, 0x13, 0xd8, 0xf3, 0x93, 0xe7, 0xd5, 0x9d, 0x78, 0x68,
	0x9f, 0x76, 0xde, 0xed, 0xf8, 0x7b, 0xa3, 0xf5, 0x3b, 0x7b, 0x8e, 0xa8, 0x52, 0xf0, 0xff, 0x09,
	0xae, 0xcb, 0x94, 0x3e, 0x2a, 0x6f, 0x2f, 0x95, 0x9f, 0xe2, 0xe7, 0x65, 0xf4, 0xe4, 0x92, 0x6e,
	0x0c, 0xfe, 0x49, 0x83, 0xd1, 0xb8, 0xde, 0x07, 0x69, 0x30, 0x10, 0x04, 0xc2, 0xf8, 0x3a, 0xe2,
	0x96, 0xab, 0xef, 0xd7, 0xac, 0xb7, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0xf7, 0x30, 0xa7,
	0x02, 0x01, 0x00, 0x00,
}
