// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package grpcpb

import (
	fmt "fmt"
	prototype "github.com/coschain/contentos-go/prototype"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccountByNameRequest struct {
	AccountName          *prototype.AccountName `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetAccountByNameRequest) Reset()         { *m = GetAccountByNameRequest{} }
func (m *GetAccountByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountByNameRequest) ProtoMessage()    {}
func (*GetAccountByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *GetAccountByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountByNameRequest.Unmarshal(m, b)
}
func (m *GetAccountByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountByNameRequest.Merge(m, src)
}
func (m *GetAccountByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountByNameRequest.Size(m)
}
func (m *GetAccountByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountByNameRequest proto.InternalMessageInfo

func (m *GetAccountByNameRequest) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

type AccountResponse struct {
	AccountName          *prototype.AccountName     `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Coin                 *prototype.Coin            `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Vest                 *prototype.Vest            `protobuf:"bytes,3,opt,name=vest,proto3" json:"vest,omitempty"`
	PublicKeys           []*prototype.PublicKeyType `protobuf:"bytes,4,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	CreatedTime          *prototype.TimePointSec    `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *AccountResponse) GetCoin() *prototype.Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

func (m *AccountResponse) GetVest() *prototype.Vest {
	if m != nil {
		return m.Vest
	}
	return nil
}

func (m *AccountResponse) GetPublicKeys() []*prototype.PublicKeyType {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *AccountResponse) GetCreatedTime() *prototype.TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

type GetFollowerListByNameRequest struct {
	AccountName          *prototype.AccountName   `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Start                *prototype.FollowerOrder `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Limit                uint32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetFollowerListByNameRequest) Reset()         { *m = GetFollowerListByNameRequest{} }
func (m *GetFollowerListByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowerListByNameRequest) ProtoMessage()    {}
func (*GetFollowerListByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *GetFollowerListByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowerListByNameRequest.Unmarshal(m, b)
}
func (m *GetFollowerListByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowerListByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowerListByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowerListByNameRequest.Merge(m, src)
}
func (m *GetFollowerListByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowerListByNameRequest.Size(m)
}
func (m *GetFollowerListByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowerListByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowerListByNameRequest proto.InternalMessageInfo

func (m *GetFollowerListByNameRequest) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *GetFollowerListByNameRequest) GetStart() *prototype.FollowerOrder {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *GetFollowerListByNameRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetFollowerListByNameResponse struct {
	FollowerList         []*prototype.AccountName `protobuf:"bytes,1,rep,name=follower_list,json=followerList,proto3" json:"follower_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetFollowerListByNameResponse) Reset()         { *m = GetFollowerListByNameResponse{} }
func (m *GetFollowerListByNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowerListByNameResponse) ProtoMessage()    {}
func (*GetFollowerListByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *GetFollowerListByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowerListByNameResponse.Unmarshal(m, b)
}
func (m *GetFollowerListByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowerListByNameResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowerListByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowerListByNameResponse.Merge(m, src)
}
func (m *GetFollowerListByNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowerListByNameResponse.Size(m)
}
func (m *GetFollowerListByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowerListByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowerListByNameResponse proto.InternalMessageInfo

func (m *GetFollowerListByNameResponse) GetFollowerList() []*prototype.AccountName {
	if m != nil {
		return m.FollowerList
	}
	return nil
}

type GetFollowingListByNameRequest struct {
	AccountName          *prototype.AccountName    `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Start                *prototype.FollowingOrder `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Limit                uint32                    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetFollowingListByNameRequest) Reset()         { *m = GetFollowingListByNameRequest{} }
func (m *GetFollowingListByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowingListByNameRequest) ProtoMessage()    {}
func (*GetFollowingListByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{4}
}

func (m *GetFollowingListByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowingListByNameRequest.Unmarshal(m, b)
}
func (m *GetFollowingListByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowingListByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowingListByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowingListByNameRequest.Merge(m, src)
}
func (m *GetFollowingListByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowingListByNameRequest.Size(m)
}
func (m *GetFollowingListByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowingListByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowingListByNameRequest proto.InternalMessageInfo

func (m *GetFollowingListByNameRequest) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *GetFollowingListByNameRequest) GetStart() *prototype.FollowingOrder {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *GetFollowingListByNameRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetFollowingListByNameResponse struct {
	FollowingList        []*prototype.AccountName `protobuf:"bytes,1,rep,name=following_list,json=followingList,proto3" json:"following_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetFollowingListByNameResponse) Reset()         { *m = GetFollowingListByNameResponse{} }
func (m *GetFollowingListByNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowingListByNameResponse) ProtoMessage()    {}
func (*GetFollowingListByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{5}
}

func (m *GetFollowingListByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowingListByNameResponse.Unmarshal(m, b)
}
func (m *GetFollowingListByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowingListByNameResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowingListByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowingListByNameResponse.Merge(m, src)
}
func (m *GetFollowingListByNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowingListByNameResponse.Size(m)
}
func (m *GetFollowingListByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowingListByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowingListByNameResponse proto.InternalMessageInfo

func (m *GetFollowingListByNameResponse) GetFollowingList() []*prototype.AccountName {
	if m != nil {
		return m.FollowingList
	}
	return nil
}

type GetFollowCountByNameRequest struct {
	AccountName          *prototype.AccountName `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetFollowCountByNameRequest) Reset()         { *m = GetFollowCountByNameRequest{} }
func (m *GetFollowCountByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowCountByNameRequest) ProtoMessage()    {}
func (*GetFollowCountByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{6}
}

func (m *GetFollowCountByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowCountByNameRequest.Unmarshal(m, b)
}
func (m *GetFollowCountByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowCountByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowCountByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowCountByNameRequest.Merge(m, src)
}
func (m *GetFollowCountByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowCountByNameRequest.Size(m)
}
func (m *GetFollowCountByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowCountByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowCountByNameRequest proto.InternalMessageInfo

func (m *GetFollowCountByNameRequest) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

type GetFollowCountByNameResponse struct {
	FerCnt               uint32   `protobuf:"varint,1,opt,name=fer_cnt,json=ferCnt,proto3" json:"fer_cnt,omitempty"`
	FingCnt              uint32   `protobuf:"varint,2,opt,name=fing_cnt,json=fingCnt,proto3" json:"fing_cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowCountByNameResponse) Reset()         { *m = GetFollowCountByNameResponse{} }
func (m *GetFollowCountByNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowCountByNameResponse) ProtoMessage()    {}
func (*GetFollowCountByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{7}
}

func (m *GetFollowCountByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowCountByNameResponse.Unmarshal(m, b)
}
func (m *GetFollowCountByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowCountByNameResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowCountByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowCountByNameResponse.Merge(m, src)
}
func (m *GetFollowCountByNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowCountByNameResponse.Size(m)
}
func (m *GetFollowCountByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowCountByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowCountByNameResponse proto.InternalMessageInfo

func (m *GetFollowCountByNameResponse) GetFerCnt() uint32 {
	if m != nil {
		return m.FerCnt
	}
	return 0
}

func (m *GetFollowCountByNameResponse) GetFingCnt() uint32 {
	if m != nil {
		return m.FingCnt
	}
	return 0
}

type WitnessResponse struct {
	AccountName          *prototype.AccountName   `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Created              *prototype.TimePointSec  `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Url                  string                   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	SigningKey           *prototype.PublicKeyType `protobuf:"bytes,4,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	ScheduleType         uint32                   `protobuf:"varint,5,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WitnessResponse) Reset()         { *m = WitnessResponse{} }
func (m *WitnessResponse) String() string { return proto.CompactTextString(m) }
func (*WitnessResponse) ProtoMessage()    {}
func (*WitnessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{8}
}

func (m *WitnessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WitnessResponse.Unmarshal(m, b)
}
func (m *WitnessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WitnessResponse.Marshal(b, m, deterministic)
}
func (m *WitnessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessResponse.Merge(m, src)
}
func (m *WitnessResponse) XXX_Size() int {
	return xxx_messageInfo_WitnessResponse.Size(m)
}
func (m *WitnessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessResponse proto.InternalMessageInfo

func (m *WitnessResponse) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *WitnessResponse) GetCreated() *prototype.TimePointSec {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *WitnessResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *WitnessResponse) GetSigningKey() *prototype.PublicKeyType {
	if m != nil {
		return m.SigningKey
	}
	return nil
}

func (m *WitnessResponse) GetScheduleType() uint32 {
	if m != nil {
		return m.ScheduleType
	}
	return 0
}

type GetWitnessListRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWitnessListRequest) Reset()         { *m = GetWitnessListRequest{} }
func (m *GetWitnessListRequest) String() string { return proto.CompactTextString(m) }
func (*GetWitnessListRequest) ProtoMessage()    {}
func (*GetWitnessListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{9}
}

func (m *GetWitnessListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWitnessListRequest.Unmarshal(m, b)
}
func (m *GetWitnessListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWitnessListRequest.Marshal(b, m, deterministic)
}
func (m *GetWitnessListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWitnessListRequest.Merge(m, src)
}
func (m *GetWitnessListRequest) XXX_Size() int {
	return xxx_messageInfo_GetWitnessListRequest.Size(m)
}
func (m *GetWitnessListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWitnessListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWitnessListRequest proto.InternalMessageInfo

func (m *GetWitnessListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetWitnessListRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetWitnessListResponse struct {
	WitnessList          []*WitnessResponse `protobuf:"bytes,1,rep,name=witness_list,json=witnessList,proto3" json:"witness_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetWitnessListResponse) Reset()         { *m = GetWitnessListResponse{} }
func (m *GetWitnessListResponse) String() string { return proto.CompactTextString(m) }
func (*GetWitnessListResponse) ProtoMessage()    {}
func (*GetWitnessListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{10}
}

func (m *GetWitnessListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWitnessListResponse.Unmarshal(m, b)
}
func (m *GetWitnessListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWitnessListResponse.Marshal(b, m, deterministic)
}
func (m *GetWitnessListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWitnessListResponse.Merge(m, src)
}
func (m *GetWitnessListResponse) XXX_Size() int {
	return xxx_messageInfo_GetWitnessListResponse.Size(m)
}
func (m *GetWitnessListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWitnessListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWitnessListResponse proto.InternalMessageInfo

func (m *GetWitnessListResponse) GetWitnessList() []*WitnessResponse {
	if m != nil {
		return m.WitnessList
	}
	return nil
}

type PostResponse struct {
	Idx                  uint32                  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Name                 *prototype.AccountName  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PostTime             *prototype.TimePointSec `protobuf:"bytes,3,opt,name=post_time,json=postTime,proto3" json:"post_time,omitempty"`
	Content              string                  `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount            uint32                  `protobuf:"varint,5,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{11}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetIdx() uint32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func (m *PostResponse) GetName() *prototype.AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *PostResponse) GetPostTime() *prototype.TimePointSec {
	if m != nil {
		return m.PostTime
	}
	return nil
}

func (m *PostResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostResponse) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

type GetPostListByCreatedRequest struct {
	AccountName          *prototype.AccountName `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Page                 uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetPostListByCreatedRequest) Reset()         { *m = GetPostListByCreatedRequest{} }
func (m *GetPostListByCreatedRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostListByCreatedRequest) ProtoMessage()    {}
func (*GetPostListByCreatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{12}
}

func (m *GetPostListByCreatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostListByCreatedRequest.Unmarshal(m, b)
}
func (m *GetPostListByCreatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostListByCreatedRequest.Marshal(b, m, deterministic)
}
func (m *GetPostListByCreatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostListByCreatedRequest.Merge(m, src)
}
func (m *GetPostListByCreatedRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostListByCreatedRequest.Size(m)
}
func (m *GetPostListByCreatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostListByCreatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostListByCreatedRequest proto.InternalMessageInfo

func (m *GetPostListByCreatedRequest) GetAccountName() *prototype.AccountName {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *GetPostListByCreatedRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetPostListByCreatedRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetPostListByCreatedResponse struct {
	PostList             []*PostResponse `protobuf:"bytes,1,rep,name=post_list,json=postList,proto3" json:"post_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetPostListByCreatedResponse) Reset()         { *m = GetPostListByCreatedResponse{} }
func (m *GetPostListByCreatedResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostListByCreatedResponse) ProtoMessage()    {}
func (*GetPostListByCreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{13}
}

func (m *GetPostListByCreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostListByCreatedResponse.Unmarshal(m, b)
}
func (m *GetPostListByCreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostListByCreatedResponse.Marshal(b, m, deterministic)
}
func (m *GetPostListByCreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostListByCreatedResponse.Merge(m, src)
}
func (m *GetPostListByCreatedResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostListByCreatedResponse.Size(m)
}
func (m *GetPostListByCreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostListByCreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostListByCreatedResponse proto.InternalMessageInfo

func (m *GetPostListByCreatedResponse) GetPostList() []*PostResponse {
	if m != nil {
		return m.PostList
	}
	return nil
}

type GetReplayListByPostIdRequest struct {
	PostId               uint32   `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReplayListByPostIdRequest) Reset()         { *m = GetReplayListByPostIdRequest{} }
func (m *GetReplayListByPostIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetReplayListByPostIdRequest) ProtoMessage()    {}
func (*GetReplayListByPostIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{14}
}

func (m *GetReplayListByPostIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplayListByPostIdRequest.Unmarshal(m, b)
}
func (m *GetReplayListByPostIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplayListByPostIdRequest.Marshal(b, m, deterministic)
}
func (m *GetReplayListByPostIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplayListByPostIdRequest.Merge(m, src)
}
func (m *GetReplayListByPostIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetReplayListByPostIdRequest.Size(m)
}
func (m *GetReplayListByPostIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplayListByPostIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplayListByPostIdRequest proto.InternalMessageInfo

func (m *GetReplayListByPostIdRequest) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type GetReplayListByPostIdResponse struct {
	ReplayList           []*PostResponse `protobuf:"bytes,1,rep,name=replay_list,json=replayList,proto3" json:"replay_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetReplayListByPostIdResponse) Reset()         { *m = GetReplayListByPostIdResponse{} }
func (m *GetReplayListByPostIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetReplayListByPostIdResponse) ProtoMessage()    {}
func (*GetReplayListByPostIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{15}
}

func (m *GetReplayListByPostIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplayListByPostIdResponse.Unmarshal(m, b)
}
func (m *GetReplayListByPostIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplayListByPostIdResponse.Marshal(b, m, deterministic)
}
func (m *GetReplayListByPostIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplayListByPostIdResponse.Merge(m, src)
}
func (m *GetReplayListByPostIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetReplayListByPostIdResponse.Size(m)
}
func (m *GetReplayListByPostIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplayListByPostIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplayListByPostIdResponse proto.InternalMessageInfo

func (m *GetReplayListByPostIdResponse) GetReplayList() []*PostResponse {
	if m != nil {
		return m.ReplayList
	}
	return nil
}

type GetBlockTransactionsByNumRequest struct {
	BlockNum             uint32   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockTransactionsByNumRequest) Reset()         { *m = GetBlockTransactionsByNumRequest{} }
func (m *GetBlockTransactionsByNumRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockTransactionsByNumRequest) ProtoMessage()    {}
func (*GetBlockTransactionsByNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{16}
}

func (m *GetBlockTransactionsByNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockTransactionsByNumRequest.Unmarshal(m, b)
}
func (m *GetBlockTransactionsByNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockTransactionsByNumRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockTransactionsByNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockTransactionsByNumRequest.Merge(m, src)
}
func (m *GetBlockTransactionsByNumRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockTransactionsByNumRequest.Size(m)
}
func (m *GetBlockTransactionsByNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockTransactionsByNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockTransactionsByNumRequest proto.InternalMessageInfo

func (m *GetBlockTransactionsByNumRequest) GetBlockNum() uint32 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetBlockTransactionsByNumRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetBlockTransactionsByNumRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetBlockTransactionsByNumResponse struct {
	Transactions         []*prototype.SignedTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetBlockTransactionsByNumResponse) Reset()         { *m = GetBlockTransactionsByNumResponse{} }
func (m *GetBlockTransactionsByNumResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockTransactionsByNumResponse) ProtoMessage()    {}
func (*GetBlockTransactionsByNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{17}
}

func (m *GetBlockTransactionsByNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockTransactionsByNumResponse.Unmarshal(m, b)
}
func (m *GetBlockTransactionsByNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockTransactionsByNumResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockTransactionsByNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockTransactionsByNumResponse.Merge(m, src)
}
func (m *GetBlockTransactionsByNumResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockTransactionsByNumResponse.Size(m)
}
func (m *GetBlockTransactionsByNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockTransactionsByNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockTransactionsByNumResponse proto.InternalMessageInfo

func (m *GetBlockTransactionsByNumResponse) GetTransactions() []*prototype.SignedTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetTrxByIdRequest struct {
	TrxId                uint64   `protobuf:"varint,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTrxByIdRequest) Reset()         { *m = GetTrxByIdRequest{} }
func (m *GetTrxByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetTrxByIdRequest) ProtoMessage()    {}
func (*GetTrxByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{18}
}

func (m *GetTrxByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrxByIdRequest.Unmarshal(m, b)
}
func (m *GetTrxByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrxByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetTrxByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrxByIdRequest.Merge(m, src)
}
func (m *GetTrxByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetTrxByIdRequest.Size(m)
}
func (m *GetTrxByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrxByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrxByIdRequest proto.InternalMessageInfo

func (m *GetTrxByIdRequest) GetTrxId() uint64 {
	if m != nil {
		return m.TrxId
	}
	return 0
}

type GetTrxByIdResponse struct {
	Trx                  *prototype.Transaction `protobuf:"bytes,1,opt,name=trx,proto3" json:"trx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetTrxByIdResponse) Reset()         { *m = GetTrxByIdResponse{} }
func (m *GetTrxByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetTrxByIdResponse) ProtoMessage()    {}
func (*GetTrxByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{19}
}

func (m *GetTrxByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrxByIdResponse.Unmarshal(m, b)
}
func (m *GetTrxByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrxByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetTrxByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrxByIdResponse.Merge(m, src)
}
func (m *GetTrxByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetTrxByIdResponse.Size(m)
}
func (m *GetTrxByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrxByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrxByIdResponse proto.InternalMessageInfo

func (m *GetTrxByIdResponse) GetTrx() *prototype.Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

type BroadcastTrxRequest struct {
	Transaction          *prototype.SignedTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *BroadcastTrxRequest) Reset()         { *m = BroadcastTrxRequest{} }
func (m *BroadcastTrxRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastTrxRequest) ProtoMessage()    {}
func (*BroadcastTrxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{20}
}

func (m *BroadcastTrxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastTrxRequest.Unmarshal(m, b)
}
func (m *BroadcastTrxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastTrxRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastTrxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastTrxRequest.Merge(m, src)
}
func (m *BroadcastTrxRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastTrxRequest.Size(m)
}
func (m *BroadcastTrxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastTrxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastTrxRequest proto.InternalMessageInfo

func (m *BroadcastTrxRequest) GetTransaction() *prototype.SignedTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type BroadcastTrxResponse struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastTrxResponse) Reset()         { *m = BroadcastTrxResponse{} }
func (m *BroadcastTrxResponse) String() string { return proto.CompactTextString(m) }
func (*BroadcastTrxResponse) ProtoMessage()    {}
func (*BroadcastTrxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{21}
}

func (m *BroadcastTrxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastTrxResponse.Unmarshal(m, b)
}
func (m *BroadcastTrxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastTrxResponse.Marshal(b, m, deterministic)
}
func (m *BroadcastTrxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastTrxResponse.Merge(m, src)
}
func (m *BroadcastTrxResponse) XXX_Size() int {
	return xxx_messageInfo_BroadcastTrxResponse.Size(m)
}
func (m *BroadcastTrxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastTrxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastTrxResponse proto.InternalMessageInfo

func (m *BroadcastTrxResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BroadcastTrxResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Request message of non params.
type NonParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonParamsRequest) Reset()         { *m = NonParamsRequest{} }
func (m *NonParamsRequest) String() string { return proto.CompactTextString(m) }
func (*NonParamsRequest) ProtoMessage()    {}
func (*NonParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{22}
}

func (m *NonParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonParamsRequest.Unmarshal(m, b)
}
func (m *NonParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonParamsRequest.Marshal(b, m, deterministic)
}
func (m *NonParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonParamsRequest.Merge(m, src)
}
func (m *NonParamsRequest) XXX_Size() int {
	return xxx_messageInfo_NonParamsRequest.Size(m)
}
func (m *NonParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonParamsRequest proto.InternalMessageInfo

// Response message of Call rpc.
type CallResponse struct {
	// result of smart contract method call.
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	//execute error
	ExecuteErr string `protobuf:"bytes,2,opt,name=execute_err,json=executeErr,proto3" json:"execute_err,omitempty"`
	//estimate gas used
	EstimateGas          string   `protobuf:"bytes,3,opt,name=estimate_gas,json=estimateGas,proto3" json:"estimate_gas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResponse) Reset()         { *m = CallResponse{} }
func (m *CallResponse) String() string { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()    {}
func (*CallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{23}
}

func (m *CallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResponse.Unmarshal(m, b)
}
func (m *CallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResponse.Marshal(b, m, deterministic)
}
func (m *CallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResponse.Merge(m, src)
}
func (m *CallResponse) XXX_Size() int {
	return xxx_messageInfo_CallResponse.Size(m)
}
func (m *CallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallResponse proto.InternalMessageInfo

func (m *CallResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *CallResponse) GetExecuteErr() string {
	if m != nil {
		return m.ExecuteErr
	}
	return ""
}

func (m *CallResponse) GetEstimateGas() string {
	if m != nil {
		return m.EstimateGas
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAccountByNameRequest)(nil), "grpcpb.GetAccountByNameRequest")
	proto.RegisterType((*AccountResponse)(nil), "grpcpb.AccountResponse")
	proto.RegisterType((*GetFollowerListByNameRequest)(nil), "grpcpb.GetFollowerListByNameRequest")
	proto.RegisterType((*GetFollowerListByNameResponse)(nil), "grpcpb.GetFollowerListByNameResponse")
	proto.RegisterType((*GetFollowingListByNameRequest)(nil), "grpcpb.GetFollowingListByNameRequest")
	proto.RegisterType((*GetFollowingListByNameResponse)(nil), "grpcpb.GetFollowingListByNameResponse")
	proto.RegisterType((*GetFollowCountByNameRequest)(nil), "grpcpb.GetFollowCountByNameRequest")
	proto.RegisterType((*GetFollowCountByNameResponse)(nil), "grpcpb.GetFollowCountByNameResponse")
	proto.RegisterType((*WitnessResponse)(nil), "grpcpb.WitnessResponse")
	proto.RegisterType((*GetWitnessListRequest)(nil), "grpcpb.GetWitnessListRequest")
	proto.RegisterType((*GetWitnessListResponse)(nil), "grpcpb.GetWitnessListResponse")
	proto.RegisterType((*PostResponse)(nil), "grpcpb.PostResponse")
	proto.RegisterType((*GetPostListByCreatedRequest)(nil), "grpcpb.GetPostListByCreatedRequest")
	proto.RegisterType((*GetPostListByCreatedResponse)(nil), "grpcpb.GetPostListByCreatedResponse")
	proto.RegisterType((*GetReplayListByPostIdRequest)(nil), "grpcpb.GetReplayListByPostIdRequest")
	proto.RegisterType((*GetReplayListByPostIdResponse)(nil), "grpcpb.GetReplayListByPostIdResponse")
	proto.RegisterType((*GetBlockTransactionsByNumRequest)(nil), "grpcpb.GetBlockTransactionsByNumRequest")
	proto.RegisterType((*GetBlockTransactionsByNumResponse)(nil), "grpcpb.GetBlockTransactionsByNumResponse")
	proto.RegisterType((*GetTrxByIdRequest)(nil), "grpcpb.GetTrxByIdRequest")
	proto.RegisterType((*GetTrxByIdResponse)(nil), "grpcpb.GetTrxByIdResponse")
	proto.RegisterType((*BroadcastTrxRequest)(nil), "grpcpb.BroadcastTrxRequest")
	proto.RegisterType((*BroadcastTrxResponse)(nil), "grpcpb.BroadcastTrxResponse")
	proto.RegisterType((*NonParamsRequest)(nil), "grpcpb.NonParamsRequest")
	proto.RegisterType((*CallResponse)(nil), "grpcpb.CallResponse")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 1328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xd7, 0xc6, 0xf9, 0xa8, 0x8f, 0x9d, 0x36, 0xff, 0xf9, 0xa7, 0x8d, 0xb3, 0x49, 0xda, 0x64,
	0xd2, 0x8f, 0x10, 0x20, 0xee, 0x87, 0x00, 0xa9, 0x54, 0x2d, 0x4d, 0x04, 0x51, 0x55, 0x14, 0x95,
	0x25, 0x14, 0x71, 0x81, 0x96, 0xf5, 0xfa, 0xd8, 0x2c, 0x59, 0xef, 0x2e, 0x33, 0xb3, 0x8d, 0xcd,
	0x1d, 0xbc, 0x00, 0x12, 0x45, 0xe2, 0x1a, 0x78, 0x0f, 0x5e, 0x82, 0x4b, 0x6e, 0x79, 0x06, 0xae,
	0xd1, 0xcc, 0xce, 0xda, 0xb3, 0xb1, 0x37, 0x89, 0x44, 0x6e, 0xec, 0x9d, 0x33, 0x67, 0xce, 0xf9,
	0xcd, 0xef, 0xcc, 0xf9, 0x00, 0xe8, 0xb2, 0xc4, 0xdf, 0x49, 0x58, 0x2c, 0x62, 0x32, 0x2b, 0xbf,
	0x93, 0x96, 0xbd, 0xda, 0x8d, 0xe3, 0x6e, 0x88, 0x4d, 0x2f, 0x09, 0x9a, 0x5e, 0x14, 0xc5, 0xc2,
	0x13, 0x41, 0x1c, 0xf1, 0x4c, 0xcb, 0x5e, 0x54, 0x7f, 0x62, 0x90, 0x60, 0x53, 0xfe, 0x68, 0xe9,
	0x8a, 0x21, 0x65, 0x5e, 0xc4, 0x3d, 0x5f, 0x9e, 0xc9, 0x36, 0xe9, 0x67, 0xb0, 0xb4, 0x8f, 0xe2,
	0xa9, 0xef, 0xc7, 0x69, 0x24, 0x76, 0x07, 0x07, 0x5e, 0x0f, 0x1d, 0xfc, 0x36, 0x45, 0x2e, 0xc8,
	0x43, 0xa8, 0x7b, 0x99, 0xdc, 0x8d, 0xbc, 0x1e, 0x36, 0xac, 0x75, 0x6b, 0xab, 0x76, 0x7f, 0x69,
	0x67, 0x68, 0x6e, 0xc7, 0xdc, 0x76, 0x6a, 0x7a, 0x25, 0x4d, 0xd0, 0x9f, 0xa6, 0xe0, 0x8a, 0x36,
	0xea, 0x20, 0x4f, 0xe2, 0x88, 0xe3, 0x7f, 0xb1, 0x47, 0x36, 0x61, 0xda, 0x8f, 0x83, 0xa8, 0x31,
	0xa5, 0xce, 0x5c, 0x31, 0xce, 0x48, 0xb1, 0xa3, 0x36, 0xa5, 0xd2, 0x2b, 0xe4, 0xa2, 0x51, 0x19,
	0x53, 0x92, 0x62, 0x47, 0x6d, 0x92, 0xf7, 0xa1, 0x96, 0xa4, 0xad, 0x30, 0xf0, 0xdd, 0x23, 0x1c,
	0xf0, 0xc6, 0xf4, 0x7a, 0x65, 0xab, 0x76, 0xdf, 0x36, 0x74, 0x47, 0xbb, 0xae, 0x5c, 0x3b, 0x90,
	0x09, 0x9e, 0xe3, 0x80, 0x93, 0x47, 0x50, 0xf7, 0x19, 0x7a, 0x02, 0xdb, 0xae, 0x08, 0x7a, 0xd8,
	0x98, 0x51, 0x9e, 0x96, 0x8d, 0xd3, 0x52, 0xec, 0x26, 0x71, 0x10, 0x09, 0x97, 0xa3, 0xef, 0xd4,
	0xb4, 0xfa, 0x61, 0xd0, 0x43, 0xfa, 0xab, 0x05, 0xab, 0xfb, 0x28, 0x3e, 0x8a, 0xc3, 0x30, 0x3e,
	0x46, 0xf6, 0x71, 0xc0, 0x2f, 0x8e, 0x71, 0xd2, 0x84, 0x19, 0x2e, 0x3c, 0x26, 0x34, 0x45, 0x26,
	0xa6, 0x8e, 0x76, 0xe8, 0xc6, 0xac, 0x8d, 0xcc, 0xc9, 0xf4, 0xc8, 0x22, 0xcc, 0x84, 0x41, 0x2f,
	0xc8, 0xe8, 0x9a, 0x77, 0xb2, 0x05, 0xfd, 0x12, 0xd6, 0x4a, 0x20, 0xea, 0x28, 0x3e, 0x82, 0xf9,
	0xa1, 0xbd, 0x30, 0xe0, 0xa2, 0x61, 0x29, 0x06, 0x4b, 0x41, 0xd6, 0x3b, 0x86, 0x2d, 0xfa, 0xbb,
	0x65, 0xd8, 0x0f, 0xa2, 0xee, 0xc5, 0x72, 0x70, 0xb7, 0xc8, 0x81, 0x3d, 0xc6, 0x41, 0x10, 0x75,
	0xcf, 0x43, 0xc2, 0x57, 0x70, 0xbd, 0x0c, 0xa4, 0x66, 0xe1, 0x31, 0x5c, 0x1e, 0x59, 0x3c, 0x0f,
	0x0d, 0xf3, 0x1d, 0xd3, 0x1a, 0xfd, 0x02, 0x56, 0x86, 0x1e, 0xf6, 0x2e, 0x36, 0xf5, 0x1c, 0xe3,
	0x91, 0x15, 0x4c, 0x6b, 0xe8, 0x4b, 0x30, 0xd7, 0x41, 0xe6, 0xfa, 0x91, 0x50, 0x66, 0xe7, 0x9d,
	0xd9, 0x0e, 0xb2, 0xbd, 0x48, 0x90, 0x65, 0xb8, 0xd4, 0x91, 0xd7, 0x91, 0x3b, 0x53, 0x6a, 0x67,
	0x4e, 0xae, 0xf7, 0x22, 0x41, 0xff, 0xb1, 0xe0, 0xca, 0xe7, 0x81, 0x88, 0x90, 0xf3, 0x0b, 0x49,
	0xe7, 0x07, 0x30, 0xa7, 0x13, 0x63, 0xc2, 0x73, 0x3d, 0x91, 0x42, 0xb9, 0x26, 0x59, 0x80, 0x4a,
	0xca, 0x42, 0x15, 0xa9, 0xaa, 0x23, 0x3f, 0x65, 0x2e, 0xf3, 0xa0, 0x1b, 0x49, 0xd0, 0x47, 0x38,
	0x68, 0x4c, 0x8f, 0x45, 0x7d, 0x2c, 0x97, 0xb5, 0xfa, 0x73, 0x1c, 0x90, 0x4d, 0x98, 0xe7, 0xfe,
	0xd7, 0xd8, 0x4e, 0x43, 0x54, 0x9b, 0x2a, 0x99, 0xe7, 0x9d, 0x7a, 0x2e, 0x3c, 0x1c, 0x24, 0x48,
	0x9f, 0xc0, 0xd5, 0x7d, 0x14, 0xfa, 0xea, 0x32, 0x72, 0x79, 0x84, 0x08, 0x4c, 0x27, 0x5e, 0x17,
	0x35, 0x85, 0xea, 0x5b, 0xca, 0x78, 0xf0, 0x1d, 0x6a, 0xf2, 0xd4, 0x37, 0x3d, 0x84, 0x6b, 0x27,
	0x0d, 0x8c, 0xf8, 0x3b, 0xce, 0xc4, 0xc5, 0x07, 0x94, 0x55, 0xfa, 0x9d, 0x13, 0x74, 0x3b, 0xb5,
	0xe3, 0x91, 0x0d, 0xfa, 0x87, 0x05, 0xf5, 0x17, 0xb1, 0x61, 0x6c, 0x01, 0x2a, 0x41, 0xbb, 0xaf,
	0xd1, 0xc8, 0x4f, 0xf2, 0x26, 0x4c, 0xab, 0xb0, 0x4c, 0x9d, 0x1e, 0x16, 0xa5, 0x44, 0xde, 0x85,
	0x6a, 0x12, 0x73, 0x91, 0x15, 0xb5, 0xca, 0x59, 0x11, 0xb9, 0x24, 0x75, 0x65, 0x45, 0x23, 0x0d,
	0x98, 0xf3, 0xe3, 0x48, 0x60, 0x24, 0x14, 0xf9, 0x55, 0x27, 0x5f, 0x92, 0x35, 0x80, 0x30, 0x38,
	0x42, 0x57, 0xb9, 0xd2, 0xd4, 0x56, 0xa5, 0x44, 0x3d, 0x49, 0xfa, 0xbd, 0xa5, 0x12, 0x40, 0xde,
	0x21, 0xcb, 0xae, 0xbd, 0x2c, 0xc8, 0x17, 0x51, 0x05, 0xf2, 0xd0, 0x4c, 0x4d, 0x08, 0x4d, 0xc5,
	0x08, 0xcd, 0x27, 0x2a, 0x51, 0x26, 0x40, 0xd0, 0x9c, 0xde, 0xd3, 0xa4, 0x18, 0xd1, 0x59, 0xcc,
	0xa3, 0x63, 0x92, 0x9f, 0xf1, 0xa1, 0xe2, 0xf2, 0x9e, 0x32, 0xe9, 0x60, 0x12, 0x7a, 0x83, 0xcc,
	0xa8, 0x54, 0x7c, 0x36, 0xbc, 0xd6, 0x12, 0xcc, 0x29, 0x93, 0x41, 0x3b, 0xcf, 0xbd, 0x44, 0xed,
	0xd3, 0x97, 0xaa, 0x2c, 0x4e, 0x3a, 0xa8, 0xc1, 0xbc, 0x03, 0x35, 0xa6, 0x76, 0xcf, 0x86, 0x03,
	0x6c, 0x68, 0x86, 0x76, 0x61, 0x7d, 0x1f, 0xc5, 0x6e, 0x18, 0xfb, 0x47, 0x87, 0xa3, 0xde, 0xcf,
	0x77, 0x07, 0x07, 0x69, 0x2f, 0x07, 0xb5, 0x02, 0xd5, 0x96, 0x54, 0x70, 0xa3, 0xb4, 0xa7, 0x61,
	0x5d, 0x52, 0x82, 0x83, 0xb4, 0x77, 0x6e, 0x32, 0x3b, 0xb0, 0x71, 0x8a, 0x23, 0x7d, 0x89, 0xa7,
	0x50, 0x37, 0x26, 0x10, 0xae, 0x6f, 0xb1, 0x66, 0x44, 0x55, 0xe6, 0xa7, 0x6c, 0xae, 0x23, 0x2d,
	0xa7, 0x70, 0x84, 0x6e, 0xc3, 0xff, 0xf6, 0x51, 0x1c, 0xb2, 0xfe, 0xee, 0x60, 0x44, 0xeb, 0x55,
	0x98, 0x15, 0xac, 0x9f, 0xb3, 0x3a, 0xed, 0xcc, 0x08, 0xd6, 0x7f, 0xd6, 0xa6, 0x8f, 0x81, 0x98,
	0xba, 0x1a, 0xc4, 0x16, 0x54, 0x04, 0xeb, 0xeb, 0x17, 0x75, 0xcd, 0x7c, 0xe5, 0x86, 0x53, 0xa9,
	0x42, 0x5f, 0xc2, 0xff, 0x77, 0x59, 0xec, 0xb5, 0x7d, 0x8f, 0x4b, 0x2b, 0xb9, 0xb7, 0x27, 0x50,
	0x33, 0x54, 0xb5, 0xa1, 0x33, 0x2e, 0x61, 0x9e, 0xa0, 0x1f, 0xc0, 0x62, 0xd1, 0xae, 0x46, 0x76,
	0x0d, 0x66, 0xb9, 0xf0, 0x44, 0xca, 0xf3, 0xc7, 0x91, 0xad, 0x64, 0x72, 0xf7, 0x78, 0x57, 0x85,
	0xa0, 0xea, 0xc8, 0x4f, 0x4a, 0x60, 0xe1, 0x20, 0x8e, 0x5e, 0x78, 0xcc, 0xeb, 0x71, 0x0d, 0x8b,
	0x7e, 0x03, 0xf5, 0x3d, 0x2f, 0x0c, 0x4d, 0x6b, 0x0c, 0x79, 0x1a, 0x66, 0x65, 0xbe, 0xea, 0xe8,
	0x15, 0xb9, 0x01, 0x35, 0xec, 0xa3, 0x9f, 0x0a, 0x74, 0x91, 0x31, 0x6d, 0x15, 0xb4, 0xe8, 0x43,
	0xc6, 0xc8, 0x06, 0xd4, 0x91, 0x8b, 0xa0, 0xe7, 0x09, 0x74, 0xbb, 0x1e, 0xd7, 0x05, 0xb7, 0x96,
	0xcb, 0xf6, 0x3d, 0x7e, 0xff, 0x2f, 0x00, 0x78, 0x9a, 0x04, 0x9f, 0x22, 0x7b, 0x15, 0xf8, 0x48,
	0x52, 0x58, 0x38, 0x39, 0x44, 0x92, 0x1b, 0xf9, 0xdb, 0x2c, 0x19, 0x2f, 0xed, 0x61, 0xa5, 0x3b,
	0x31, 0x27, 0xd2, 0x3b, 0x3f, 0xfc, 0xf9, 0xf7, 0xeb, 0xa9, 0x0d, 0xba, 0xda, 0x7c, 0x75, 0xaf,
	0x99, 0x72, 0x64, 0xcd, 0x2e, 0x0a, 0x37, 0xcf, 0xf7, 0xd6, 0x40, 0xa5, 0xfc, 0x43, 0x6b, 0x9b,
	0xbc, 0xb6, 0x54, 0x75, 0x1e, 0x1f, 0x56, 0xc8, 0x4d, 0xc3, 0x79, 0xe9, 0xb8, 0x65, 0xdf, 0x3a,
	0x43, 0x4b, 0xe3, 0x79, 0x5b, 0xe1, 0xb9, 0x43, 0x69, 0x01, 0x4f, 0x61, 0x08, 0x32, 0x51, 0xfd,
	0x62, 0xa9, 0x92, 0x3f, 0x61, 0x7a, 0x20, 0xe3, 0x0e, 0x27, 0x8d, 0x40, 0xf6, 0xed, 0xb3, 0xd4,
	0x34, 0xb0, 0x1d, 0x05, 0x6c, 0x8b, 0x6e, 0x4e, 0x00, 0x96, 0xcf, 0x25, 0x26, 0xb2, 0x1f, 0x2d,
	0x58, 0x9c, 0x34, 0x1a, 0x90, 0xcd, 0x31, 0x87, 0xe3, 0x33, 0x89, 0x7d, 0xf3, 0x74, 0x25, 0x8d,
	0xe9, 0x2d, 0x85, 0xe9, 0x36, 0xdd, 0x98, 0x80, 0xc9, 0x1d, 0x8b, 0x20, 0x83, 0xcb, 0xc5, 0xee,
	0x48, 0xd6, 0x0c, 0x2f, 0xe3, 0x6d, 0xd7, 0xbe, 0x5e, 0xb6, 0xad, 0xdd, 0x6f, 0x28, 0xf7, 0x2b,
	0x64, 0xb9, 0xe0, 0xde, 0xec, 0xb3, 0x39, 0x0b, 0x63, 0x75, 0xbf, 0xc0, 0x42, 0x59, 0x63, 0x2a,
	0xb0, 0x50, 0xda, 0x3a, 0x8a, 0x2c, 0xc8, 0x12, 0xaf, 0x60, 0x0c, 0xbb, 0x89, 0xa4, 0x40, 0x4f,
	0x35, 0x92, 0x85, 0x9f, 0xb3, 0x77, 0x3c, 0x5e, 0xfd, 0x0b, 0xef, 0xb8, 0xb4, 0xab, 0x14, 0xde,
	0x71, 0x79, 0x0b, 0x29, 0x3e, 0x97, 0x21, 0x28, 0xa3, 0xab, 0x48, 0x58, 0xba, 0x3d, 0x49, 0x58,
	0xbf, 0x59, 0xb0, 0x5c, 0x5a, 0xd3, 0xc9, 0x96, 0xe1, 0xf4, 0xd4, 0xfe, 0x62, 0xbf, 0x71, 0x0e,
	0x4d, 0x0d, 0xf1, 0xae, 0x82, 0xb8, 0x4d, 0x6f, 0x49, 0x88, 0x82, 0xf5, 0x15, 0xc2, 0xac, 0x39,
	0x99, 0x5d, 0x40, 0x3d, 0xa1, 0xb4, 0x27, 0x41, 0x22, 0xc0, 0xa8, 0xc6, 0x93, 0x65, 0xc3, 0x55,
	0xb1, 0x47, 0xd8, 0xf6, 0xa4, 0x2d, 0xed, 0x76, 0x5d, 0xb9, 0xb5, 0xe9, 0x55, 0xd3, 0xad, 0xec,
	0x28, 0xad, 0x81, 0xe6, 0xe2, 0x08, 0xea, 0x66, 0xc9, 0x26, 0x2b, 0xb9, 0xb5, 0x09, 0x0d, 0xc2,
	0x5e, 0x9d, 0xbc, 0x59, 0xe6, 0xac, 0x95, 0x6b, 0x49, 0x97, 0x0f, 0xad, 0xed, 0xd6, 0xac, 0x6a,
	0x25, 0x0f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xe0, 0xa1, 0x0c, 0x01, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServiceClient interface {
	GetAccountByName(ctx context.Context, in *GetAccountByNameRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetFollowerListByName(ctx context.Context, in *GetFollowerListByNameRequest, opts ...grpc.CallOption) (*GetFollowerListByNameResponse, error)
	GetFollowingListByName(ctx context.Context, in *GetFollowingListByNameRequest, opts ...grpc.CallOption) (*GetFollowingListByNameResponse, error)
	GetFollowCountByName(ctx context.Context, in *GetFollowCountByNameRequest, opts ...grpc.CallOption) (*GetFollowCountByNameResponse, error)
	GetWitnessList(ctx context.Context, in *GetWitnessListRequest, opts ...grpc.CallOption) (*GetWitnessListResponse, error)
	GetPostListByCreated(ctx context.Context, in *GetPostListByCreatedRequest, opts ...grpc.CallOption) (*GetPostListByCreatedResponse, error)
	GetReplayListByPostId(ctx context.Context, in *GetReplayListByPostIdRequest, opts ...grpc.CallOption) (*GetReplayListByPostIdResponse, error)
	GetBlockTransactionsByNum(ctx context.Context, in *GetBlockTransactionsByNumRequest, opts ...grpc.CallOption) (*GetBlockTransactionsByNumResponse, error)
	GetTrxById(ctx context.Context, in *GetTrxByIdRequest, opts ...grpc.CallOption) (*GetTrxByIdResponse, error)
	BroadcastTrx(ctx context.Context, in *BroadcastTrxRequest, opts ...grpc.CallOption) (*BroadcastTrxResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetAccountByName(ctx context.Context, in *GetAccountByNameRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetAccountByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetFollowerListByName(ctx context.Context, in *GetFollowerListByNameRequest, opts ...grpc.CallOption) (*GetFollowerListByNameResponse, error) {
	out := new(GetFollowerListByNameResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetFollowerListByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetFollowingListByName(ctx context.Context, in *GetFollowingListByNameRequest, opts ...grpc.CallOption) (*GetFollowingListByNameResponse, error) {
	out := new(GetFollowingListByNameResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetFollowingListByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetFollowCountByName(ctx context.Context, in *GetFollowCountByNameRequest, opts ...grpc.CallOption) (*GetFollowCountByNameResponse, error) {
	out := new(GetFollowCountByNameResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetFollowCountByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetWitnessList(ctx context.Context, in *GetWitnessListRequest, opts ...grpc.CallOption) (*GetWitnessListResponse, error) {
	out := new(GetWitnessListResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetWitnessList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetPostListByCreated(ctx context.Context, in *GetPostListByCreatedRequest, opts ...grpc.CallOption) (*GetPostListByCreatedResponse, error) {
	out := new(GetPostListByCreatedResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetPostListByCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetReplayListByPostId(ctx context.Context, in *GetReplayListByPostIdRequest, opts ...grpc.CallOption) (*GetReplayListByPostIdResponse, error) {
	out := new(GetReplayListByPostIdResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetReplayListByPostId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetBlockTransactionsByNum(ctx context.Context, in *GetBlockTransactionsByNumRequest, opts ...grpc.CallOption) (*GetBlockTransactionsByNumResponse, error) {
	out := new(GetBlockTransactionsByNumResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetBlockTransactionsByNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetTrxById(ctx context.Context, in *GetTrxByIdRequest, opts ...grpc.CallOption) (*GetTrxByIdResponse, error) {
	out := new(GetTrxByIdResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/GetTrxById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) BroadcastTrx(ctx context.Context, in *BroadcastTrxRequest, opts ...grpc.CallOption) (*BroadcastTrxResponse, error) {
	out := new(BroadcastTrxResponse)
	err := c.cc.Invoke(ctx, "/grpcpb.ApiService/BroadcastTrx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
type ApiServiceServer interface {
	GetAccountByName(context.Context, *GetAccountByNameRequest) (*AccountResponse, error)
	GetFollowerListByName(context.Context, *GetFollowerListByNameRequest) (*GetFollowerListByNameResponse, error)
	GetFollowingListByName(context.Context, *GetFollowingListByNameRequest) (*GetFollowingListByNameResponse, error)
	GetFollowCountByName(context.Context, *GetFollowCountByNameRequest) (*GetFollowCountByNameResponse, error)
	GetWitnessList(context.Context, *GetWitnessListRequest) (*GetWitnessListResponse, error)
	GetPostListByCreated(context.Context, *GetPostListByCreatedRequest) (*GetPostListByCreatedResponse, error)
	GetReplayListByPostId(context.Context, *GetReplayListByPostIdRequest) (*GetReplayListByPostIdResponse, error)
	GetBlockTransactionsByNum(context.Context, *GetBlockTransactionsByNumRequest) (*GetBlockTransactionsByNumResponse, error)
	GetTrxById(context.Context, *GetTrxByIdRequest) (*GetTrxByIdResponse, error)
	BroadcastTrx(context.Context, *BroadcastTrxRequest) (*BroadcastTrxResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetAccountByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAccountByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetAccountByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAccountByName(ctx, req.(*GetAccountByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetFollowerListByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowerListByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetFollowerListByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetFollowerListByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetFollowerListByName(ctx, req.(*GetFollowerListByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetFollowingListByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingListByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetFollowingListByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetFollowingListByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetFollowingListByName(ctx, req.(*GetFollowingListByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetFollowCountByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowCountByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetFollowCountByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetFollowCountByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetFollowCountByName(ctx, req.(*GetFollowCountByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetWitnessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWitnessListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetWitnessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetWitnessList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetWitnessList(ctx, req.(*GetWitnessListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetPostListByCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostListByCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetPostListByCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetPostListByCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetPostListByCreated(ctx, req.(*GetPostListByCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetReplayListByPostId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplayListByPostIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetReplayListByPostId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetReplayListByPostId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetReplayListByPostId(ctx, req.(*GetReplayListByPostIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetBlockTransactionsByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockTransactionsByNumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetBlockTransactionsByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetBlockTransactionsByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetBlockTransactionsByNum(ctx, req.(*GetBlockTransactionsByNumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetTrxById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrxByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetTrxById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/GetTrxById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetTrxById(ctx, req.(*GetTrxByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_BroadcastTrx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTrxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).BroadcastTrx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcpb.ApiService/BroadcastTrx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).BroadcastTrx(ctx, req.(*BroadcastTrxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcpb.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountByName",
			Handler:    _ApiService_GetAccountByName_Handler,
		},
		{
			MethodName: "GetFollowerListByName",
			Handler:    _ApiService_GetFollowerListByName_Handler,
		},
		{
			MethodName: "GetFollowingListByName",
			Handler:    _ApiService_GetFollowingListByName_Handler,
		},
		{
			MethodName: "GetFollowCountByName",
			Handler:    _ApiService_GetFollowCountByName_Handler,
		},
		{
			MethodName: "GetWitnessList",
			Handler:    _ApiService_GetWitnessList_Handler,
		},
		{
			MethodName: "GetPostListByCreated",
			Handler:    _ApiService_GetPostListByCreated_Handler,
		},
		{
			MethodName: "GetReplayListByPostId",
			Handler:    _ApiService_GetReplayListByPostId_Handler,
		},
		{
			MethodName: "GetBlockTransactionsByNum",
			Handler:    _ApiService_GetBlockTransactionsByNum_Handler,
		},
		{
			MethodName: "GetTrxById",
			Handler:    _ApiService_GetTrxById_Handler,
		},
		{
			MethodName: "BroadcastTrx",
			Handler:    _ApiService_BroadcastTrx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
