// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prototype/operation.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountCreateOperation struct {
	Fee                  *Coin          `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	Creator              *AccountName   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	NewAccountName       *AccountName   `protobuf:"bytes,3,opt,name=new_account_name,json=newAccountName,proto3" json:"new_account_name,omitempty"`
	Owner                *Authority     `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Active               *Authority     `protobuf:"bytes,5,opt,name=active,proto3" json:"active,omitempty"`
	Posting              *Authority     `protobuf:"bytes,6,opt,name=posting,proto3" json:"posting,omitempty"`
	MemoKey              *PublicKeyType `protobuf:"bytes,7,opt,name=memo_key,json=memoKey,proto3" json:"memo_key,omitempty"`
	JsonMetadata         string         `protobuf:"bytes,8,opt,name=json_metadata,json=jsonMetadata,proto3" json:"json_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccountCreateOperation) Reset()         { *m = AccountCreateOperation{} }
func (m *AccountCreateOperation) String() string { return proto.CompactTextString(m) }
func (*AccountCreateOperation) ProtoMessage()    {}
func (*AccountCreateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{0}
}

func (m *AccountCreateOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreateOperation.Unmarshal(m, b)
}
func (m *AccountCreateOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreateOperation.Marshal(b, m, deterministic)
}
func (m *AccountCreateOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreateOperation.Merge(m, src)
}
func (m *AccountCreateOperation) XXX_Size() int {
	return xxx_messageInfo_AccountCreateOperation.Size(m)
}
func (m *AccountCreateOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreateOperation.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreateOperation proto.InternalMessageInfo

func (m *AccountCreateOperation) GetFee() *Coin {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *AccountCreateOperation) GetCreator() *AccountName {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *AccountCreateOperation) GetNewAccountName() *AccountName {
	if m != nil {
		return m.NewAccountName
	}
	return nil
}

func (m *AccountCreateOperation) GetOwner() *Authority {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *AccountCreateOperation) GetActive() *Authority {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *AccountCreateOperation) GetPosting() *Authority {
	if m != nil {
		return m.Posting
	}
	return nil
}

func (m *AccountCreateOperation) GetMemoKey() *PublicKeyType {
	if m != nil {
		return m.MemoKey
	}
	return nil
}

func (m *AccountCreateOperation) GetJsonMetadata() string {
	if m != nil {
		return m.JsonMetadata
	}
	return ""
}

type TransferOperation struct {
	From                 *AccountName `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *AccountName `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               *Coin        `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string       `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransferOperation) Reset()         { *m = TransferOperation{} }
func (m *TransferOperation) String() string { return proto.CompactTextString(m) }
func (*TransferOperation) ProtoMessage()    {}
func (*TransferOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{1}
}

func (m *TransferOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferOperation.Unmarshal(m, b)
}
func (m *TransferOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferOperation.Marshal(b, m, deterministic)
}
func (m *TransferOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferOperation.Merge(m, src)
}
func (m *TransferOperation) XXX_Size() int {
	return xxx_messageInfo_TransferOperation.Size(m)
}
func (m *TransferOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TransferOperation proto.InternalMessageInfo

func (m *TransferOperation) GetFrom() *AccountName {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransferOperation) GetTo() *AccountName {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransferOperation) GetAmount() *Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TransferOperation) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type TransferToVestingOperation struct {
	From                 *AccountName `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *AccountName `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               *Coin        `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransferToVestingOperation) Reset()         { *m = TransferToVestingOperation{} }
func (m *TransferToVestingOperation) String() string { return proto.CompactTextString(m) }
func (*TransferToVestingOperation) ProtoMessage()    {}
func (*TransferToVestingOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{2}
}

func (m *TransferToVestingOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferToVestingOperation.Unmarshal(m, b)
}
func (m *TransferToVestingOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferToVestingOperation.Marshal(b, m, deterministic)
}
func (m *TransferToVestingOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferToVestingOperation.Merge(m, src)
}
func (m *TransferToVestingOperation) XXX_Size() int {
	return xxx_messageInfo_TransferToVestingOperation.Size(m)
}
func (m *TransferToVestingOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferToVestingOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TransferToVestingOperation proto.InternalMessageInfo

func (m *TransferToVestingOperation) GetFrom() *AccountName {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransferToVestingOperation) GetTo() *AccountName {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransferToVestingOperation) GetAmount() *Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

type VoteOperation struct {
	Voter                *AccountName `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Idx                  uint64       `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VoteOperation) Reset()         { *m = VoteOperation{} }
func (m *VoteOperation) String() string { return proto.CompactTextString(m) }
func (*VoteOperation) ProtoMessage()    {}
func (*VoteOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{3}
}

func (m *VoteOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteOperation.Unmarshal(m, b)
}
func (m *VoteOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteOperation.Marshal(b, m, deterministic)
}
func (m *VoteOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteOperation.Merge(m, src)
}
func (m *VoteOperation) XXX_Size() int {
	return xxx_messageInfo_VoteOperation.Size(m)
}
func (m *VoteOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteOperation.DiscardUnknown(m)
}

var xxx_messageInfo_VoteOperation proto.InternalMessageInfo

func (m *VoteOperation) GetVoter() *AccountName {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *VoteOperation) GetIdx() uint64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

type BpRegisterOperation struct {
	Owner                *AccountName     `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Url                  string           `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Desc                 string           `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	BlockSigningKey      *PublicKeyType   `protobuf:"bytes,4,opt,name=block_signing_key,json=blockSigningKey,proto3" json:"block_signing_key,omitempty"`
	Props                *ChainProperties `protobuf:"bytes,5,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BpRegisterOperation) Reset()         { *m = BpRegisterOperation{} }
func (m *BpRegisterOperation) String() string { return proto.CompactTextString(m) }
func (*BpRegisterOperation) ProtoMessage()    {}
func (*BpRegisterOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{4}
}

func (m *BpRegisterOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BpRegisterOperation.Unmarshal(m, b)
}
func (m *BpRegisterOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BpRegisterOperation.Marshal(b, m, deterministic)
}
func (m *BpRegisterOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BpRegisterOperation.Merge(m, src)
}
func (m *BpRegisterOperation) XXX_Size() int {
	return xxx_messageInfo_BpRegisterOperation.Size(m)
}
func (m *BpRegisterOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_BpRegisterOperation.DiscardUnknown(m)
}

var xxx_messageInfo_BpRegisterOperation proto.InternalMessageInfo

func (m *BpRegisterOperation) GetOwner() *AccountName {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *BpRegisterOperation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *BpRegisterOperation) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *BpRegisterOperation) GetBlockSigningKey() *PublicKeyType {
	if m != nil {
		return m.BlockSigningKey
	}
	return nil
}

func (m *BpRegisterOperation) GetProps() *ChainProperties {
	if m != nil {
		return m.Props
	}
	return nil
}

type BpUnregisterOperation struct {
	Owner                *AccountName `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BpUnregisterOperation) Reset()         { *m = BpUnregisterOperation{} }
func (m *BpUnregisterOperation) String() string { return proto.CompactTextString(m) }
func (*BpUnregisterOperation) ProtoMessage()    {}
func (*BpUnregisterOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{5}
}

func (m *BpUnregisterOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BpUnregisterOperation.Unmarshal(m, b)
}
func (m *BpUnregisterOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BpUnregisterOperation.Marshal(b, m, deterministic)
}
func (m *BpUnregisterOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BpUnregisterOperation.Merge(m, src)
}
func (m *BpUnregisterOperation) XXX_Size() int {
	return xxx_messageInfo_BpUnregisterOperation.Size(m)
}
func (m *BpUnregisterOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_BpUnregisterOperation.DiscardUnknown(m)
}

var xxx_messageInfo_BpUnregisterOperation proto.InternalMessageInfo

func (m *BpUnregisterOperation) GetOwner() *AccountName {
	if m != nil {
		return m.Owner
	}
	return nil
}

type BpVoteOperation struct {
	Voter                *AccountName `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Witness              *AccountName `protobuf:"bytes,2,opt,name=witness,proto3" json:"witness,omitempty"`
	Cancel               bool         `protobuf:"varint,3,opt,name=cancel,proto3" json:"cancel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BpVoteOperation) Reset()         { *m = BpVoteOperation{} }
func (m *BpVoteOperation) String() string { return proto.CompactTextString(m) }
func (*BpVoteOperation) ProtoMessage()    {}
func (*BpVoteOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{6}
}

func (m *BpVoteOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BpVoteOperation.Unmarshal(m, b)
}
func (m *BpVoteOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BpVoteOperation.Marshal(b, m, deterministic)
}
func (m *BpVoteOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BpVoteOperation.Merge(m, src)
}
func (m *BpVoteOperation) XXX_Size() int {
	return xxx_messageInfo_BpVoteOperation.Size(m)
}
func (m *BpVoteOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_BpVoteOperation.DiscardUnknown(m)
}

var xxx_messageInfo_BpVoteOperation proto.InternalMessageInfo

func (m *BpVoteOperation) GetVoter() *AccountName {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *BpVoteOperation) GetWitness() *AccountName {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *BpVoteOperation) GetCancel() bool {
	if m != nil {
		return m.Cancel
	}
	return false
}

type FollowOperation struct {
	Follower             *AccountName `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Following            *AccountName `protobuf:"bytes,2,opt,name=following,proto3" json:"following,omitempty"`
	Cancel               bool         `protobuf:"varint,3,opt,name=cancel,proto3" json:"cancel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FollowOperation) Reset()         { *m = FollowOperation{} }
func (m *FollowOperation) String() string { return proto.CompactTextString(m) }
func (*FollowOperation) ProtoMessage()    {}
func (*FollowOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{7}
}

func (m *FollowOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowOperation.Unmarshal(m, b)
}
func (m *FollowOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowOperation.Marshal(b, m, deterministic)
}
func (m *FollowOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowOperation.Merge(m, src)
}
func (m *FollowOperation) XXX_Size() int {
	return xxx_messageInfo_FollowOperation.Size(m)
}
func (m *FollowOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowOperation.DiscardUnknown(m)
}

var xxx_messageInfo_FollowOperation proto.InternalMessageInfo

func (m *FollowOperation) GetFollower() *AccountName {
	if m != nil {
		return m.Follower
	}
	return nil
}

func (m *FollowOperation) GetFollowing() *AccountName {
	if m != nil {
		return m.Following
	}
	return nil
}

func (m *FollowOperation) GetCancel() bool {
	if m != nil {
		return m.Cancel
	}
	return false
}

type BeneficiaryRouteType struct {
	Name                 *AccountName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight               uint32       `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BeneficiaryRouteType) Reset()         { *m = BeneficiaryRouteType{} }
func (m *BeneficiaryRouteType) String() string { return proto.CompactTextString(m) }
func (*BeneficiaryRouteType) ProtoMessage()    {}
func (*BeneficiaryRouteType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{8}
}

func (m *BeneficiaryRouteType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeneficiaryRouteType.Unmarshal(m, b)
}
func (m *BeneficiaryRouteType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeneficiaryRouteType.Marshal(b, m, deterministic)
}
func (m *BeneficiaryRouteType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeneficiaryRouteType.Merge(m, src)
}
func (m *BeneficiaryRouteType) XXX_Size() int {
	return xxx_messageInfo_BeneficiaryRouteType.Size(m)
}
func (m *BeneficiaryRouteType) XXX_DiscardUnknown() {
	xxx_messageInfo_BeneficiaryRouteType.DiscardUnknown(m)
}

var xxx_messageInfo_BeneficiaryRouteType proto.InternalMessageInfo

func (m *BeneficiaryRouteType) GetName() *AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BeneficiaryRouteType) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type PostOperation struct {
	Uuid                 string                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Owner                *AccountName            `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Title                string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string                  `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Tags                 []string                `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Beneficiaries        []*BeneficiaryRouteType `protobuf:"bytes,6,rep,name=beneficiaries,proto3" json:"beneficiaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PostOperation) Reset()         { *m = PostOperation{} }
func (m *PostOperation) String() string { return proto.CompactTextString(m) }
func (*PostOperation) ProtoMessage()    {}
func (*PostOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{9}
}

func (m *PostOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOperation.Unmarshal(m, b)
}
func (m *PostOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOperation.Marshal(b, m, deterministic)
}
func (m *PostOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOperation.Merge(m, src)
}
func (m *PostOperation) XXX_Size() int {
	return xxx_messageInfo_PostOperation.Size(m)
}
func (m *PostOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOperation.DiscardUnknown(m)
}

var xxx_messageInfo_PostOperation proto.InternalMessageInfo

func (m *PostOperation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PostOperation) GetOwner() *AccountName {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *PostOperation) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostOperation) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostOperation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PostOperation) GetBeneficiaries() []*BeneficiaryRouteType {
	if m != nil {
		return m.Beneficiaries
	}
	return nil
}

type ReplyOperation struct {
	Uuid                 string                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Owner                *AccountName            `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Content              string                  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentUuid           string                  `protobuf:"bytes,4,opt,name=parent_uuid,json=parentUuid,proto3" json:"parent_uuid,omitempty"`
	Beneficiaries        []*BeneficiaryRouteType `protobuf:"bytes,6,rep,name=beneficiaries,proto3" json:"beneficiaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ReplyOperation) Reset()         { *m = ReplyOperation{} }
func (m *ReplyOperation) String() string { return proto.CompactTextString(m) }
func (*ReplyOperation) ProtoMessage()    {}
func (*ReplyOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c964c0e078f560bc, []int{10}
}

func (m *ReplyOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyOperation.Unmarshal(m, b)
}
func (m *ReplyOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyOperation.Marshal(b, m, deterministic)
}
func (m *ReplyOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyOperation.Merge(m, src)
}
func (m *ReplyOperation) XXX_Size() int {
	return xxx_messageInfo_ReplyOperation.Size(m)
}
func (m *ReplyOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyOperation proto.InternalMessageInfo

func (m *ReplyOperation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ReplyOperation) GetOwner() *AccountName {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ReplyOperation) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReplyOperation) GetParentUuid() string {
	if m != nil {
		return m.ParentUuid
	}
	return ""
}

func (m *ReplyOperation) GetBeneficiaries() []*BeneficiaryRouteType {
	if m != nil {
		return m.Beneficiaries
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountCreateOperation)(nil), "prototype.account_create_operation")
	proto.RegisterType((*TransferOperation)(nil), "prototype.transfer_operation")
	proto.RegisterType((*TransferToVestingOperation)(nil), "prototype.transfer_to_vesting_operation")
	proto.RegisterType((*VoteOperation)(nil), "prototype.vote_operation")
	proto.RegisterType((*BpRegisterOperation)(nil), "prototype.bp_register_operation")
	proto.RegisterType((*BpUnregisterOperation)(nil), "prototype.bp_unregister_operation")
	proto.RegisterType((*BpVoteOperation)(nil), "prototype.bp_vote_operation")
	proto.RegisterType((*FollowOperation)(nil), "prototype.follow_operation")
	proto.RegisterType((*BeneficiaryRouteType)(nil), "prototype.beneficiary_route_type")
	proto.RegisterType((*PostOperation)(nil), "prototype.post_operation")
	proto.RegisterType((*ReplyOperation)(nil), "prototype.reply_operation")
}

func init() { proto.RegisterFile("prototype/operation.proto", fileDescriptor_c964c0e078f560bc) }

var fileDescriptor_c964c0e078f560bc = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x6e, 0xd3, 0x4e,
	0x10, 0x97, 0xe3, 0x7c, 0x4e, 0xff, 0x6d, 0xd3, 0x55, 0xff, 0xad, 0x29, 0x42, 0xb4, 0xe6, 0xd0,
	0xaa, 0xb4, 0x89, 0xda, 0xaa, 0x0f, 0x50, 0x0e, 0x80, 0x84, 0x40, 0xc2, 0x88, 0x0b, 0x12, 0xb2,
	0xd6, 0xce, 0x24, 0x59, 0x6a, 0xef, 0x5a, 0xeb, 0x75, 0x43, 0x1e, 0x82, 0x2b, 0x12, 0x17, 0xae,
	0xbc, 0x12, 0x47, 0x6e, 0xbc, 0x06, 0xda, 0xb5, 0x93, 0x38, 0x82, 0xd6, 0x48, 0xed, 0x81, 0xcb,
	0x6a, 0x76, 0xe6, 0x37, 0x1f, 0xbf, 0x99, 0xd9, 0x85, 0x7b, 0x89, 0x14, 0x4a, 0xa8, 0x69, 0x82,
	0x7d, 0x91, 0xa0, 0xa4, 0x8a, 0x09, 0xde, 0x33, 0x3a, 0xd2, 0x99, 0x9b, 0x76, 0x36, 0x17, 0x28,
	0x7d, 0xe4, 0x00, 0xf7, 0x8b, 0x0d, 0x0e, 0x0d, 0x43, 0x91, 0x71, 0xe5, 0x87, 0x12, 0xa9, 0x42,
	0x7f, 0x1e, 0x83, 0xec, 0x81, 0x3d, 0x44, 0x74, 0xac, 0x5d, 0xeb, 0x60, 0xe5, 0x74, 0xbd, 0x37,
	0x0f, 0xd0, 0x0b, 0x05, 0xe3, 0x9e, 0xb6, 0x91, 0x13, 0x68, 0x19, 0x37, 0x21, 0x9d, 0x9a, 0x81,
	0x6d, 0x97, 0x60, 0xb3, 0xc0, 0x9c, 0xc6, 0xe8, 0xcd, 0x70, 0xe4, 0x02, 0xba, 0x1c, 0x27, 0x7e,
	0xd9, 0xe8, 0xd8, 0x37, 0xfb, 0xae, 0x71, 0x9c, 0x5c, 0xe4, 0x8a, 0x57, 0x34, 0x46, 0x72, 0x08,
	0x0d, 0x31, 0xe1, 0x28, 0x9d, 0xba, 0xf1, 0xdb, 0x2c, 0xfb, 0x65, 0x6a, 0x2c, 0x24, 0x53, 0x53,
	0x2f, 0x87, 0x90, 0x23, 0x68, 0xd2, 0x50, 0xb1, 0x2b, 0x74, 0x1a, 0x37, 0x80, 0x0b, 0x0c, 0xe9,
	0x41, 0x2b, 0x11, 0xa9, 0x62, 0x7c, 0xe4, 0x34, 0x6f, 0x80, 0xcf, 0x40, 0xe4, 0x1c, 0xda, 0x31,
	0xc6, 0xc2, 0xbf, 0xc4, 0xa9, 0xd3, 0x32, 0x0e, 0x3b, 0x25, 0x87, 0x24, 0x0b, 0x22, 0x16, 0x6a,
	0xa3, 0xaf, 0xef, 0x5e, 0x4b, 0x63, 0x5f, 0xe0, 0x94, 0x3c, 0x82, 0xd5, 0x0f, 0xa9, 0xe0, 0x7e,
	0x8c, 0x8a, 0x0e, 0xa8, 0xa2, 0x4e, 0x7b, 0xd7, 0x3a, 0xe8, 0x78, 0xff, 0x69, 0xe5, 0xcb, 0x42,
	0xe7, 0x7e, 0xb3, 0x80, 0x28, 0x49, 0x79, 0x3a, 0x44, 0x59, 0x9a, 0xca, 0x63, 0xa8, 0x0f, 0xa5,
	0x88, 0x8b, 0xb1, 0x5c, 0xdb, 0x33, 0x03, 0x22, 0xfb, 0x50, 0x53, 0xa2, 0x6a, 0x34, 0x35, 0x25,
	0xc8, 0x3e, 0x34, 0x69, 0xac, 0x55, 0xc5, 0x2c, 0x7e, 0x1b, 0x77, 0x61, 0x26, 0x04, 0xea, 0x9a,
	0x85, 0x69, 0x7d, 0xc7, 0x33, 0xb2, 0xfb, 0xd5, 0x82, 0x07, 0xf3, 0x4a, 0x95, 0xf0, 0xaf, 0xd0,
	0x74, 0xe7, 0x9f, 0x29, 0xda, 0x7d, 0x0d, 0x6b, 0x57, 0x62, 0x69, 0xb7, 0x8f, 0xa1, 0xa1, 0x35,
	0xb2, 0xaa, 0xa2, 0x1c, 0x45, 0xba, 0x60, 0xb3, 0xc1, 0x47, 0x93, 0xa6, 0xee, 0x69, 0xd1, 0xfd,
	0x69, 0xc1, 0xff, 0x41, 0xe2, 0x4b, 0x1c, 0xb1, 0x54, 0x2d, 0x0d, 0xe8, 0x78, 0xb6, 0x9d, 0x55,
	0xa1, 0xf3, 0x05, 0xed, 0x82, 0x9d, 0xc9, 0xc8, 0xd0, 0xed, 0x78, 0x5a, 0xd4, 0x2d, 0x1e, 0x60,
	0x1a, 0x9a, 0x6c, 0x1d, 0xcf, 0xc8, 0xe4, 0x29, 0x6c, 0x04, 0x91, 0x08, 0x2f, 0xfd, 0x94, 0x8d,
	0xb8, 0xee, 0xad, 0xde, 0xb8, 0x7a, 0xe5, 0xc6, 0xad, 0x1b, 0xa7, 0x37, 0xb9, 0x8f, 0xde, 0xbc,
	0x13, 0x68, 0x24, 0x52, 0x24, 0x69, 0xf1, 0x1a, 0xee, 0x97, 0x3b, 0x36, 0xa6, 0x8c, 0xfb, 0xda,
	0x8a, 0x52, 0x31, 0x4c, 0xbd, 0x1c, 0xe9, 0x3e, 0x87, 0xed, 0x20, 0xf1, 0x33, 0x7e, 0x6b, 0xaa,
	0xee, 0x27, 0x0b, 0x36, 0x82, 0xc4, 0xbf, 0xdd, 0x28, 0x4e, 0xa0, 0x35, 0x61, 0x8a, 0x63, 0x9a,
	0x56, 0x7e, 0x39, 0x05, 0x8e, 0x6c, 0x41, 0x33, 0xa4, 0x3c, 0xc4, 0xc8, 0xb4, 0xb4, 0xed, 0x15,
	0x37, 0xf7, 0xb3, 0x05, 0xdd, 0xa1, 0x88, 0x22, 0x31, 0x29, 0x95, 0x73, 0x06, 0xed, 0x5c, 0x57,
	0x5d, 0xd1, 0x1c, 0x48, 0xce, 0xa1, 0x93, 0xcb, 0xfa, 0xe7, 0xa8, 0x28, 0x6b, 0x81, 0xbc, 0xb6,
	0xb0, 0xf7, 0xb0, 0x15, 0x20, 0xc7, 0x21, 0x0b, 0x19, 0x95, 0x53, 0x5f, 0x8a, 0x4c, 0xa1, 0x19,
	0xa8, 0x7e, 0x48, 0xe6, 0xc7, 0xac, 0x7a, 0x48, 0xfa, 0xd4, 0xe1, 0x27, 0xc8, 0x46, 0x63, 0x65,
	0x4a, 0x5a, 0xf5, 0x8a, 0x9b, 0xfb, 0xc3, 0x82, 0x35, 0xfd, 0x83, 0x95, 0x58, 0x13, 0xa8, 0x67,
	0x19, 0x1b, 0x98, 0xb8, 0x1d, 0xcf, 0xc8, 0x8b, 0xe9, 0xd6, 0xfe, 0x6a, 0x91, 0x37, 0xa1, 0xa1,
	0x98, 0x8a, 0xb0, 0xd8, 0xdb, 0xfc, 0x42, 0x1c, 0x68, 0x85, 0x82, 0x2b, 0xe4, 0xaa, 0xf8, 0x32,
	0x66, 0x57, 0x9d, 0x52, 0xd1, 0x91, 0xde, 0x44, 0x5b, 0xa7, 0xd4, 0x32, 0x79, 0x06, 0xab, 0x0b,
	0xe2, 0x0c, 0x53, 0xa7, 0xb9, 0x6b, 0x1f, 0xac, 0x9c, 0xee, 0x95, 0x52, 0xff, 0xb9, 0x31, 0xde,
	0xb2, 0x9f, 0xfb, 0xdd, 0x82, 0x75, 0x89, 0x49, 0x34, 0xbd, 0x5b, 0x8e, 0x25, 0x36, 0xf6, 0x32,
	0x9b, 0x87, 0xb0, 0x92, 0x50, 0x89, 0x5c, 0xf9, 0x26, 0x47, 0xce, 0x15, 0x72, 0xd5, 0x5b, 0x9d,
	0xe9, 0xae, 0xa8, 0x3d, 0x39, 0x7a, 0x77, 0x38, 0x62, 0x6a, 0x9c, 0x05, 0xbd, 0x50, 0xc4, 0xfd,
	0x50, 0xa4, 0xe6, 0xe1, 0xf6, 0x8b, 0x42, 0x44, 0x7a, 0x3c, 0x12, 0xfd, 0x79, 0xcc, 0xa0, 0x69,
	0xc4, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x32, 0xc8, 0xaa, 0x26, 0x08, 0x00, 0x00,
}
