// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthorityClassification int32

const (
	Authority_owner   AuthorityClassification = 0
	Authority_active  AuthorityClassification = 1
	Authority_key     AuthorityClassification = 2
	Authority_posting AuthorityClassification = 3
)

var AuthorityClassification_name = map[int32]string{
	0: "owner",
	1: "active",
	2: "key",
	3: "posting",
}

var AuthorityClassification_value = map[string]int32{
	"owner":   0,
	"active":  1,
	"key":     2,
	"posting": 3,
}

func (x AuthorityClassification) String() string {
	return proto.EnumName(AuthorityClassification_name, int32(x))
}

func (AuthorityClassification) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{9, 0}
}

type WitnessScheduleTypeWitnessScheduleType int32

const (
	WitnessScheduleType_top19     WitnessScheduleTypeWitnessScheduleType = 0
	WitnessScheduleType_timeshare WitnessScheduleTypeWitnessScheduleType = 1
	WitnessScheduleType_miner     WitnessScheduleTypeWitnessScheduleType = 2
	WitnessScheduleType_none      WitnessScheduleTypeWitnessScheduleType = 3
)

var WitnessScheduleTypeWitnessScheduleType_name = map[int32]string{
	0: "top19",
	1: "timeshare",
	2: "miner",
	3: "none",
}

var WitnessScheduleTypeWitnessScheduleType_value = map[string]int32{
	"top19":     0,
	"timeshare": 1,
	"miner":     2,
	"none":      3,
}

func (x WitnessScheduleTypeWitnessScheduleType) String() string {
	return proto.EnumName(WitnessScheduleTypeWitnessScheduleType_name, int32(x))
}

func (WitnessScheduleTypeWitnessScheduleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{16, 0}
}

type AccountName struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountName) Reset()         { *m = AccountName{} }
func (m *AccountName) String() string { return proto.CompactTextString(m) }
func (*AccountName) ProtoMessage()    {}
func (*AccountName) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *AccountName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountName.Unmarshal(m, b)
}
func (m *AccountName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountName.Marshal(b, m, deterministic)
}
func (m *AccountName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountName.Merge(m, src)
}
func (m *AccountName) XXX_Size() int {
	return xxx_messageInfo_AccountName.Size(m)
}
func (m *AccountName) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountName.DiscardUnknown(m)
}

var xxx_messageInfo_AccountName proto.InternalMessageInfo

func (m *AccountName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ChainId struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainId) Reset()         { *m = ChainId{} }
func (m *ChainId) String() string { return proto.CompactTextString(m) }
func (*ChainId) ProtoMessage()    {}
func (*ChainId) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1}
}

func (m *ChainId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainId.Unmarshal(m, b)
}
func (m *ChainId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainId.Marshal(b, m, deterministic)
}
func (m *ChainId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainId.Merge(m, src)
}
func (m *ChainId) XXX_Size() int {
	return xxx_messageInfo_ChainId.Size(m)
}
func (m *ChainId) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainId.DiscardUnknown(m)
}

var xxx_messageInfo_ChainId proto.InternalMessageInfo

func (m *ChainId) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Safe64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Safe64) Reset()         { *m = Safe64{} }
func (m *Safe64) String() string { return proto.CompactTextString(m) }
func (*Safe64) ProtoMessage()    {}
func (*Safe64) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{2}
}

func (m *Safe64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Safe64.Unmarshal(m, b)
}
func (m *Safe64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Safe64.Marshal(b, m, deterministic)
}
func (m *Safe64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Safe64.Merge(m, src)
}
func (m *Safe64) XXX_Size() int {
	return xxx_messageInfo_Safe64.Size(m)
}
func (m *Safe64) XXX_DiscardUnknown() {
	xxx_messageInfo_Safe64.DiscardUnknown(m)
}

var xxx_messageInfo_Safe64 proto.InternalMessageInfo

func (m *Safe64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Coin struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coin) Reset()         { *m = Coin{} }
func (m *Coin) String() string { return proto.CompactTextString(m) }
func (*Coin) ProtoMessage()    {}
func (*Coin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{3}
}

func (m *Coin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coin.Unmarshal(m, b)
}
func (m *Coin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coin.Marshal(b, m, deterministic)
}
func (m *Coin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coin.Merge(m, src)
}
func (m *Coin) XXX_Size() int {
	return xxx_messageInfo_Coin.Size(m)
}
func (m *Coin) XXX_DiscardUnknown() {
	xxx_messageInfo_Coin.DiscardUnknown(m)
}

var xxx_messageInfo_Coin proto.InternalMessageInfo

func (m *Coin) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Vest struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vest) Reset()         { *m = Vest{} }
func (m *Vest) String() string { return proto.CompactTextString(m) }
func (*Vest) ProtoMessage()    {}
func (*Vest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{4}
}

func (m *Vest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vest.Unmarshal(m, b)
}
func (m *Vest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vest.Marshal(b, m, deterministic)
}
func (m *Vest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vest.Merge(m, src)
}
func (m *Vest) XXX_Size() int {
	return xxx_messageInfo_Vest.Size(m)
}
func (m *Vest) XXX_DiscardUnknown() {
	xxx_messageInfo_Vest.DiscardUnknown(m)
}

var xxx_messageInfo_Vest proto.InternalMessageInfo

func (m *Vest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PublicKeyType struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyType) Reset()         { *m = PublicKeyType{} }
func (m *PublicKeyType) String() string { return proto.CompactTextString(m) }
func (*PublicKeyType) ProtoMessage()    {}
func (*PublicKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{5}
}

func (m *PublicKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyType.Unmarshal(m, b)
}
func (m *PublicKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyType.Marshal(b, m, deterministic)
}
func (m *PublicKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyType.Merge(m, src)
}
func (m *PublicKeyType) XXX_Size() int {
	return xxx_messageInfo_PublicKeyType.Size(m)
}
func (m *PublicKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyType proto.InternalMessageInfo

func (m *PublicKeyType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrivateKeyType struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKeyType) Reset()         { *m = PrivateKeyType{} }
func (m *PrivateKeyType) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyType) ProtoMessage()    {}
func (*PrivateKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{6}
}

func (m *PrivateKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyType.Unmarshal(m, b)
}
func (m *PrivateKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyType.Marshal(b, m, deterministic)
}
func (m *PrivateKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyType.Merge(m, src)
}
func (m *PrivateKeyType) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyType.Size(m)
}
func (m *PrivateKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyType proto.InternalMessageInfo

func (m *PrivateKeyType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type KvAccountAuth struct {
	Name                 *AccountName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight               uint32       `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *KvAccountAuth) Reset()         { *m = KvAccountAuth{} }
func (m *KvAccountAuth) String() string { return proto.CompactTextString(m) }
func (*KvAccountAuth) ProtoMessage()    {}
func (*KvAccountAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{7}
}

func (m *KvAccountAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvAccountAuth.Unmarshal(m, b)
}
func (m *KvAccountAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvAccountAuth.Marshal(b, m, deterministic)
}
func (m *KvAccountAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvAccountAuth.Merge(m, src)
}
func (m *KvAccountAuth) XXX_Size() int {
	return xxx_messageInfo_KvAccountAuth.Size(m)
}
func (m *KvAccountAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_KvAccountAuth.DiscardUnknown(m)
}

var xxx_messageInfo_KvAccountAuth proto.InternalMessageInfo

func (m *KvAccountAuth) GetName() *AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *KvAccountAuth) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type KvKeyAuth struct {
	Key                  *PublicKeyType `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Weight               uint32         `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KvKeyAuth) Reset()         { *m = KvKeyAuth{} }
func (m *KvKeyAuth) String() string { return proto.CompactTextString(m) }
func (*KvKeyAuth) ProtoMessage()    {}
func (*KvKeyAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{8}
}

func (m *KvKeyAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvKeyAuth.Unmarshal(m, b)
}
func (m *KvKeyAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvKeyAuth.Marshal(b, m, deterministic)
}
func (m *KvKeyAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvKeyAuth.Merge(m, src)
}
func (m *KvKeyAuth) XXX_Size() int {
	return xxx_messageInfo_KvKeyAuth.Size(m)
}
func (m *KvKeyAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_KvKeyAuth.DiscardUnknown(m)
}

var xxx_messageInfo_KvKeyAuth proto.InternalMessageInfo

func (m *KvKeyAuth) GetKey() *PublicKeyType {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KvKeyAuth) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Authority struct {
	Cf                   AuthorityClassification `protobuf:"varint,1,opt,name=cf,proto3,enum=prototype.AuthorityClassification" json:"cf,omitempty"`
	WeightThreshold      uint32                  `protobuf:"varint,2,opt,name=weight_threshold,json=weightThreshold,proto3" json:"weight_threshold,omitempty"`
	AccountAuths         []*KvAccountAuth        `protobuf:"bytes,3,rep,name=account_auths,json=accountAuths,proto3" json:"account_auths,omitempty"`
	KeyAuths             []*KvKeyAuth            `protobuf:"bytes,4,rep,name=key_auths,json=keyAuths,proto3" json:"key_auths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Authority) Reset()         { *m = Authority{} }
func (m *Authority) String() string { return proto.CompactTextString(m) }
func (*Authority) ProtoMessage()    {}
func (*Authority) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{9}
}

func (m *Authority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authority.Unmarshal(m, b)
}
func (m *Authority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authority.Marshal(b, m, deterministic)
}
func (m *Authority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authority.Merge(m, src)
}
func (m *Authority) XXX_Size() int {
	return xxx_messageInfo_Authority.Size(m)
}
func (m *Authority) XXX_DiscardUnknown() {
	xxx_messageInfo_Authority.DiscardUnknown(m)
}

var xxx_messageInfo_Authority proto.InternalMessageInfo

func (m *Authority) GetCf() AuthorityClassification {
	if m != nil {
		return m.Cf
	}
	return Authority_owner
}

func (m *Authority) GetWeightThreshold() uint32 {
	if m != nil {
		return m.WeightThreshold
	}
	return 0
}

func (m *Authority) GetAccountAuths() []*KvAccountAuth {
	if m != nil {
		return m.AccountAuths
	}
	return nil
}

func (m *Authority) GetKeyAuths() []*KvKeyAuth {
	if m != nil {
		return m.KeyAuths
	}
	return nil
}

type TimePointSec struct {
	UtcSeconds           uint32   `protobuf:"varint,1,opt,name=utc_seconds,json=utcSeconds,proto3" json:"utc_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimePointSec) Reset()         { *m = TimePointSec{} }
func (m *TimePointSec) String() string { return proto.CompactTextString(m) }
func (*TimePointSec) ProtoMessage()    {}
func (*TimePointSec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{10}
}

func (m *TimePointSec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimePointSec.Unmarshal(m, b)
}
func (m *TimePointSec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimePointSec.Marshal(b, m, deterministic)
}
func (m *TimePointSec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimePointSec.Merge(m, src)
}
func (m *TimePointSec) XXX_Size() int {
	return xxx_messageInfo_TimePointSec.Size(m)
}
func (m *TimePointSec) XXX_DiscardUnknown() {
	xxx_messageInfo_TimePointSec.DiscardUnknown(m)
}

var xxx_messageInfo_TimePointSec proto.InternalMessageInfo

func (m *TimePointSec) GetUtcSeconds() uint32 {
	if m != nil {
		return m.UtcSeconds
	}
	return 0
}

type SignatureType struct {
	Sig                  []byte   `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureType) Reset()         { *m = SignatureType{} }
func (m *SignatureType) String() string { return proto.CompactTextString(m) }
func (*SignatureType) ProtoMessage()    {}
func (*SignatureType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{11}
}

func (m *SignatureType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureType.Unmarshal(m, b)
}
func (m *SignatureType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureType.Marshal(b, m, deterministic)
}
func (m *SignatureType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureType.Merge(m, src)
}
func (m *SignatureType) XXX_Size() int {
	return xxx_messageInfo_SignatureType.Size(m)
}
func (m *SignatureType) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureType.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureType proto.InternalMessageInfo

func (m *SignatureType) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Sha256 struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sha256) Reset()         { *m = Sha256{} }
func (m *Sha256) String() string { return proto.CompactTextString(m) }
func (*Sha256) ProtoMessage()    {}
func (*Sha256) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{12}
}

func (m *Sha256) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sha256.Unmarshal(m, b)
}
func (m *Sha256) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sha256.Marshal(b, m, deterministic)
}
func (m *Sha256) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sha256.Merge(m, src)
}
func (m *Sha256) XXX_Size() int {
	return xxx_messageInfo_Sha256.Size(m)
}
func (m *Sha256) XXX_DiscardUnknown() {
	xxx_messageInfo_Sha256.DiscardUnknown(m)
}

var xxx_messageInfo_Sha256 proto.InternalMessageInfo

func (m *Sha256) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ChainProperties struct {
	AccountCreationFee   *Coin    `protobuf:"bytes,1,opt,name=account_creation_fee,json=accountCreationFee,proto3" json:"account_creation_fee,omitempty"`
	MaximumBlockSize     uint32   `protobuf:"varint,2,opt,name=maximum_block_size,json=maximumBlockSize,proto3" json:"maximum_block_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainProperties) Reset()         { *m = ChainProperties{} }
func (m *ChainProperties) String() string { return proto.CompactTextString(m) }
func (*ChainProperties) ProtoMessage()    {}
func (*ChainProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{13}
}

func (m *ChainProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainProperties.Unmarshal(m, b)
}
func (m *ChainProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainProperties.Marshal(b, m, deterministic)
}
func (m *ChainProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainProperties.Merge(m, src)
}
func (m *ChainProperties) XXX_Size() int {
	return xxx_messageInfo_ChainProperties.Size(m)
}
func (m *ChainProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ChainProperties proto.InternalMessageInfo

func (m *ChainProperties) GetAccountCreationFee() *Coin {
	if m != nil {
		return m.AccountCreationFee
	}
	return nil
}

func (m *ChainProperties) GetMaximumBlockSize() uint32 {
	if m != nil {
		return m.MaximumBlockSize
	}
	return 0
}

type FollowerRelation struct {
	Account              *AccountName  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          *TimePointSec `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Follower             *AccountName  `protobuf:"bytes,3,opt,name=follower,proto3" json:"follower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FollowerRelation) Reset()         { *m = FollowerRelation{} }
func (m *FollowerRelation) String() string { return proto.CompactTextString(m) }
func (*FollowerRelation) ProtoMessage()    {}
func (*FollowerRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{14}
}

func (m *FollowerRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerRelation.Unmarshal(m, b)
}
func (m *FollowerRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerRelation.Marshal(b, m, deterministic)
}
func (m *FollowerRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerRelation.Merge(m, src)
}
func (m *FollowerRelation) XXX_Size() int {
	return xxx_messageInfo_FollowerRelation.Size(m)
}
func (m *FollowerRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerRelation.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerRelation proto.InternalMessageInfo

func (m *FollowerRelation) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FollowerRelation) GetCreatedTime() *TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *FollowerRelation) GetFollower() *AccountName {
	if m != nil {
		return m.Follower
	}
	return nil
}

type FollowingRelation struct {
	Account              *AccountName  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          *TimePointSec `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Following            *AccountName  `protobuf:"bytes,3,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FollowingRelation) Reset()         { *m = FollowingRelation{} }
func (m *FollowingRelation) String() string { return proto.CompactTextString(m) }
func (*FollowingRelation) ProtoMessage()    {}
func (*FollowingRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{15}
}

func (m *FollowingRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingRelation.Unmarshal(m, b)
}
func (m *FollowingRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingRelation.Marshal(b, m, deterministic)
}
func (m *FollowingRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingRelation.Merge(m, src)
}
func (m *FollowingRelation) XXX_Size() int {
	return xxx_messageInfo_FollowingRelation.Size(m)
}
func (m *FollowingRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingRelation.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingRelation proto.InternalMessageInfo

func (m *FollowingRelation) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FollowingRelation) GetCreatedTime() *TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *FollowingRelation) GetFollowing() *AccountName {
	if m != nil {
		return m.Following
	}
	return nil
}

type WitnessScheduleType struct {
	Value                WitnessScheduleTypeWitnessScheduleType `protobuf:"varint,1,opt,name=value,proto3,enum=prototype.WitnessScheduleTypeWitnessScheduleType" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *WitnessScheduleType) Reset()         { *m = WitnessScheduleType{} }
func (m *WitnessScheduleType) String() string { return proto.CompactTextString(m) }
func (*WitnessScheduleType) ProtoMessage()    {}
func (*WitnessScheduleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{16}
}

func (m *WitnessScheduleType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WitnessScheduleType.Unmarshal(m, b)
}
func (m *WitnessScheduleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WitnessScheduleType.Marshal(b, m, deterministic)
}
func (m *WitnessScheduleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessScheduleType.Merge(m, src)
}
func (m *WitnessScheduleType) XXX_Size() int {
	return xxx_messageInfo_WitnessScheduleType.Size(m)
}
func (m *WitnessScheduleType) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessScheduleType.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessScheduleType proto.InternalMessageInfo

func (m *WitnessScheduleType) GetValue() WitnessScheduleTypeWitnessScheduleType {
	if m != nil {
		return m.Value
	}
	return WitnessScheduleType_top19
}

type PostCreatedOrder struct {
	LastUpdate           *TimePointSec `protobuf:"bytes,1,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	RootId               uint64        `protobuf:"varint,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	PostId               uint64        `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostCreatedOrder) Reset()         { *m = PostCreatedOrder{} }
func (m *PostCreatedOrder) String() string { return proto.CompactTextString(m) }
func (*PostCreatedOrder) ProtoMessage()    {}
func (*PostCreatedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{17}
}

func (m *PostCreatedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCreatedOrder.Unmarshal(m, b)
}
func (m *PostCreatedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCreatedOrder.Marshal(b, m, deterministic)
}
func (m *PostCreatedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCreatedOrder.Merge(m, src)
}
func (m *PostCreatedOrder) XXX_Size() int {
	return xxx_messageInfo_PostCreatedOrder.Size(m)
}
func (m *PostCreatedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCreatedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PostCreatedOrder proto.InternalMessageInfo

func (m *PostCreatedOrder) GetLastUpdate() *TimePointSec {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

func (m *PostCreatedOrder) GetRootId() uint64 {
	if m != nil {
		return m.RootId
	}
	return 0
}

func (m *PostCreatedOrder) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type PostReplyOrder struct {
	RootId               uint64        `protobuf:"varint,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	LastUpdate           *TimePointSec `protobuf:"bytes,2,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	PostId               uint64        `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostReplyOrder) Reset()         { *m = PostReplyOrder{} }
func (m *PostReplyOrder) String() string { return proto.CompactTextString(m) }
func (*PostReplyOrder) ProtoMessage()    {}
func (*PostReplyOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{18}
}

func (m *PostReplyOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReplyOrder.Unmarshal(m, b)
}
func (m *PostReplyOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReplyOrder.Marshal(b, m, deterministic)
}
func (m *PostReplyOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReplyOrder.Merge(m, src)
}
func (m *PostReplyOrder) XXX_Size() int {
	return xxx_messageInfo_PostReplyOrder.Size(m)
}
func (m *PostReplyOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReplyOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PostReplyOrder proto.InternalMessageInfo

func (m *PostReplyOrder) GetRootId() uint64 {
	if m != nil {
		return m.RootId
	}
	return 0
}

func (m *PostReplyOrder) GetLastUpdate() *TimePointSec {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

func (m *PostReplyOrder) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func init() {
	proto.RegisterEnum("prototype.AuthorityClassification", AuthorityClassification_name, AuthorityClassification_value)
	proto.RegisterEnum("prototype.WitnessScheduleTypeWitnessScheduleType", WitnessScheduleTypeWitnessScheduleType_name, WitnessScheduleTypeWitnessScheduleType_value)
	proto.RegisterType((*AccountName)(nil), "prototype.account_name")
	proto.RegisterType((*ChainId)(nil), "prototype.chain_id")
	proto.RegisterType((*Safe64)(nil), "prototype.safe64")
	proto.RegisterType((*Coin)(nil), "prototype.coin")
	proto.RegisterType((*Vest)(nil), "prototype.vest")
	proto.RegisterType((*PublicKeyType)(nil), "prototype.public_key_type")
	proto.RegisterType((*PrivateKeyType)(nil), "prototype.private_key_type")
	proto.RegisterType((*KvAccountAuth)(nil), "prototype.kv_account_auth")
	proto.RegisterType((*KvKeyAuth)(nil), "prototype.kv_key_auth")
	proto.RegisterType((*Authority)(nil), "prototype.authority")
	proto.RegisterType((*TimePointSec)(nil), "prototype.time_point_sec")
	proto.RegisterType((*SignatureType)(nil), "prototype.signature_type")
	proto.RegisterType((*Sha256)(nil), "prototype.sha256")
	proto.RegisterType((*ChainProperties)(nil), "prototype.chain_properties")
	proto.RegisterType((*FollowerRelation)(nil), "prototype.follower_relation")
	proto.RegisterType((*FollowingRelation)(nil), "prototype.following_relation")
	proto.RegisterType((*WitnessScheduleType)(nil), "prototype.witness_schedule_type")
	proto.RegisterType((*PostCreatedOrder)(nil), "prototype.post_created_order")
	proto.RegisterType((*PostReplyOrder)(nil), "prototype.post_reply_order")
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059) }

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 800 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x5d, 0x6f, 0x23, 0x35,
	0x14, 0xdd, 0x49, 0xd2, 0xb4, 0x73, 0xd3, 0xa6, 0x83, 0xb5, 0xec, 0x06, 0xb4, 0x82, 0x6a, 0xf8,
	0x10, 0x1f, 0x25, 0x55, 0x53, 0xb6, 0x12, 0x08, 0x84, 0x76, 0x91, 0x56, 0x5a, 0x89, 0xa7, 0xe9,
	0xc2, 0x03, 0x2f, 0x96, 0xeb, 0xb9, 0xc9, 0x58, 0x99, 0xd8, 0x23, 0xdb, 0x93, 0x92, 0x7d, 0x42,
	0xf0, 0x47, 0xf8, 0x03, 0xfc, 0x00, 0x24, 0x7e, 0x1c, 0xb2, 0x67, 0x5c, 0x26, 0x55, 0xdb, 0x15,
	0x4f, 0x3c, 0xc5, 0xf6, 0x3d, 0x3e, 0xf7, 0xf8, 0xe4, 0xdc, 0x01, 0xb0, 0x9b, 0x0a, 0xa7, 0x95,
	0x56, 0x56, 0x91, 0xd8, 0xff, 0xb8, 0x83, 0xf4, 0x43, 0xd8, 0x67, 0x9c, 0xab, 0x5a, 0x5a, 0x2a,
	0xd9, 0x0a, 0xc9, 0x43, 0xd8, 0x59, 0xb3, 0xb2, 0xc6, 0x49, 0x74, 0x14, 0x7d, 0x12, 0x67, 0xcd,
	0x26, 0x3d, 0x82, 0x3d, 0x5e, 0x30, 0x21, 0xa9, 0xc8, 0xb7, 0x11, 0x07, 0x01, 0xf1, 0x1e, 0x0c,
	0x0d, 0x9b, 0xe3, 0xf9, 0x97, 0xdb, 0xf5, 0x7e, 0xa8, 0x3f, 0x81, 0x01, 0x57, 0x42, 0x6e, 0x57,
	0x07, 0x9d, 0xea, 0x1a, 0x8d, 0xbd, 0xa3, 0xfa, 0x11, 0x1c, 0x56, 0xf5, 0x65, 0x29, 0x38, 0x5d,
	0xe2, 0x86, 0x3a, 0xd9, 0x84, 0xc0, 0x20, 0x67, 0x96, 0x79, 0xdc, 0x7e, 0xe6, 0xd7, 0xe9, 0xc7,
	0x90, 0x54, 0x5a, 0xac, 0x99, 0xc5, 0xfb, 0x71, 0x3f, 0xc1, 0xe1, 0x72, 0x4d, 0xc3, 0xab, 0x59,
	0x6d, 0x0b, 0xf2, 0x39, 0x0c, 0xdc, 0xeb, 0x3d, 0x6c, 0x34, 0x7b, 0x3c, 0xbd, 0xf6, 0x67, 0xda,
	0x35, 0x27, 0xf3, 0x20, 0xf2, 0x08, 0x86, 0x57, 0x28, 0x16, 0x85, 0x9d, 0xf4, 0xbc, 0x03, 0xed,
	0x2e, 0xbd, 0x80, 0xd1, 0x72, 0xed, 0x5b, 0x7b, 0xce, 0x63, 0xe8, 0x2f, 0x71, 0xd3, 0x52, 0xbe,
	0xdb, 0xa1, 0xbc, 0xf1, 0x96, 0xcc, 0xc1, 0xee, 0x24, 0xfd, 0xa3, 0x07, 0xb1, 0xa3, 0x53, 0x5a,
	0xd8, 0x0d, 0x39, 0x83, 0x1e, 0x9f, 0x7b, 0xca, 0xf1, 0xec, 0x83, 0xae, 0xca, 0x80, 0x98, 0xf2,
	0x92, 0x19, 0x23, 0xe6, 0x82, 0x33, 0x2b, 0x94, 0xcc, 0x7a, 0x7c, 0x4e, 0x3e, 0x85, 0xa4, 0x21,
	0xa3, 0xb6, 0xd0, 0x68, 0x0a, 0x55, 0xe6, 0x6d, 0x93, 0xc3, 0xe6, 0xfc, 0x55, 0x38, 0x26, 0xdf,
	0xc1, 0x41, 0xd7, 0x17, 0x33, 0xe9, 0x1f, 0xf5, 0x6f, 0xa8, 0xbf, 0x61, 0x5d, 0x16, 0xe2, 0xf3,
	0xcc, 0xe1, 0xc9, 0x19, 0xc4, 0xc1, 0x00, 0x33, 0x19, 0xf8, 0xcb, 0x8f, 0xb6, 0x2f, 0x87, 0x72,
	0xb6, 0xb7, 0xc4, 0x8d, 0xbf, 0x94, 0x7e, 0x0b, 0xe3, 0x6d, 0xd9, 0x24, 0x86, 0x1d, 0x75, 0x25,
	0x51, 0x27, 0x0f, 0x08, 0xc0, 0x90, 0x71, 0x2b, 0xd6, 0x98, 0x44, 0x64, 0xd7, 0x5b, 0x9a, 0xf4,
	0xc8, 0x08, 0x76, 0x2b, 0x65, 0xac, 0x90, 0x8b, 0xa4, 0x9f, 0x9e, 0xc2, 0xd8, 0x8a, 0x15, 0xd2,
	0x4a, 0x09, 0x69, 0xa9, 0x41, 0x4e, 0xde, 0x87, 0x51, 0x6d, 0xb9, 0x5b, 0x2a, 0x99, 0x9b, 0x36,
	0xa8, 0x50, 0x5b, 0x7e, 0xd1, 0x9c, 0xa4, 0x29, 0x8c, 0x8d, 0x58, 0x48, 0x66, 0x6b, 0x8d, 0x4d,
	0x50, 0x12, 0xe8, 0x1b, 0xb1, 0x68, 0x73, 0xe2, 0x96, 0xe9, 0x13, 0x18, 0x9a, 0x82, 0xcd, 0x9e,
	0x9e, 0xbb, 0x10, 0x15, 0xcc, 0x14, 0x21, 0x44, 0x6e, 0x9d, 0xfe, 0x1e, 0x41, 0xd2, 0x8c, 0x44,
	0xa5, 0x55, 0x85, 0xda, 0x0a, 0x34, 0xe4, 0x19, 0x3c, 0x0c, 0xde, 0x70, 0x8d, 0xfe, 0x29, 0x74,
	0x8e, 0x21, 0x56, 0x87, 0x1d, 0x23, 0xdc, 0x2c, 0x64, 0xa4, 0x05, 0x7f, 0xdf, 0x62, 0x5f, 0x20,
	0x92, 0x63, 0x20, 0x2b, 0xf6, 0x8b, 0x58, 0xd5, 0x2b, 0x7a, 0x59, 0x2a, 0xbe, 0xa4, 0x46, 0xbc,
	0xc6, 0xf6, 0xef, 0x4a, 0xda, 0xca, 0x73, 0x57, 0xb8, 0x10, 0xaf, 0x31, 0xfd, 0x2b, 0x82, 0xb7,
	0xe6, 0xaa, 0x2c, 0xd5, 0x15, 0x6a, 0xaa, 0xb1, 0x6c, 0xdc, 0x3b, 0x85, 0xdd, 0x96, 0xf9, 0x4d,
	0x81, 0x0e, 0x38, 0xf2, 0x0d, 0xec, 0x7b, 0xc5, 0x98, 0x53, 0xe7, 0xa5, 0x6f, 0x38, 0x9a, 0xbd,
	0xd3, 0xb9, 0xb7, 0x6d, 0x71, 0x36, 0x6a, 0xe1, 0xaf, 0xc4, 0x0a, 0xc9, 0x19, 0xec, 0x05, 0x15,
	0x93, 0xfe, 0xfd, 0x1d, 0xaf, 0x81, 0xe9, 0xdf, 0x11, 0x90, 0x66, 0x23, 0xe4, 0xe2, 0x7f, 0x14,
	0xff, 0x14, 0xe2, 0x6b, 0x19, 0x6f, 0x52, 0xff, 0x2f, 0x32, 0xfd, 0x33, 0x82, 0xb7, 0xaf, 0x84,
	0x95, 0x68, 0x0c, 0x35, 0xbc, 0xc0, 0xbc, 0x2e, 0xdb, 0x28, 0xfd, 0xd0, 0xfd, 0x88, 0x8d, 0x67,
	0xe7, 0x1d, 0xb2, 0x5b, 0x2f, 0xdc, 0x7e, 0x1a, 0x3e, 0x7e, 0x2f, 0xee, 0x6a, 0x13, 0xc3, 0x8e,
	0x55, 0xd5, 0xe9, 0x57, 0xc9, 0x03, 0x72, 0x00, 0xb1, 0x7b, 0xa1, 0x29, 0x98, 0x76, 0x63, 0x12,
	0xc3, 0xce, 0x4a, 0xb8, 0xe9, 0xe9, 0x91, 0x3d, 0x18, 0x48, 0x25, 0x31, 0xe9, 0xa7, 0xbf, 0x45,
	0x40, 0xdc, 0xcc, 0xd0, 0x60, 0x95, 0xd2, 0x39, 0x6a, 0xf2, 0x35, 0x8c, 0x4a, 0x66, 0x2c, 0xad,
	0xab, 0x9c, 0xd9, 0x90, 0xd4, 0x7b, 0xac, 0x03, 0x87, 0xfe, 0xd1, 0x83, 0xc9, 0x63, 0xd8, 0xd5,
	0x4a, 0x59, 0x2a, 0x9a, 0xef, 0xc9, 0x20, 0x1b, 0xba, 0xed, 0xcb, 0xdc, 0x15, 0x7c, 0x2b, 0x91,
	0x7b, 0x43, 0x07, 0xd9, 0xd0, 0x6d, 0x5f, 0xe6, 0xe9, 0xaf, 0x11, 0x24, 0xbe, 0xa2, 0xb1, 0x2a,
	0x37, 0xad, 0x84, 0x0e, 0x4d, 0xb4, 0x45, 0x73, 0x43, 0x5b, 0xef, 0x3f, 0x6a, 0xbb, 0x55, 0xc2,
	0xf3, 0xe3, 0x9f, 0x3f, 0x5b, 0x08, 0x5b, 0xd4, 0x97, 0x53, 0xae, 0x56, 0x27, 0x5c, 0x19, 0x3f,
	0xc5, 0x27, 0x5c, 0x49, 0x8b, 0xd2, 0x2a, 0xf3, 0xc5, 0x42, 0x9d, 0x5c, 0x77, 0xb8, 0x1c, 0xfa,
	0xe5, 0xd9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x12, 0x9b, 0x3b, 0x3e, 0x07, 0x00, 0x00,
}
