// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prototype/type.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthorityClassification int32

const (
	Authority_owner   AuthorityClassification = 0
	Authority_active  AuthorityClassification = 1
	Authority_key     AuthorityClassification = 2
	Authority_posting AuthorityClassification = 3
)

var AuthorityClassification_name = map[int32]string{
	0: "owner",
	1: "active",
	2: "key",
	3: "posting",
}

var AuthorityClassification_value = map[string]int32{
	"owner":   0,
	"active":  1,
	"key":     2,
	"posting": 3,
}

func (x AuthorityClassification) String() string {
	return proto.EnumName(AuthorityClassification_name, int32(x))
}

func (AuthorityClassification) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{9, 0}
}

type AccountName struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountName) Reset()         { *m = AccountName{} }
func (m *AccountName) String() string { return proto.CompactTextString(m) }
func (*AccountName) ProtoMessage()    {}
func (*AccountName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{0}
}

func (m *AccountName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountName.Unmarshal(m, b)
}
func (m *AccountName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountName.Marshal(b, m, deterministic)
}
func (m *AccountName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountName.Merge(m, src)
}
func (m *AccountName) XXX_Size() int {
	return xxx_messageInfo_AccountName.Size(m)
}
func (m *AccountName) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountName.DiscardUnknown(m)
}

var xxx_messageInfo_AccountName proto.InternalMessageInfo

func (m *AccountName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ChainId struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainId) Reset()         { *m = ChainId{} }
func (m *ChainId) String() string { return proto.CompactTextString(m) }
func (*ChainId) ProtoMessage()    {}
func (*ChainId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{1}
}

func (m *ChainId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainId.Unmarshal(m, b)
}
func (m *ChainId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainId.Marshal(b, m, deterministic)
}
func (m *ChainId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainId.Merge(m, src)
}
func (m *ChainId) XXX_Size() int {
	return xxx_messageInfo_ChainId.Size(m)
}
func (m *ChainId) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainId.DiscardUnknown(m)
}

var xxx_messageInfo_ChainId proto.InternalMessageInfo

func (m *ChainId) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Safe64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Safe64) Reset()         { *m = Safe64{} }
func (m *Safe64) String() string { return proto.CompactTextString(m) }
func (*Safe64) ProtoMessage()    {}
func (*Safe64) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{2}
}

func (m *Safe64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Safe64.Unmarshal(m, b)
}
func (m *Safe64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Safe64.Marshal(b, m, deterministic)
}
func (m *Safe64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Safe64.Merge(m, src)
}
func (m *Safe64) XXX_Size() int {
	return xxx_messageInfo_Safe64.Size(m)
}
func (m *Safe64) XXX_DiscardUnknown() {
	xxx_messageInfo_Safe64.DiscardUnknown(m)
}

var xxx_messageInfo_Safe64 proto.InternalMessageInfo

func (m *Safe64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Coin struct {
	Amount               *Safe64  `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coin) Reset()         { *m = Coin{} }
func (m *Coin) String() string { return proto.CompactTextString(m) }
func (*Coin) ProtoMessage()    {}
func (*Coin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{3}
}

func (m *Coin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coin.Unmarshal(m, b)
}
func (m *Coin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coin.Marshal(b, m, deterministic)
}
func (m *Coin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coin.Merge(m, src)
}
func (m *Coin) XXX_Size() int {
	return xxx_messageInfo_Coin.Size(m)
}
func (m *Coin) XXX_DiscardUnknown() {
	xxx_messageInfo_Coin.DiscardUnknown(m)
}

var xxx_messageInfo_Coin proto.InternalMessageInfo

func (m *Coin) GetAmount() *Safe64 {
	if m != nil {
		return m.Amount
	}
	return nil
}

type Vest struct {
	Amount               *Safe64  `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vest) Reset()         { *m = Vest{} }
func (m *Vest) String() string { return proto.CompactTextString(m) }
func (*Vest) ProtoMessage()    {}
func (*Vest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{4}
}

func (m *Vest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vest.Unmarshal(m, b)
}
func (m *Vest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vest.Marshal(b, m, deterministic)
}
func (m *Vest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vest.Merge(m, src)
}
func (m *Vest) XXX_Size() int {
	return xxx_messageInfo_Vest.Size(m)
}
func (m *Vest) XXX_DiscardUnknown() {
	xxx_messageInfo_Vest.DiscardUnknown(m)
}

var xxx_messageInfo_Vest proto.InternalMessageInfo

func (m *Vest) GetAmount() *Safe64 {
	if m != nil {
		return m.Amount
	}
	return nil
}

type PublicKeyType struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyType) Reset()         { *m = PublicKeyType{} }
func (m *PublicKeyType) String() string { return proto.CompactTextString(m) }
func (*PublicKeyType) ProtoMessage()    {}
func (*PublicKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{5}
}

func (m *PublicKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyType.Unmarshal(m, b)
}
func (m *PublicKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyType.Marshal(b, m, deterministic)
}
func (m *PublicKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyType.Merge(m, src)
}
func (m *PublicKeyType) XXX_Size() int {
	return xxx_messageInfo_PublicKeyType.Size(m)
}
func (m *PublicKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyType proto.InternalMessageInfo

func (m *PublicKeyType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrivateKeyType struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKeyType) Reset()         { *m = PrivateKeyType{} }
func (m *PrivateKeyType) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyType) ProtoMessage()    {}
func (*PrivateKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{6}
}

func (m *PrivateKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyType.Unmarshal(m, b)
}
func (m *PrivateKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyType.Marshal(b, m, deterministic)
}
func (m *PrivateKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyType.Merge(m, src)
}
func (m *PrivateKeyType) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyType.Size(m)
}
func (m *PrivateKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyType proto.InternalMessageInfo

func (m *PrivateKeyType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type KvAccountAuth struct {
	Name                 *AccountName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight               uint32       `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *KvAccountAuth) Reset()         { *m = KvAccountAuth{} }
func (m *KvAccountAuth) String() string { return proto.CompactTextString(m) }
func (*KvAccountAuth) ProtoMessage()    {}
func (*KvAccountAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{7}
}

func (m *KvAccountAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvAccountAuth.Unmarshal(m, b)
}
func (m *KvAccountAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvAccountAuth.Marshal(b, m, deterministic)
}
func (m *KvAccountAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvAccountAuth.Merge(m, src)
}
func (m *KvAccountAuth) XXX_Size() int {
	return xxx_messageInfo_KvAccountAuth.Size(m)
}
func (m *KvAccountAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_KvAccountAuth.DiscardUnknown(m)
}

var xxx_messageInfo_KvAccountAuth proto.InternalMessageInfo

func (m *KvAccountAuth) GetName() *AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *KvAccountAuth) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type KvKeyAuth struct {
	Key                  *PublicKeyType `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Weight               uint32         `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KvKeyAuth) Reset()         { *m = KvKeyAuth{} }
func (m *KvKeyAuth) String() string { return proto.CompactTextString(m) }
func (*KvKeyAuth) ProtoMessage()    {}
func (*KvKeyAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{8}
}

func (m *KvKeyAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvKeyAuth.Unmarshal(m, b)
}
func (m *KvKeyAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvKeyAuth.Marshal(b, m, deterministic)
}
func (m *KvKeyAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvKeyAuth.Merge(m, src)
}
func (m *KvKeyAuth) XXX_Size() int {
	return xxx_messageInfo_KvKeyAuth.Size(m)
}
func (m *KvKeyAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_KvKeyAuth.DiscardUnknown(m)
}

var xxx_messageInfo_KvKeyAuth proto.InternalMessageInfo

func (m *KvKeyAuth) GetKey() *PublicKeyType {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KvKeyAuth) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Authority struct {
	Cf                   AuthorityClassification `protobuf:"varint,1,opt,name=cf,proto3,enum=prototype.AuthorityClassification" json:"cf,omitempty"`
	WeightThreshold      uint32                  `protobuf:"varint,2,opt,name=weight_threshold,json=weightThreshold,proto3" json:"weight_threshold,omitempty"`
	AccountAuths         []*KvAccountAuth        `protobuf:"bytes,3,rep,name=account_auths,json=accountAuths,proto3" json:"account_auths,omitempty"`
	KeyAuths             []*KvKeyAuth            `protobuf:"bytes,4,rep,name=key_auths,json=keyAuths,proto3" json:"key_auths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Authority) Reset()         { *m = Authority{} }
func (m *Authority) String() string { return proto.CompactTextString(m) }
func (*Authority) ProtoMessage()    {}
func (*Authority) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{9}
}

func (m *Authority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authority.Unmarshal(m, b)
}
func (m *Authority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authority.Marshal(b, m, deterministic)
}
func (m *Authority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authority.Merge(m, src)
}
func (m *Authority) XXX_Size() int {
	return xxx_messageInfo_Authority.Size(m)
}
func (m *Authority) XXX_DiscardUnknown() {
	xxx_messageInfo_Authority.DiscardUnknown(m)
}

var xxx_messageInfo_Authority proto.InternalMessageInfo

func (m *Authority) GetCf() AuthorityClassification {
	if m != nil {
		return m.Cf
	}
	return Authority_owner
}

func (m *Authority) GetWeightThreshold() uint32 {
	if m != nil {
		return m.WeightThreshold
	}
	return 0
}

func (m *Authority) GetAccountAuths() []*KvAccountAuth {
	if m != nil {
		return m.AccountAuths
	}
	return nil
}

func (m *Authority) GetKeyAuths() []*KvKeyAuth {
	if m != nil {
		return m.KeyAuths
	}
	return nil
}

type TimePointSec struct {
	UtcSeconds           uint32   `protobuf:"varint,1,opt,name=utc_seconds,json=utcSeconds,proto3" json:"utc_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimePointSec) Reset()         { *m = TimePointSec{} }
func (m *TimePointSec) String() string { return proto.CompactTextString(m) }
func (*TimePointSec) ProtoMessage()    {}
func (*TimePointSec) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{10}
}

func (m *TimePointSec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimePointSec.Unmarshal(m, b)
}
func (m *TimePointSec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimePointSec.Marshal(b, m, deterministic)
}
func (m *TimePointSec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimePointSec.Merge(m, src)
}
func (m *TimePointSec) XXX_Size() int {
	return xxx_messageInfo_TimePointSec.Size(m)
}
func (m *TimePointSec) XXX_DiscardUnknown() {
	xxx_messageInfo_TimePointSec.DiscardUnknown(m)
}

var xxx_messageInfo_TimePointSec proto.InternalMessageInfo

func (m *TimePointSec) GetUtcSeconds() uint32 {
	if m != nil {
		return m.UtcSeconds
	}
	return 0
}

type SignatureType struct {
	Sig                  []byte   `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureType) Reset()         { *m = SignatureType{} }
func (m *SignatureType) String() string { return proto.CompactTextString(m) }
func (*SignatureType) ProtoMessage()    {}
func (*SignatureType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{11}
}

func (m *SignatureType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureType.Unmarshal(m, b)
}
func (m *SignatureType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureType.Marshal(b, m, deterministic)
}
func (m *SignatureType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureType.Merge(m, src)
}
func (m *SignatureType) XXX_Size() int {
	return xxx_messageInfo_SignatureType.Size(m)
}
func (m *SignatureType) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureType.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureType proto.InternalMessageInfo

func (m *SignatureType) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Sha256 struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sha256) Reset()         { *m = Sha256{} }
func (m *Sha256) String() string { return proto.CompactTextString(m) }
func (*Sha256) ProtoMessage()    {}
func (*Sha256) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{12}
}

func (m *Sha256) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sha256.Unmarshal(m, b)
}
func (m *Sha256) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sha256.Marshal(b, m, deterministic)
}
func (m *Sha256) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sha256.Merge(m, src)
}
func (m *Sha256) XXX_Size() int {
	return xxx_messageInfo_Sha256.Size(m)
}
func (m *Sha256) XXX_DiscardUnknown() {
	xxx_messageInfo_Sha256.DiscardUnknown(m)
}

var xxx_messageInfo_Sha256 proto.InternalMessageInfo

func (m *Sha256) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ChainProperties struct {
	AccountCreationFee   *Coin    `protobuf:"bytes,1,opt,name=account_creation_fee,json=accountCreationFee,proto3" json:"account_creation_fee,omitempty"`
	MaximumBlockSize     uint32   `protobuf:"varint,2,opt,name=maximum_block_size,json=maximumBlockSize,proto3" json:"maximum_block_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainProperties) Reset()         { *m = ChainProperties{} }
func (m *ChainProperties) String() string { return proto.CompactTextString(m) }
func (*ChainProperties) ProtoMessage()    {}
func (*ChainProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1b10af7c504b1c5, []int{13}
}

func (m *ChainProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainProperties.Unmarshal(m, b)
}
func (m *ChainProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainProperties.Marshal(b, m, deterministic)
}
func (m *ChainProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainProperties.Merge(m, src)
}
func (m *ChainProperties) XXX_Size() int {
	return xxx_messageInfo_ChainProperties.Size(m)
}
func (m *ChainProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ChainProperties proto.InternalMessageInfo

func (m *ChainProperties) GetAccountCreationFee() *Coin {
	if m != nil {
		return m.AccountCreationFee
	}
	return nil
}

func (m *ChainProperties) GetMaximumBlockSize() uint32 {
	if m != nil {
		return m.MaximumBlockSize
	}
	return 0
}

func init() {
	proto.RegisterEnum("prototype.AuthorityClassification", AuthorityClassification_name, AuthorityClassification_value)
	proto.RegisterType((*AccountName)(nil), "prototype.account_name")
	proto.RegisterType((*ChainId)(nil), "prototype.chain_id")
	proto.RegisterType((*Safe64)(nil), "prototype.safe64")
	proto.RegisterType((*Coin)(nil), "prototype.coin")
	proto.RegisterType((*Vest)(nil), "prototype.vest")
	proto.RegisterType((*PublicKeyType)(nil), "prototype.public_key_type")
	proto.RegisterType((*PrivateKeyType)(nil), "prototype.private_key_type")
	proto.RegisterType((*KvAccountAuth)(nil), "prototype.kv_account_auth")
	proto.RegisterType((*KvKeyAuth)(nil), "prototype.kv_key_auth")
	proto.RegisterType((*Authority)(nil), "prototype.authority")
	proto.RegisterType((*TimePointSec)(nil), "prototype.time_point_sec")
	proto.RegisterType((*SignatureType)(nil), "prototype.signature_type")
	proto.RegisterType((*Sha256)(nil), "prototype.sha256")
	proto.RegisterType((*ChainProperties)(nil), "prototype.chain_properties")
}

func init() { proto.RegisterFile("prototype/type.proto", fileDescriptor_f1b10af7c504b1c5) }

var fileDescriptor_f1b10af7c504b1c5 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x12, 0xa7, 0x6e, 0x33, 0x69, 0x13, 0x7f, 0xab, 0xaa, 0x44, 0x08, 0x41, 0x65, 0x7e,
	0x44, 0xa1, 0x24, 0x6a, 0x03, 0xbd, 0x43, 0xa8, 0x45, 0xe2, 0x01, 0x1c, 0xc4, 0x05, 0x37, 0xd6,
	0x66, 0x33, 0xb1, 0x57, 0x8e, 0x77, 0x2d, 0xef, 0xda, 0x25, 0xbd, 0xe5, 0x45, 0x78, 0x54, 0xb4,
	0x6b, 0x3b, 0x72, 0x22, 0x81, 0xc4, 0x8d, 0x35, 0x3b, 0x73, 0xe6, 0xcc, 0xec, 0xf1, 0x59, 0x38,
	0xcd, 0x72, 0xa9, 0xa5, 0xde, 0x64, 0x38, 0x35, 0x9f, 0x89, 0x3d, 0x92, 0xfe, 0x36, 0xeb, 0xbf,
	0x80, 0x63, 0xca, 0x98, 0x2c, 0x84, 0x0e, 0x05, 0x4d, 0x91, 0x9c, 0xc2, 0x41, 0x49, 0xd7, 0x05,
	0x8e, 0x3b, 0xe7, 0x9d, 0xd7, 0xfd, 0xa0, 0x3a, 0xf8, 0xe7, 0x70, 0xc4, 0x62, 0xca, 0x45, 0xc8,
	0x97, 0xbb, 0x88, 0x93, 0x06, 0xf1, 0x14, 0x5c, 0x45, 0x57, 0x78, 0xf3, 0x7e, 0xb7, 0xee, 0x34,
	0xf5, 0x2b, 0xe8, 0x31, 0xc9, 0x05, 0xb9, 0x00, 0x97, 0xa6, 0x66, 0x9c, 0x2d, 0x0f, 0xae, 0xff,
	0x9f, 0x6c, 0x77, 0x99, 0x54, 0x04, 0x41, 0x0d, 0x30, 0x2d, 0x25, 0x2a, 0xfd, 0x2f, 0x2d, 0x2f,
	0x61, 0x94, 0x15, 0x8b, 0x35, 0x67, 0x61, 0x82, 0x9b, 0xd0, 0x20, 0x08, 0x81, 0xde, 0x92, 0x6a,
	0x6a, 0x7b, 0x8f, 0x03, 0x1b, 0xfb, 0xaf, 0xc0, 0xcb, 0x72, 0x5e, 0x52, 0x8d, 0x7f, 0xc7, 0x7d,
	0x83, 0x51, 0x52, 0x86, 0x8d, 0x3e, 0xb4, 0xd0, 0x31, 0x79, 0x0b, 0x3d, 0xa3, 0x53, 0xbd, 0xca,
	0xa3, 0xd6, 0x2a, 0x6d, 0x19, 0x03, 0x0b, 0x22, 0x67, 0xe0, 0xde, 0x23, 0x8f, 0x62, 0x3d, 0xee,
	0x5a, 0xad, 0xea, 0x93, 0x3f, 0x87, 0x41, 0x52, 0xda, 0xd1, 0x96, 0xf3, 0x12, 0x9c, 0x04, 0x37,
	0x35, 0xe5, 0xe3, 0x16, 0xe5, 0xde, 0x5d, 0x02, 0x03, 0xfb, 0x23, 0xe9, 0xaf, 0x2e, 0xf4, 0x0d,
	0x9d, 0xcc, 0xb9, 0xde, 0x90, 0x19, 0x74, 0xd9, 0xca, 0x52, 0x0e, 0xaf, 0x9f, 0xb7, 0xb7, 0x6c,
	0x10, 0x13, 0xb6, 0xa6, 0x4a, 0xf1, 0x15, 0x67, 0x54, 0x73, 0x29, 0x82, 0x2e, 0x5b, 0x91, 0x0b,
	0xf0, 0x2a, 0xb2, 0x50, 0xc7, 0x39, 0xaa, 0x58, 0xae, 0x97, 0xf5, 0x90, 0x51, 0x95, 0xff, 0xda,
	0xa4, 0xc9, 0x27, 0x38, 0x69, 0xeb, 0xa2, 0xc6, 0xce, 0xb9, 0xb3, 0xb7, 0xfd, 0x9e, 0x74, 0x41,
	0x63, 0xb4, 0x5b, 0x83, 0x27, 0x33, 0xe8, 0x37, 0x02, 0xa8, 0x71, 0xcf, 0x36, 0x9f, 0xed, 0x36,
	0x37, 0xe5, 0xe0, 0x28, 0xc1, 0x8d, 0x6d, 0xf2, 0x3f, 0xc2, 0x70, 0x77, 0x6d, 0xd2, 0x87, 0x03,
	0x79, 0x2f, 0x30, 0xf7, 0xfe, 0x23, 0x00, 0x2e, 0x65, 0x9a, 0x97, 0xe8, 0x75, 0xc8, 0xa1, 0x95,
	0xd4, 0xeb, 0x92, 0x01, 0x1c, 0x66, 0x52, 0x69, 0x2e, 0x22, 0xcf, 0xf1, 0xaf, 0x60, 0xa8, 0x79,
	0x8a, 0x61, 0x26, 0xb9, 0xd0, 0xa1, 0x42, 0x46, 0x9e, 0xc1, 0xa0, 0xd0, 0xcc, 0x84, 0x52, 0x2c,
	0x55, 0x6d, 0x69, 0x28, 0x34, 0x9b, 0x57, 0x19, 0xdf, 0x87, 0xa1, 0xe2, 0x91, 0xa0, 0xba, 0xc8,
	0xb1, 0x32, 0x8a, 0x07, 0x8e, 0xe2, 0x51, 0xed, 0x13, 0x13, 0xfa, 0x4f, 0xc0, 0x55, 0x31, 0xbd,
	0xfe, 0x70, 0x63, 0x4c, 0x14, 0x53, 0x15, 0x37, 0x26, 0x32, 0xb1, 0xff, 0xb3, 0x03, 0x5e, 0xf5,
	0x78, 0xb2, 0x5c, 0x66, 0x98, 0x6b, 0x8e, 0x8a, 0xdc, 0xc2, 0x69, 0xa3, 0x0d, 0xcb, 0xd1, 0x5e,
	0x25, 0x5c, 0x61, 0x63, 0xab, 0x51, 0x4b, 0x08, 0xf3, 0x6a, 0x02, 0x52, 0x83, 0x3f, 0xd7, 0xd8,
	0x2f, 0x88, 0xe4, 0x12, 0x48, 0x4a, 0x7f, 0xf0, 0xb4, 0x48, 0xc3, 0xc5, 0x5a, 0xb2, 0x24, 0x54,
	0xfc, 0x01, 0xeb, 0xdf, 0xe5, 0xd5, 0x95, 0x3b, 0x53, 0x98, 0xf3, 0x07, 0xbc, 0xbb, 0xfc, 0xfe,
	0x26, 0xe2, 0x3a, 0x2e, 0x16, 0x13, 0x26, 0xd3, 0x29, 0x93, 0xca, 0xae, 0x34, 0x65, 0x52, 0x68,
	0x14, 0x5a, 0xaa, 0x77, 0x91, 0x9c, 0x6e, 0x87, 0x2e, 0x5c, 0x1b, 0xce, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0x37, 0xd6, 0x67, 0x3f, 0x04, 0x00, 0x00,
}
