// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prototype/type.proto

package prototype // import "github.com/coschain/contentos-go/prototype"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountName struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountName) Reset()         { *m = AccountName{} }
func (m *AccountName) String() string { return proto.CompactTextString(m) }
func (*AccountName) ProtoMessage()    {}
func (*AccountName) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{0}
}
func (m *AccountName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountName.Unmarshal(m, b)
}
func (m *AccountName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountName.Marshal(b, m, deterministic)
}
func (dst *AccountName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountName.Merge(dst, src)
}
func (m *AccountName) XXX_Size() int {
	return xxx_messageInfo_AccountName.Size(m)
}
func (m *AccountName) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountName.DiscardUnknown(m)
}

var xxx_messageInfo_AccountName proto.InternalMessageInfo

func (m *AccountName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ChainId struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainId) Reset()         { *m = ChainId{} }
func (m *ChainId) String() string { return proto.CompactTextString(m) }
func (*ChainId) ProtoMessage()    {}
func (*ChainId) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{1}
}
func (m *ChainId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainId.Unmarshal(m, b)
}
func (m *ChainId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainId.Marshal(b, m, deterministic)
}
func (dst *ChainId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainId.Merge(dst, src)
}
func (m *ChainId) XXX_Size() int {
	return xxx_messageInfo_ChainId.Size(m)
}
func (m *ChainId) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainId.DiscardUnknown(m)
}

var xxx_messageInfo_ChainId proto.InternalMessageInfo

func (m *ChainId) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Coin struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coin) Reset()         { *m = Coin{} }
func (m *Coin) String() string { return proto.CompactTextString(m) }
func (*Coin) ProtoMessage()    {}
func (*Coin) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{2}
}
func (m *Coin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coin.Unmarshal(m, b)
}
func (m *Coin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coin.Marshal(b, m, deterministic)
}
func (dst *Coin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coin.Merge(dst, src)
}
func (m *Coin) XXX_Size() int {
	return xxx_messageInfo_Coin.Size(m)
}
func (m *Coin) XXX_DiscardUnknown() {
	xxx_messageInfo_Coin.DiscardUnknown(m)
}

var xxx_messageInfo_Coin proto.InternalMessageInfo

func (m *Coin) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Vest struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vest) Reset()         { *m = Vest{} }
func (m *Vest) String() string { return proto.CompactTextString(m) }
func (*Vest) ProtoMessage()    {}
func (*Vest) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{3}
}
func (m *Vest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vest.Unmarshal(m, b)
}
func (m *Vest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vest.Marshal(b, m, deterministic)
}
func (dst *Vest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vest.Merge(dst, src)
}
func (m *Vest) XXX_Size() int {
	return xxx_messageInfo_Vest.Size(m)
}
func (m *Vest) XXX_DiscardUnknown() {
	xxx_messageInfo_Vest.DiscardUnknown(m)
}

var xxx_messageInfo_Vest proto.InternalMessageInfo

func (m *Vest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PublicKeyType struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyType) Reset()         { *m = PublicKeyType{} }
func (m *PublicKeyType) String() string { return proto.CompactTextString(m) }
func (*PublicKeyType) ProtoMessage()    {}
func (*PublicKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{4}
}
func (m *PublicKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyType.Unmarshal(m, b)
}
func (m *PublicKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyType.Marshal(b, m, deterministic)
}
func (dst *PublicKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyType.Merge(dst, src)
}
func (m *PublicKeyType) XXX_Size() int {
	return xxx_messageInfo_PublicKeyType.Size(m)
}
func (m *PublicKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyType proto.InternalMessageInfo

func (m *PublicKeyType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrivateKeyType struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKeyType) Reset()         { *m = PrivateKeyType{} }
func (m *PrivateKeyType) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyType) ProtoMessage()    {}
func (*PrivateKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{5}
}
func (m *PrivateKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyType.Unmarshal(m, b)
}
func (m *PrivateKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyType.Marshal(b, m, deterministic)
}
func (dst *PrivateKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyType.Merge(dst, src)
}
func (m *PrivateKeyType) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyType.Size(m)
}
func (m *PrivateKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyType proto.InternalMessageInfo

func (m *PrivateKeyType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TimePointSec struct {
	UtcSeconds           uint32   `protobuf:"varint,1,opt,name=utc_seconds,json=utcSeconds,proto3" json:"utc_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimePointSec) Reset()         { *m = TimePointSec{} }
func (m *TimePointSec) String() string { return proto.CompactTextString(m) }
func (*TimePointSec) ProtoMessage()    {}
func (*TimePointSec) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{6}
}
func (m *TimePointSec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimePointSec.Unmarshal(m, b)
}
func (m *TimePointSec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimePointSec.Marshal(b, m, deterministic)
}
func (dst *TimePointSec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimePointSec.Merge(dst, src)
}
func (m *TimePointSec) XXX_Size() int {
	return xxx_messageInfo_TimePointSec.Size(m)
}
func (m *TimePointSec) XXX_DiscardUnknown() {
	xxx_messageInfo_TimePointSec.DiscardUnknown(m)
}

var xxx_messageInfo_TimePointSec proto.InternalMessageInfo

func (m *TimePointSec) GetUtcSeconds() uint32 {
	if m != nil {
		return m.UtcSeconds
	}
	return 0
}

type SignatureType struct {
	Sig                  []byte   `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureType) Reset()         { *m = SignatureType{} }
func (m *SignatureType) String() string { return proto.CompactTextString(m) }
func (*SignatureType) ProtoMessage()    {}
func (*SignatureType) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{7}
}
func (m *SignatureType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureType.Unmarshal(m, b)
}
func (m *SignatureType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureType.Marshal(b, m, deterministic)
}
func (dst *SignatureType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureType.Merge(dst, src)
}
func (m *SignatureType) XXX_Size() int {
	return xxx_messageInfo_SignatureType.Size(m)
}
func (m *SignatureType) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureType.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureType proto.InternalMessageInfo

func (m *SignatureType) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Sha256 struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sha256) Reset()         { *m = Sha256{} }
func (m *Sha256) String() string { return proto.CompactTextString(m) }
func (*Sha256) ProtoMessage()    {}
func (*Sha256) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{8}
}
func (m *Sha256) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sha256.Unmarshal(m, b)
}
func (m *Sha256) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sha256.Marshal(b, m, deterministic)
}
func (dst *Sha256) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sha256.Merge(dst, src)
}
func (m *Sha256) XXX_Size() int {
	return xxx_messageInfo_Sha256.Size(m)
}
func (m *Sha256) XXX_DiscardUnknown() {
	xxx_messageInfo_Sha256.DiscardUnknown(m)
}

var xxx_messageInfo_Sha256 proto.InternalMessageInfo

func (m *Sha256) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GiftTicketKeyType struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	CreateBlock          uint64   `protobuf:"varint,4,opt,name=create_block,json=createBlock,proto3" json:"create_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GiftTicketKeyType) Reset()         { *m = GiftTicketKeyType{} }
func (m *GiftTicketKeyType) String() string { return proto.CompactTextString(m) }
func (*GiftTicketKeyType) ProtoMessage()    {}
func (*GiftTicketKeyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{9}
}
func (m *GiftTicketKeyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiftTicketKeyType.Unmarshal(m, b)
}
func (m *GiftTicketKeyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiftTicketKeyType.Marshal(b, m, deterministic)
}
func (dst *GiftTicketKeyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiftTicketKeyType.Merge(dst, src)
}
func (m *GiftTicketKeyType) XXX_Size() int {
	return xxx_messageInfo_GiftTicketKeyType.Size(m)
}
func (m *GiftTicketKeyType) XXX_DiscardUnknown() {
	xxx_messageInfo_GiftTicketKeyType.DiscardUnknown(m)
}

var xxx_messageInfo_GiftTicketKeyType proto.InternalMessageInfo

func (m *GiftTicketKeyType) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GiftTicketKeyType) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GiftTicketKeyType) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *GiftTicketKeyType) GetCreateBlock() uint64 {
	if m != nil {
		return m.CreateBlock
	}
	return 0
}

type ChainProperties struct {
	AccountCreationFee   *Coin    `protobuf:"bytes,1,opt,name=account_creation_fee,json=accountCreationFee,proto3" json:"account_creation_fee,omitempty"`
	MaximumBlockSize     uint32   `protobuf:"varint,2,opt,name=maximum_block_size,json=maximumBlockSize,proto3" json:"maximum_block_size,omitempty"`
	StaminaFree          uint64   `protobuf:"varint,3,opt,name=stamina_free,json=staminaFree,proto3" json:"stamina_free,omitempty"`
	TpsExpected          uint64   `protobuf:"varint,4,opt,name=tps_expected,json=tpsExpected,proto3" json:"tps_expected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainProperties) Reset()         { *m = ChainProperties{} }
func (m *ChainProperties) String() string { return proto.CompactTextString(m) }
func (*ChainProperties) ProtoMessage()    {}
func (*ChainProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{10}
}
func (m *ChainProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainProperties.Unmarshal(m, b)
}
func (m *ChainProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainProperties.Marshal(b, m, deterministic)
}
func (dst *ChainProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainProperties.Merge(dst, src)
}
func (m *ChainProperties) XXX_Size() int {
	return xxx_messageInfo_ChainProperties.Size(m)
}
func (m *ChainProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ChainProperties proto.InternalMessageInfo

func (m *ChainProperties) GetAccountCreationFee() *Coin {
	if m != nil {
		return m.AccountCreationFee
	}
	return nil
}

func (m *ChainProperties) GetMaximumBlockSize() uint32 {
	if m != nil {
		return m.MaximumBlockSize
	}
	return 0
}

func (m *ChainProperties) GetStaminaFree() uint64 {
	if m != nil {
		return m.StaminaFree
	}
	return 0
}

func (m *ChainProperties) GetTpsExpected() uint64 {
	if m != nil {
		return m.TpsExpected
	}
	return 0
}

type DynamicProperties struct {
	HeadBlockId             *Sha256       `protobuf:"bytes,2,opt,name=head_block_id,json=headBlockId,proto3" json:"head_block_id,omitempty"`
	HeadBlockNumber         uint64        `protobuf:"varint,3,opt,name=head_block_number,json=headBlockNumber,proto3" json:"head_block_number,omitempty"`
	MaximumBlockSize        uint32        `protobuf:"varint,4,opt,name=maximum_block_size,json=maximumBlockSize,proto3" json:"maximum_block_size,omitempty"`
	TotalCos                *Coin         `protobuf:"bytes,5,opt,name=total_cos,json=totalCos,proto3" json:"total_cos,omitempty"`
	Time                    *TimePointSec `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	CurrentWitness          *AccountName  `protobuf:"bytes,7,opt,name=current_witness,json=currentWitness,proto3" json:"current_witness,omitempty"`
	Tps                     uint32        `protobuf:"varint,9,opt,name=tps,proto3" json:"tps,omitempty"`
	TotalVestingShares      *Vest         `protobuf:"bytes,10,opt,name=total_vesting_shares,json=totalVestingShares,proto3" json:"total_vesting_shares,omitempty"`
	CurrentSupply           *Coin         `protobuf:"bytes,11,opt,name=current_supply,json=currentSupply,proto3" json:"current_supply,omitempty"`
	PostWeightedVps         string        `protobuf:"bytes,13,opt,name=post_weighted_vps,json=postWeightedVps,proto3" json:"post_weighted_vps,omitempty"`
	PostRewards             *Vest         `protobuf:"bytes,14,opt,name=post_rewards,json=postRewards,proto3" json:"post_rewards,omitempty"`
	TotalTrxCnt             uint64        `protobuf:"varint,15,opt,name=total_trx_cnt,json=totalTrxCnt,proto3" json:"total_trx_cnt,omitempty"`
	TotalPostCnt            uint64        `protobuf:"varint,16,opt,name=total_post_cnt,json=totalPostCnt,proto3" json:"total_post_cnt,omitempty"`
	TotalUserCnt            uint64        `protobuf:"varint,17,opt,name=total_user_cnt,json=totalUserCnt,proto3" json:"total_user_cnt,omitempty"`
	MaxTps                  uint32        `protobuf:"varint,18,opt,name=max_tps,json=maxTps,proto3" json:"max_tps,omitempty"`
	MaxTpsBlockNum          uint64        `protobuf:"varint,19,opt,name=max_tps_block_num,json=maxTpsBlockNum,proto3" json:"max_tps_block_num,omitempty"`
	HeadBlockPrefix         uint32        `protobuf:"varint,20,opt,name=head_block_prefix,json=headBlockPrefix,proto3" json:"head_block_prefix,omitempty"`
	ReportRewards           *Vest         `protobuf:"bytes,21,opt,name=report_rewards,json=reportRewards,proto3" json:"report_rewards,omitempty"`
	IthYear                 uint32        `protobuf:"varint,22,opt,name=ith_year,json=ithYear,proto3" json:"ith_year,omitempty"`
	AnnualBudget            *Vest         `protobuf:"bytes,23,opt,name=annual_budget,json=annualBudget,proto3" json:"annual_budget,omitempty"`
	AnnualMinted            *Vest         `protobuf:"bytes,24,opt,name=annual_minted,json=annualMinted,proto3" json:"annual_minted,omitempty"`
	PostDappRewards         *Vest         `protobuf:"bytes,25,opt,name=post_dapp_rewards,json=postDappRewards,proto3" json:"post_dapp_rewards,omitempty"`
	VoterRewards            *Vest         `protobuf:"bytes,26,opt,name=voter_rewards,json=voterRewards,proto3" json:"voter_rewards,omitempty"`
	ReplyRewards            *Vest         `protobuf:"bytes,27,opt,name=reply_rewards,json=replyRewards,proto3" json:"reply_rewards,omitempty"`
	ReplyWeightedVps        string        `protobuf:"bytes,28,opt,name=reply_weighted_vps,json=replyWeightedVps,proto3" json:"reply_weighted_vps,omitempty"`
	ReplyDappRewards        *Vest         `protobuf:"bytes,29,opt,name=reply_dapp_rewards,json=replyDappRewards,proto3" json:"reply_dapp_rewards,omitempty"`
	StakeVestingShares      *Vest         `protobuf:"bytes,30,opt,name=stake_vesting_shares,json=stakeVestingShares,proto3" json:"stake_vesting_shares,omitempty"`
	WitnessBootCompleted    bool          `protobuf:"varint,31,opt,name=witness_boot_completed,json=witnessBootCompleted,proto3" json:"witness_boot_completed,omitempty"`
	StaminaFree             uint64        `protobuf:"varint,32,opt,name=stamina_free,json=staminaFree,proto3" json:"stamina_free,omitempty"`
	TpsExpected             uint64        `protobuf:"varint,33,opt,name=tps_expected,json=tpsExpected,proto3" json:"tps_expected,omitempty"`
	AvgTpsUpdateBlock       uint64        `protobuf:"varint,34,opt,name=avg_tps_update_block,json=avgTpsUpdateBlock,proto3" json:"avg_tps_update_block,omitempty"`
	AvgTpsInWindow          uint64        `protobuf:"varint,35,opt,name=avg_tps_in_window,json=avgTpsInWindow,proto3" json:"avg_tps_in_window,omitempty"`
	OneDayStamina           uint64        `protobuf:"varint,36,opt,name=one_day_stamina,json=oneDayStamina,proto3" json:"one_day_stamina,omitempty"`
	AccountCreateFee        *Coin         `protobuf:"bytes,37,opt,name=account_create_fee,json=accountCreateFee,proto3" json:"account_create_fee,omitempty"`
	CurrentEpochStartBlock  uint64        `protobuf:"varint,38,opt,name=current_epoch_start_block,json=currentEpochStartBlock,proto3" json:"current_epoch_start_block,omitempty"`
	EpochDuration           uint64        `protobuf:"varint,39,opt,name=epoch_duration,json=epochDuration,proto3" json:"epoch_duration,omitempty"`
	DistributeBootCompleted bool          `protobuf:"varint,40,opt,name=distribute_boot_completed,json=distributeBootCompleted,proto3" json:"distribute_boot_completed,omitempty"`
	TopNAcquireFreeToken    uint32        `protobuf:"varint,41,opt,name=top_n_acquire_free_token,json=topNAcquireFreeToken,proto3" json:"top_n_acquire_free_token,omitempty"`
	TicketPrice             uint64        `protobuf:"varint,42,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	TicketFeeToBp           *Vest         `protobuf:"bytes,43,opt,name=ticket_fee_to_bp,json=ticketFeeToBp,proto3" json:"ticket_fee_to_bp,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *DynamicProperties) Reset()         { *m = DynamicProperties{} }
func (m *DynamicProperties) String() string { return proto.CompactTextString(m) }
func (*DynamicProperties) ProtoMessage()    {}
func (*DynamicProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{11}
}
func (m *DynamicProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicProperties.Unmarshal(m, b)
}
func (m *DynamicProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicProperties.Marshal(b, m, deterministic)
}
func (dst *DynamicProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicProperties.Merge(dst, src)
}
func (m *DynamicProperties) XXX_Size() int {
	return xxx_messageInfo_DynamicProperties.Size(m)
}
func (m *DynamicProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicProperties.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicProperties proto.InternalMessageInfo

func (m *DynamicProperties) GetHeadBlockId() *Sha256 {
	if m != nil {
		return m.HeadBlockId
	}
	return nil
}

func (m *DynamicProperties) GetHeadBlockNumber() uint64 {
	if m != nil {
		return m.HeadBlockNumber
	}
	return 0
}

func (m *DynamicProperties) GetMaximumBlockSize() uint32 {
	if m != nil {
		return m.MaximumBlockSize
	}
	return 0
}

func (m *DynamicProperties) GetTotalCos() *Coin {
	if m != nil {
		return m.TotalCos
	}
	return nil
}

func (m *DynamicProperties) GetTime() *TimePointSec {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *DynamicProperties) GetCurrentWitness() *AccountName {
	if m != nil {
		return m.CurrentWitness
	}
	return nil
}

func (m *DynamicProperties) GetTps() uint32 {
	if m != nil {
		return m.Tps
	}
	return 0
}

func (m *DynamicProperties) GetTotalVestingShares() *Vest {
	if m != nil {
		return m.TotalVestingShares
	}
	return nil
}

func (m *DynamicProperties) GetCurrentSupply() *Coin {
	if m != nil {
		return m.CurrentSupply
	}
	return nil
}

func (m *DynamicProperties) GetPostWeightedVps() string {
	if m != nil {
		return m.PostWeightedVps
	}
	return ""
}

func (m *DynamicProperties) GetPostRewards() *Vest {
	if m != nil {
		return m.PostRewards
	}
	return nil
}

func (m *DynamicProperties) GetTotalTrxCnt() uint64 {
	if m != nil {
		return m.TotalTrxCnt
	}
	return 0
}

func (m *DynamicProperties) GetTotalPostCnt() uint64 {
	if m != nil {
		return m.TotalPostCnt
	}
	return 0
}

func (m *DynamicProperties) GetTotalUserCnt() uint64 {
	if m != nil {
		return m.TotalUserCnt
	}
	return 0
}

func (m *DynamicProperties) GetMaxTps() uint32 {
	if m != nil {
		return m.MaxTps
	}
	return 0
}

func (m *DynamicProperties) GetMaxTpsBlockNum() uint64 {
	if m != nil {
		return m.MaxTpsBlockNum
	}
	return 0
}

func (m *DynamicProperties) GetHeadBlockPrefix() uint32 {
	if m != nil {
		return m.HeadBlockPrefix
	}
	return 0
}

func (m *DynamicProperties) GetReportRewards() *Vest {
	if m != nil {
		return m.ReportRewards
	}
	return nil
}

func (m *DynamicProperties) GetIthYear() uint32 {
	if m != nil {
		return m.IthYear
	}
	return 0
}

func (m *DynamicProperties) GetAnnualBudget() *Vest {
	if m != nil {
		return m.AnnualBudget
	}
	return nil
}

func (m *DynamicProperties) GetAnnualMinted() *Vest {
	if m != nil {
		return m.AnnualMinted
	}
	return nil
}

func (m *DynamicProperties) GetPostDappRewards() *Vest {
	if m != nil {
		return m.PostDappRewards
	}
	return nil
}

func (m *DynamicProperties) GetVoterRewards() *Vest {
	if m != nil {
		return m.VoterRewards
	}
	return nil
}

func (m *DynamicProperties) GetReplyRewards() *Vest {
	if m != nil {
		return m.ReplyRewards
	}
	return nil
}

func (m *DynamicProperties) GetReplyWeightedVps() string {
	if m != nil {
		return m.ReplyWeightedVps
	}
	return ""
}

func (m *DynamicProperties) GetReplyDappRewards() *Vest {
	if m != nil {
		return m.ReplyDappRewards
	}
	return nil
}

func (m *DynamicProperties) GetStakeVestingShares() *Vest {
	if m != nil {
		return m.StakeVestingShares
	}
	return nil
}

func (m *DynamicProperties) GetWitnessBootCompleted() bool {
	if m != nil {
		return m.WitnessBootCompleted
	}
	return false
}

func (m *DynamicProperties) GetStaminaFree() uint64 {
	if m != nil {
		return m.StaminaFree
	}
	return 0
}

func (m *DynamicProperties) GetTpsExpected() uint64 {
	if m != nil {
		return m.TpsExpected
	}
	return 0
}

func (m *DynamicProperties) GetAvgTpsUpdateBlock() uint64 {
	if m != nil {
		return m.AvgTpsUpdateBlock
	}
	return 0
}

func (m *DynamicProperties) GetAvgTpsInWindow() uint64 {
	if m != nil {
		return m.AvgTpsInWindow
	}
	return 0
}

func (m *DynamicProperties) GetOneDayStamina() uint64 {
	if m != nil {
		return m.OneDayStamina
	}
	return 0
}

func (m *DynamicProperties) GetAccountCreateFee() *Coin {
	if m != nil {
		return m.AccountCreateFee
	}
	return nil
}

func (m *DynamicProperties) GetCurrentEpochStartBlock() uint64 {
	if m != nil {
		return m.CurrentEpochStartBlock
	}
	return 0
}

func (m *DynamicProperties) GetEpochDuration() uint64 {
	if m != nil {
		return m.EpochDuration
	}
	return 0
}

func (m *DynamicProperties) GetDistributeBootCompleted() bool {
	if m != nil {
		return m.DistributeBootCompleted
	}
	return false
}

func (m *DynamicProperties) GetTopNAcquireFreeToken() uint32 {
	if m != nil {
		return m.TopNAcquireFreeToken
	}
	return 0
}

func (m *DynamicProperties) GetTicketPrice() uint64 {
	if m != nil {
		return m.TicketPrice
	}
	return 0
}

func (m *DynamicProperties) GetTicketFeeToBp() *Vest {
	if m != nil {
		return m.TicketFeeToBp
	}
	return nil
}

type BeneficiaryRouteType struct {
	Name                 *AccountName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight               uint32       `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BeneficiaryRouteType) Reset()         { *m = BeneficiaryRouteType{} }
func (m *BeneficiaryRouteType) String() string { return proto.CompactTextString(m) }
func (*BeneficiaryRouteType) ProtoMessage()    {}
func (*BeneficiaryRouteType) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_2d1c6a5c416a3f2a, []int{12}
}
func (m *BeneficiaryRouteType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeneficiaryRouteType.Unmarshal(m, b)
}
func (m *BeneficiaryRouteType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeneficiaryRouteType.Marshal(b, m, deterministic)
}
func (dst *BeneficiaryRouteType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeneficiaryRouteType.Merge(dst, src)
}
func (m *BeneficiaryRouteType) XXX_Size() int {
	return xxx_messageInfo_BeneficiaryRouteType.Size(m)
}
func (m *BeneficiaryRouteType) XXX_DiscardUnknown() {
	xxx_messageInfo_BeneficiaryRouteType.DiscardUnknown(m)
}

var xxx_messageInfo_BeneficiaryRouteType proto.InternalMessageInfo

func (m *BeneficiaryRouteType) GetName() *AccountName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BeneficiaryRouteType) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountName)(nil), "prototype.account_name")
	proto.RegisterType((*ChainId)(nil), "prototype.chain_id")
	proto.RegisterType((*Coin)(nil), "prototype.coin")
	proto.RegisterType((*Vest)(nil), "prototype.vest")
	proto.RegisterType((*PublicKeyType)(nil), "prototype.public_key_type")
	proto.RegisterType((*PrivateKeyType)(nil), "prototype.private_key_type")
	proto.RegisterType((*TimePointSec)(nil), "prototype.time_point_sec")
	proto.RegisterType((*SignatureType)(nil), "prototype.signature_type")
	proto.RegisterType((*Sha256)(nil), "prototype.sha256")
	proto.RegisterType((*GiftTicketKeyType)(nil), "prototype.gift_ticket_key_type")
	proto.RegisterType((*ChainProperties)(nil), "prototype.chain_properties")
	proto.RegisterType((*DynamicProperties)(nil), "prototype.dynamic_properties")
	proto.RegisterType((*BeneficiaryRouteType)(nil), "prototype.beneficiary_route_type")
}

func init() { proto.RegisterFile("prototype/type.proto", fileDescriptor_type_2d1c6a5c416a3f2a) }

var fileDescriptor_type_2d1c6a5c416a3f2a = []byte{
	// 1237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x96, 0xdb, 0x6e, 0x1b, 0x37,
	0x13, 0x80, 0x61, 0x47, 0x71, 0x6c, 0xca, 0x3a, 0x98, 0xbf, 0x7e, 0x7b, 0xdd, 0xa6, 0x8d, 0xa3,
	0x26, 0x69, 0x8e, 0x76, 0xeb, 0x26, 0x41, 0x0f, 0x28, 0xd0, 0xd8, 0x49, 0x80, 0x5c, 0x34, 0x30,
	0x64, 0x27, 0x41, 0x0b, 0x14, 0x04, 0xb5, 0x3b, 0x96, 0x08, 0x6b, 0x49, 0x86, 0xe4, 0xca, 0x52,
	0x5e, 0xa6, 0xcf, 0xd3, 0xb7, 0x2a, 0x38, 0xa4, 0xa4, 0x55, 0x22, 0xa5, 0x37, 0x12, 0x77, 0xe6,
	0x1b, 0xce, 0x0c, 0x67, 0x78, 0x20, 0x2d, 0x6d, 0x94, 0x53, 0x6e, 0xac, 0xe1, 0xc0, 0xff, 0xec,
	0xe3, 0x27, 0xdd, 0x98, 0x4a, 0xdb, 0xb7, 0xc8, 0x26, 0x4f, 0x53, 0x55, 0x48, 0xc7, 0x24, 0xcf,
	0x81, 0xb6, 0xc8, 0xd5, 0x21, 0x1f, 0x14, 0x90, 0xac, 0xec, 0xad, 0xdc, 0xdd, 0xe8, 0x84, 0x8f,
	0xf6, 0x1e, 0x59, 0x4f, 0xfb, 0x5c, 0x48, 0x26, 0xb2, 0x79, 0xa2, 0x36, 0x23, 0x2a, 0xa9, 0x12,
	0x92, 0x26, 0x65, 0x6d, 0xe5, 0x68, 0xf5, 0xbb, 0x95, 0x12, 0x31, 0x04, 0xeb, 0x3e, 0x43, 0xdc,
	0x26, 0x0d, 0x5d, 0x74, 0x07, 0x22, 0x65, 0x17, 0x30, 0x66, 0x3e, 0x3c, 0x4a, 0x49, 0x25, 0xe3,
	0x8e, 0x23, 0xbb, 0xd9, 0xc1, 0x71, 0xfb, 0x0e, 0x69, 0x6a, 0x23, 0x86, 0xdc, 0xc1, 0xe7, 0xb9,
	0xef, 0x49, 0xdd, 0x89, 0x1c, 0x98, 0x56, 0x42, 0x3a, 0x66, 0x21, 0xa5, 0x37, 0x48, 0xb5, 0x70,
	0xa9, 0x1f, 0x2a, 0x99, 0xd9, 0x98, 0x00, 0x29, 0x5c, 0x7a, 0x1a, 0x24, 0xed, 0x36, 0xa9, 0x5b,
	0xd1, 0x93, 0xdc, 0x15, 0x06, 0xc2, 0xc4, 0x4d, 0x72, 0xc5, 0x8a, 0x5e, 0x9c, 0xd7, 0x0f, 0xdb,
	0xd7, 0xc9, 0x9a, 0xed, 0xf3, 0xc3, 0x27, 0x4f, 0xbd, 0xd3, 0x3e, 0xb7, 0xfd, 0x89, 0x53, 0x3f,
	0x6e, 0xbf, 0x27, 0xad, 0x9e, 0x38, 0x77, 0xcc, 0x89, 0xf4, 0x02, 0xdc, 0x5c, 0x80, 0xfe, 0x3f,
	0xfa, 0xac, 0x4c, 0x64, 0xe7, 0x46, 0xe5, 0xc9, 0x6a, 0xb0, 0xf7, 0x63, 0x5a, 0x27, 0xab, 0x4e,
	0x25, 0x57, 0x50, 0xb2, 0xea, 0x14, 0xbd, 0x49, 0x36, 0x53, 0x03, 0x3e, 0xd7, 0xee, 0x40, 0xa5,
	0x17, 0x49, 0xc5, 0x2f, 0x5a, 0xa7, 0x1a, 0x64, 0x47, 0x5e, 0xd4, 0xfe, 0x67, 0x85, 0x34, 0x43,
	0x75, 0xb4, 0x51, 0x1a, 0x8c, 0x13, 0x60, 0xe9, 0x33, 0xd2, 0x9a, 0xd4, 0x15, 0x59, 0xa1, 0x24,
	0x3b, 0x87, 0xe0, 0xbf, 0x7a, 0xd8, 0xd8, 0x9f, 0x76, 0xc0, 0xbe, 0x2f, 0x5b, 0x87, 0x46, 0xf8,
	0x38, 0xb2, 0x2f, 0x01, 0xe8, 0x43, 0x42, 0x73, 0x3e, 0x12, 0x79, 0x91, 0x07, 0xdf, 0xcc, 0x8a,
	0x0f, 0x80, 0xc1, 0xd6, 0x3a, 0xcd, 0xa8, 0xc1, 0x08, 0x4e, 0xc5, 0x07, 0xf0, 0x81, 0x5a, 0xc7,
	0x73, 0x21, 0x39, 0x3b, 0x37, 0x00, 0x98, 0x42, 0xa5, 0x53, 0x8d, 0xb2, 0x97, 0x06, 0x10, 0x71,
	0xda, 0x32, 0x18, 0x69, 0x48, 0x1d, 0x64, 0x93, 0x5c, 0x9c, 0xb6, 0x2f, 0xa2, 0xa8, 0xfd, 0x77,
	0x83, 0xd0, 0x6c, 0x2c, 0x79, 0x2e, 0xd2, 0x72, 0x36, 0x4f, 0x48, 0xad, 0x0f, 0x3c, 0x8b, 0x71,
	0x88, 0x0c, 0xa3, 0xa8, 0x1e, 0x6e, 0x95, 0xd2, 0x08, 0x35, 0xe9, 0x54, 0x3d, 0x87, 0x51, 0xbd,
	0xca, 0xe8, 0x7d, 0xb2, 0x55, 0x32, 0x93, 0x45, 0xde, 0x05, 0x13, 0x03, 0x6b, 0x4c, 0xb9, 0xd7,
	0x28, 0x5e, 0x92, 0x6d, 0x65, 0x49, 0xb6, 0x0f, 0xc9, 0x86, 0x53, 0x8e, 0x0f, 0x58, 0xaa, 0x6c,
	0x72, 0x75, 0xf1, 0x9a, 0xae, 0x23, 0x71, 0xac, 0x2c, 0x7d, 0x44, 0x2a, 0xbe, 0x13, 0x93, 0x35,
	0x04, 0x77, 0x4b, 0xe0, 0x7c, 0x83, 0x76, 0x10, 0xa3, 0xbf, 0x91, 0x46, 0x5a, 0x18, 0x03, 0xd2,
	0xb1, 0x4b, 0xe1, 0x24, 0x58, 0x9b, 0x5c, 0x43, 0xcb, 0x9d, 0x92, 0x65, 0x79, 0xd7, 0x76, 0xea,
	0x91, 0x7f, 0x17, 0x70, 0xdf, 0xb5, 0x4e, 0xdb, 0x64, 0x03, 0xa3, 0xf7, 0x43, 0xdf, 0x0f, 0x21,
	0x60, 0xbf, 0x07, 0x85, 0xec, 0x31, 0xdb, 0xe7, 0x06, 0x6c, 0x42, 0x3e, 0x89, 0xdd, 0x03, 0x1d,
	0x8a, 0xf0, 0xdb, 0xc0, 0x9e, 0x22, 0x4a, 0x9f, 0x92, 0x89, 0x1b, 0x66, 0x0b, 0xad, 0x07, 0xe3,
	0xa4, 0xba, 0x38, 0xf1, 0x5a, 0xc4, 0x4e, 0x91, 0xf2, 0x55, 0xd0, 0xca, 0x3a, 0x76, 0x09, 0xa2,
	0xd7, 0x77, 0x90, 0xb1, 0xa1, 0xb6, 0x49, 0x0d, 0x8f, 0x97, 0x86, 0x57, 0xbc, 0x8b, 0xf2, 0xb7,
	0xda, 0xd2, 0x43, 0xb2, 0x89, 0xac, 0x81, 0x4b, 0x6e, 0x32, 0x9b, 0xd4, 0x17, 0x87, 0x57, 0xf5,
	0x50, 0x27, 0x30, 0xb4, 0x4d, 0x6a, 0x21, 0x35, 0x67, 0x46, 0x2c, 0x95, 0x2e, 0x69, 0xc4, 0xbe,
	0xf2, 0xc2, 0x33, 0x33, 0x3a, 0x96, 0x8e, 0xde, 0x22, 0xf5, 0xc0, 0xe0, 0xec, 0x1e, 0x6a, 0x22,
	0xb4, 0x89, 0xd2, 0x13, 0x65, 0xdd, 0x1c, 0x55, 0x58, 0x30, 0x48, 0x6d, 0x95, 0xa8, 0x37, 0x16,
	0x8c, 0xa7, 0x76, 0xc8, 0xb5, 0x9c, 0x8f, 0x98, 0x5f, 0x60, 0x8a, 0x0b, 0xbc, 0x96, 0xf3, 0xd1,
	0x99, 0xf6, 0x65, 0xde, 0x8a, 0x8a, 0x59, 0xc7, 0x25, 0xff, 0x9b, 0x9e, 0x72, 0xf5, 0x80, 0x4d,
	0x9a, 0xee, 0xa3, 0xee, 0xd4, 0x06, 0xce, 0xc5, 0x28, 0x69, 0xe1, 0x8c, 0xb3, 0xee, 0x3c, 0x41,
	0xb1, 0x5f, 0x7b, 0x03, 0x5a, 0x99, 0xd9, 0xca, 0xfc, 0x7f, 0xf1, 0xca, 0xd4, 0x02, 0x36, 0x59,
	0x9b, 0x5d, 0xb2, 0x2e, 0x5c, 0x9f, 0x8d, 0x81, 0x9b, 0x64, 0x1b, 0xa7, 0xbe, 0x26, 0x5c, 0xff,
	0x0f, 0xe0, 0x86, 0x3e, 0x26, 0x35, 0x2e, 0x65, 0xc1, 0x07, 0xac, 0x5b, 0x64, 0x3d, 0x70, 0xc9,
	0xce, 0xe2, 0x19, 0x37, 0x03, 0x75, 0x84, 0x50, 0xc9, 0x2a, 0x17, 0xd2, 0x6f, 0xe2, 0xe4, 0xb3,
	0x56, 0xbf, 0x23, 0x44, 0x7f, 0x89, 0x2d, 0x90, 0x71, 0xad, 0xa7, 0x19, 0xec, 0x2e, 0xb6, 0xc4,
	0x9e, 0x78, 0xce, 0xb5, 0x9e, 0xe4, 0xf0, 0x98, 0xd4, 0x86, 0xca, 0x81, 0x99, 0x1a, 0x7e, 0xb1,
	0xc4, 0x25, 0x52, 0x25, 0x2b, 0x03, 0x7a, 0x30, 0x9e, 0x5a, 0x7d, 0xb9, 0xc4, 0x0a, 0xa9, 0x89,
	0xd5, 0x43, 0x42, 0x83, 0xd5, 0x5c, 0xb3, 0x5e, 0xc7, 0x66, 0x6d, 0xa2, 0xa6, 0xdc, 0xad, 0xbf,
	0x4e, 0xe8, 0xb9, 0xbc, 0xbe, 0x5a, 0xec, 0x28, 0x98, 0x97, 0x13, 0x7b, 0x46, 0x5a, 0xd6, 0xf1,
	0x0b, 0xf8, 0x78, 0x4f, 0x7e, 0xbd, 0x64, 0x4f, 0x22, 0x3c, 0xbf, 0x27, 0x1f, 0x93, 0xed, 0x78,
	0x44, 0xb0, 0xae, 0x52, 0x8e, 0xa5, 0x2a, 0xd7, 0x03, 0xf0, 0x75, 0xb9, 0xb1, 0xb7, 0x72, 0x77,
	0xbd, 0xd3, 0x8a, 0xda, 0x23, 0xa5, 0xdc, 0xf1, 0x44, 0xf7, 0xc9, 0x59, 0xbd, 0xf7, 0xdf, 0x67,
	0xf5, 0xcd, 0x4f, 0xce, 0x6a, 0x7a, 0x40, 0x5a, 0x7c, 0xd8, 0xc3, 0x76, 0x2f, 0x74, 0x36, 0xbb,
	0xa2, 0xda, 0x88, 0x6e, 0xf1, 0x61, 0xef, 0x4c, 0xdb, 0x37, 0xa8, 0xc1, 0x56, 0xa6, 0xf7, 0xc8,
	0xd6, 0xc4, 0x40, 0x48, 0x76, 0x29, 0x64, 0xa6, 0x2e, 0x93, 0x6f, 0x90, 0xae, 0x07, 0xfa, 0x95,
	0x7c, 0x87, 0x52, 0x7a, 0x87, 0x34, 0x94, 0x04, 0x96, 0xf1, 0x31, 0x8b, 0x51, 0x25, 0xb7, 0x10,
	0xac, 0x29, 0x09, 0xcf, 0xf9, 0xf8, 0x34, 0x08, 0x7d, 0x05, 0xe6, 0xae, 0x39, 0xc0, 0x4b, 0xee,
	0xf6, 0xe2, 0x73, 0xa9, 0x59, 0xbe, 0xe4, 0xc0, 0x5f, 0x71, 0x3f, 0x91, 0xdd, 0xc9, 0x91, 0x06,
	0x5a, 0xa5, 0x7d, 0xef, 0xcc, 0xb8, 0x98, 0xc7, 0x1d, 0x74, 0xb8, 0x1d, 0x81, 0x17, 0x5e, 0x7f,
	0xea, 0xd5, 0x21, 0x99, 0xdb, 0xa4, 0x1e, 0x4c, 0xb2, 0xc2, 0xe0, 0x95, 0x99, 0x7c, 0x1b, 0x02,
	0x44, 0xe9, 0xf3, 0x28, 0xa4, 0x3f, 0x93, 0xdd, 0x4c, 0x58, 0x67, 0x44, 0xb7, 0xf0, 0x0b, 0x34,
	0x5f, 0xa3, 0xbb, 0x58, 0xa3, 0x9d, 0x19, 0x30, 0x5f, 0xa6, 0xa7, 0x24, 0x71, 0x4a, 0x33, 0xc9,
	0x78, 0xfa, 0xbe, 0x10, 0x06, 0xb0, 0x58, 0xcc, 0xa9, 0x0b, 0x90, 0xc9, 0x3d, 0xdc, 0xcc, 0x2d,
	0xa7, 0xf4, 0xeb, 0x67, 0x41, 0xeb, 0xcb, 0x76, 0xe6, 0x75, 0x58, 0xbb, 0xf0, 0xfc, 0xd0, 0x46,
	0xa4, 0x90, 0xdc, 0x8f, 0xb5, 0x43, 0xd9, 0x89, 0x17, 0xd1, 0x1f, 0x49, 0x33, 0x22, 0xe7, 0x38,
	0x25, 0xeb, 0xea, 0xe4, 0xc1, 0x92, 0x13, 0x25, 0x80, 0x2f, 0xfd, 0xec, 0x47, 0xba, 0xfd, 0x17,
	0xd9, 0xee, 0x82, 0x84, 0x73, 0x91, 0x0a, 0x6e, 0xc6, 0xcc, 0x28, 0x9f, 0x17, 0x3e, 0x67, 0x1e,
	0x90, 0x8a, 0xbf, 0x8c, 0xe2, 0x13, 0x63, 0xe9, 0x5d, 0x85, 0x10, 0xdd, 0x26, 0x6b, 0x61, 0x8b,
	0xc5, 0x07, 0x45, 0xfc, 0x3a, 0x3a, 0x21, 0x6d, 0xa1, 0xf6, 0x53, 0x25, 0x1d, 0x48, 0xa7, 0xec,
	0x3e, 0x97, 0x99, 0x51, 0x22, 0xdb, 0xb7, 0xd9, 0xc5, 0x6c, 0xc2, 0x3f, 0xef, 0xf7, 0x84, 0xeb,
	0x17, 0xdd, 0xfd, 0x54, 0xe5, 0x07, 0xa9, 0xb2, 0xf8, 0xfa, 0x39, 0x98, 0x1a, 0x3d, 0xea, 0xa9,
	0x83, 0x29, 0xdb, 0x5d, 0xc3, 0xe1, 0x0f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xf7, 0x9b,
	0x57, 0x0b, 0x0b, 0x00, 0x00,
}
